### ISSUE TITLE
Should users be able to review their own sentences?

### ISSUE THREAD

**Issue by mikehenrty** [Common-Voice/sentence-collector#1]

**Comment by nukeador** [comment]
Ideally no, we want peer-review, not self-review. We assume everyone would vote positive on their own strings.

**Comment by mikehenrty** [comment]
Except in the case where the submitter found the sentences, and submitted them to the collector. In this case, it feels like they should be able to review.

**Comment by nukeador** [comment]
Yes, but we should be then clear in #4 to avoid abuse.

**Comment by MichaelKohler** [comment]
Let's close this as it will be handled in #4.
