### ISSUE TITLE
Alert User when closing window while sentences are being uploaded

### ISSUE THREAD

**Issue by MichaelKohler** [Common-Voice/sentence-collector#102]
When uploading sentences it might take some amount of time depending on the amount of sentences to be uploaded. While sentences are being uploaded, we should show a warning to the user 'beforeunload' (with `preventDefault` this is done automatically by the browser). It's best to do this through Redux, as the component might get unmounted when the user goes to a different subsite of the website. The sentences upload would still happen in the background though.

**Comment by helenatxu** [comment]
Hello @MichaelKohler! I see this issue is still open, does it make sense to fix it now?

**Comment by MichaelKohler** [comment]
Yes, this still makes sense. Would be great if you want to work on this once the spinner is done :)

**Comment by helenatxu** [comment]
Right now I'm busy in other bugs for the projects I'm applying for the Outreachy internship, so I will unclaim that issue for now. But if nobody takes it after sometime, I will come back ;)

**Comment by singhvisha** [comment]
hi want to work on this bug

**Comment by singhvisha** [comment]
Hi @MichaelKohler , i want to work on this issue..

**Comment by MichaelKohler** [comment]
@singhvisha sure, go ahead! I'm happy to help if you should have any questions. You can find the instructions to set up the project at https://github.com/Common-Voice/sentence-collector/blob/master/README.md

**Comment by singhvisha** [comment]
hi @MichaelKohler , After installing all Prerequisites and cloning the voice-web repository locally,
when i run the frontend by running the command "yarn start",
it show this at last and nothing is happening --
E]     at processImmediate [as _immediateCallback] (timers.js:729:5)
[BE]      code: 'ECONNREFUSED',
[BE]      errno: 'ECONNREFUSED',
[BE]      syscall: 'connect',
[BE]      address: '127.0.0.1',
[BE]      port: 3306,
[BE]      fatal: true },
[BE]   isOperational: true,
[BE]   code: 'ECONNREFUSED',
[BE]   errno: 'ECONNREFUSED',
[BE]   syscall: 'connect',
[BE]   address: '127.0.0.1',
[BE]   port: 3306,
[BE]   fatal: true }
[BE] APPLICATION -- 2s to perform maintenance
[FE] Built!

**Comment by MichaelKohler** [comment]
@singhvisha The Sentence Collector is its own repository, it looks like you are in the wrong repository. This output comes from the voice-web repo, which you won't need to fix this here. Can you make sure that all the commands from the README are run in a checked out repository from https://github.com/Common-Voice/sentence-collector ?

**Comment by singhvisha** [comment]
hi, thanks for help.
I will soon submit my first patch

**Comment by shvmsrma** [comment]
Hello, @MichaelKohler  I would like to work on this issue.

**Comment by MichaelKohler** [comment]
@shvmsrma Currently @singhvisha is working on this issue. Would you be interested in tackling https://github.com/Common-Voice/sentence-collector/issues/123?

**Comment by shvmsrma** [comment]
Sure please assign me #123

**Comment by singhvisha** [comment]
hi @MichaelKohler, Is I have to add alert message when sentence are being uploaded?
Am i moving in the right direction?

**Comment by singhvisha** [comment]
hi @MichaelKohler , Is i have to add alert message when user tried to close the window while sentence are being uploaded ?
Am i moving in the right direction?

**Comment by alejandroclose** [comment]
@MichaelKohler Do you have any other "good first issue" for a junior dev? :)

**Comment by singhvisha** [comment]
No

**Comment by MichaelKohler** [comment]
> Is i have to add alert message when user tried to close the window while sentence are being uploaded ?
Am i moving in the right direction?

Yes, when sentences are being uploaded, we show a spinner. The same Redux mechanism can be used to register an `onunload` listener that prompts the user if they really want to quit while the sentences are being uploaded. Once the sentences are all uploaded, we should remove that listener again.

**Comment by MichaelKohler** [comment]
> Do you have any other "good first issue" for a junior dev? :)

@alejandroclose unfortuntely not right now. A lot of the pending issues either need a discussion first, or require a "real" backend so we can better handle things. If you're using the Sentence Collector and find a bug that could be easily fixed, I'm happy to accept PRs though.

Until we have more good first issues, would you be interested in contributing to the Dev Tools? You can find these repositories at https://github.com/firefox-devtools and all of them should have a "good first issue" label to make it easier for newcomers.

**Comment by MichaelKohler** [comment]
@singhvisha how is it coming along? Is there anything I can help you with? Happy to help! :)

**Comment by singhvisha** [comment]
Hi, sorry for any progress. my end-sem was going on.  Now I will do my best..

**Comment by sonyshubham** [comment]
@singhvisha are you still working on this?

**Comment by carpecodeum** [comment]
is this issue still being worked on?
