### ISSUE TITLE
Duplicated sentence detection

### ISSUE THREAD

**Issue by Txopi** [Common-Voice/sentence-collector#113]
If I try to add this new non existent sentences, the Submit phase finishes successfully and says that it will add 4 sentences:

1. Lehen esaldia
2. Bigarren esaldia
3. Bigarren esaldia
4. Hirugarren esaldia

But the 2nd and 3rd sentences are duplicated. The tool search for duplicates on already uploaded sentences, but not in the sentences you are trying to upload. It would be better if it detects the repeated sentences and discards them. Anyway, I don't think this is an important bug.

What is more weird from my point of view is what happens after confirm the submission. This is the output for the example above:

- `Submitted`
- `3 sentences.`
- `1 sentences failed`
- `Failed sentences:`
- `Bigarren esaldia: last modified precondition failed`

Reading this is it clear that "Bigarren esaldia" is duplicated? Not for me, although my English is quite bad... I think it would be better to discard the repeated sentences in the previous phase or at least showing a more clear error in this one.

**Comment by nukeador** [comment]
I can confirm this issue

**Comment by Txopi** [comment]
I tested this again in the [testing sentence collector](https://common-voice.github.io/sentence-collector) and I got the same output. Perhaps it's not running the fixed version.

**Comment by MichaelKohler** [comment]
Nope, not deployed yet. The bot will add a comment here once it's deployed.
