### ISSUE TITLE
Sentence Length is too short for Punjabi (India) Language!

### ISSUE THREAD

**Issue by profsatwinder** [Common-Voice/sentence-collector#115]
I tried adding lots of Punjabi Sentences but the system rejects the sentences just because the sentence length is a little bit big. It might be because Punjabi language's Gurmukhi script is using various symbols.

for eg. 
**ਸਾਡੇ ਕੋਲ ਠਹਿਰਿਆ ਰਾਤੀਂ ਅਸੀਂ ਬੈਠੇ ਪਿਆਲੋ ਪਿਆਲੀ ਹੁੰਦੇ ਪੁਰਾਣੀਆਂ ਯਾਦਾਂ ਤਾਜ਼ਾ ਕਰ ਰਹੇ ਸੀ ਕਿ ਬਾਪੂ ਜੀ ਨੀਂਦ ਵਿੱਚ ਤੁਰਦੇ ਸਾਡੇ ਕੋਲ ਆਣ ਖੜੇ ਹੋਏ**

The above sentence has **26 words** and **101 characters excluding white spaces.** 

could you please increase the char length for the Punjabi language so that I can add some meaningful big sentence.

**Comment by nukeador** [comment]
How long does it take to read that sentence?

The current limit is 14 words so reading time just takes 5s.

**Comment by MichaelKohler** [comment]
@profsatwinder could you please answer nukeador's question so we could adjust it if needed?

**Comment by MichaelKohler** [comment]
Thanks for the response. I'll let @nukeador decide here.

**Comment by nukeador** [comment]
@profsatwinder Can I suggest you open a topic over Common Voice discourse so other Punjabi speakers can engage to take a decision on how many words are needed for a 5 seconds sentences?

https://discourse.mozilla.org/tags/c/voice/sentence-collection

**Comment by MichaelKohler** [comment]
We have started a topic to discuss sentence length. It would be great if you could add your examples in that discussion :)

https://discourse.mozilla.org/t/proposal-sentences-lenght-limit-from-14-words-to-100-characters/35599
