### ISSUE TITLE
Really ensure people understand and agree content submitted is public domain

### ISSUE THREAD

**Issue by nukeador** [Common-Voice/sentence-collector#117]
I got this from the Common Voice team meeting.

There are two important things we need:

- Ensure people see and understand wikipedia content is not OK (This is a common issue even if people are told so)
- Make sure people have to take an action agreeing content submitted is public domain (this can maybe be a checkbox with a text on the first screen on "Add", next to the source one

Looping @mbransn here also for additional feedback

**Comment by nukeador** [comment]
@JRMeyer We might want to also consider in the future if there is an automated way to check corpus license (I remember someone mentioned a service in the past)

**Comment by MichaelKohler** [comment]
> Make sure people have to take an action agreeing content submitted is public domain (this can maybe be a checkbox with a text on the first screen on "Add", next to the source one

Should we just move the existing sentence to the first screen or just add a checkbox on the confirm screen where currently the sentence is?

**Comment by nukeador** [comment]
I think we want to move the notice to the first screen and have a checkbox so people have to read it.

Let's wait for @mbransn feedback here.

**Comment by mbransn** [comment]
Thanks for logging this @nukeador :)

Agreed that a checkbox is a good way to do this and yes, it should be on the first screen. My thinking is to keep this checkbox inline with the flow (note copy changes): 
- Add Sentences
- Where are these sentences from?
- [ ] I confirm that these sentences are [public domain](https://en.wikipedia.org/wiki/Public_domain) and I have permission to upload them.
- `Submit`

For `Add Sentences` we should add prompt copy within the field to nudge people toward public domain and one sentence per line: 
> Add your [public domain](https://en.wikipedia.org/wiki/Public_domain) sentences here **one per line**

For 'Where are these sentences from?' can we also add prompt copy that helps provide ideas of where they could obtain sentences? Not everyone will go to the "How to" first:
> e.g. myself, podcasts, movie transcripts, books, etc. Read our [How-to](https://common-voice.github.io/sentence-collector/#/how-to) for more ideas.

Note: for future iterations we are working on designs that would include criteria and prompts like these incorporated into the 'Add' and 'Review' pages.

**Comment by MichaelKohler** [comment]
Sounds good to me. However, I'm not sure if it would be clear enough that e.g. books need to be public as well, so maybe that should be iterated again that it needs to be public domain. What do you think?

**Comment by mbransn** [comment]
Thanks @MichaelKohler -- as public domain encompasses all of the examples given, perhaps we map that into the question instead?

Where are these [public domain](https://en.wikipedia.org/wiki/Public_domain) sentences from?

**Comment by MichaelKohler** [comment]
So this would make it the following, correct? (just imagine it without the header lines GitHub does for markdown, did I just find a new way of prototyping? :)

# Add Sentences
[LANGUAGE CHOICE]
## Add your [public domain](https://en.wikipedia.org/wiki/Public_domain) sentences here one per line
[Textarea]
## Where are these sentences from?
e.g. myself, podcasts, movie transcripts, books, etc. Read our [How-to](https://common-voice.github.io/sentence-collector/#/how-to) for more ideas.

[Textfield]
- [ ] I confirm that these sentences are [public domain](https://en.wikipedia.org/wiki/Public_domain) and I have permission to upload them.

[Submit]

**Comment by mbransn** [comment]
@MichaelKohler Your iteration made me go back and assess the intro copy as well, there's a bit of redundancy on the page. Less words in the right places should help a bit, take a look below and let me know thoughts.

## Select Language
[Language Dropdown]

## Add [public domain](https://en.wikipedia.org/wiki/Public_domain) sentences
[Text area w/placeholder: One sentence per line]
## Where are these [public domain](https://en.wikipedia.org/wiki/Public_domain) sentences from?
[Text area w/placeholder: Read our [How-to](https://common-voice.github.io/sentence-collector/#/how-to) if unsure how to attribute]

- [ ] I confirm that these sentences are [public domain](https://en.wikipedia.org/wiki/Public_domain) and I have permission to upload them.

[Submit]

---

I also made an attempt locally, but quick coding inline links and checkboxes aren't my skill level so it's not quite complete. :)

![screen shot 2019-01-17 at 3 10 43 pm](https://user-images.githubusercontent.com/18686986/51355010-7ac38400-1a6a-11e9-90a8-90471f8e3489.png)

**Comment by MichaelKohler** [comment]
Looks good to me. The only difference I see is "public domain" (in your text) vs. "Public Domain" (in your screenshot). I suppose we want to go with "public domain"?

**Comment by nukeador** [comment]
This looks great :-)
