### ISSUE TITLE
Ability to see and remove my own sentences

### ISSUE THREAD

**Issue by nukeador** [common-voice/sentence-collector#118]
We need a way for a given user to see all sentences they have sent and provide with the ability to remove them, and maybe the same for an admin user.

Context: What happens if a user realizes some of his/her sentences were not public domain?

**Comment by MichaelKohler** [comment]
In terms of Kinto permissions, this should be doable if I read the documentation right:

> Every modification of an object (including the creation of new objects) grant the write permission to their creator/editor.

I would need some help in terms of UX though, as there possibly should be search as well?

**Comment by nukeador** [comment]
Let's keep this idea parked until we decide priority, no need to think yet about UX here.

**Comment by nukeador** [comment]
How complex a minimum viable version of this would be to implement?

MVP
- List all my sentences.
- Button to remove individual ones.
- Button to remove all from one submission?

Additional features from community feedback
- See my sentences that have been rejected
- Search
- Download all my sentences (and metadata)

**Comment by MichaelKohler** [comment]
For now let's go with the following:

* Additional section in the menu "My sentences"
* Sentences that got submitted by the current user are listed there (similar to the upcoming 'Rejected Sentences')
* Each sentence has a remove button next to it
* Clicking the button removes the sentences from the database

**Comment by MichaelKohler** [comment]
PR for 'Rejected Sentences' as inspiration on how to tackle this: https://github.com/Common-Voice/sentence-collector/pull/219/files. This will show how to change the navigation, and how to add new pages. Of course the content and file names would need to be different for this PR ;)
