### ISSUE TITLE
Ensure locale list is in sync with voice-web

### ISSUE THREAD

**Issue by nukeador** [Common-Voice/sentence-collector#121]
Let's make sure we are using the same locale list being used by voice-web

https://github.com/mozilla/voice-web/tree/master/locales

**Comment by MichaelKohler** [comment]
Should we really only gather sentences for locales that are enabled in Common Voice?

**Comment by MichaelKohler** [comment]
in any case, we definitely should use the same codes though

**Comment by MichaelKohler** [comment]
This also possibly blocks the export, as we wouldn't have the same locale codes..

**Comment by Gregoor** [comment]
Is a JSON file an API? 🙃 
https://github.com/mozilla/voice-web/blob/master/locales/contributable.json

That list should be fairly stable!

**Comment by MichaelKohler** [comment]
hah, sure, fair enough. I'd argue though that we should take the "all" list and not only the contributable.

https://raw.githubusercontent.com/mozilla/voice-web/master/locales/all.json

**Comment by nukeador** [comment]
> This also possibly blocks the export, as we wouldn't have the same locale codes..

What do we mean by this? Is it currently blocking, might block it in the future...?

**Comment by MichaelKohler** [comment]
Well, if we have non-matching locales (for example the 3-letter ones), we can't really export it to the correct folder. So currently blocking, yes.

**Comment by nukeador** [comment]
OK, then let's make sure we are using the right list :-)

**Comment by MichaelKohler** [comment]
Ok, to summarize:

1) We need to have the same locale codes as voice-web does
2) We only want "soon to be" languages on voice-web (anything that is in translation on Pontoon basically)
3) We can use the list directly from the repo to populate our dropdowns
4) CV/Pontoon does not use one standard for locale codes (ISO 639-1/3 and zh-TW format)
5) Kinto collections can't be created on the fly as we do not have a backend
6) We do not want to pre-create all possible collections with all of these formats
7) Brings us to the interesting problem: how can we create these collections without unnecessary manual interaction?
8) We can only export if we have the correct locales, we can only collect sentences if we have the correct locales to avoid migrations

Now, @Gregoor, I would love to hear your thoughts on this. I've been thinking about this and figured we definitely need some dynamic way. Are you currently getting the languages manually or automatically from Pontoon? I had an idea that, if automatic, we could also just do a collection in Kinto at the same time. Is that too weirdly crossing app boundaries?

**Comment by nukeador** [comment]
I think we need all to follow the same "all locales list", because I don't want to block a locale to start submitting sentences even if they haven't started the site localization.

**Comment by MichaelKohler** [comment]
ah, then this changes things, probably best if we sync with @Gregoor then, as this will then also have an effect on CV itself, I'd say.

**Comment by Gregoor** [comment]
Atm we're manually running a script (about once per week, or when pinged by community) that fetches all the locales from pontoon and updates the locale json files.

I guess the problem with creating it eagerly on the sentence-collector side, is that the locale codes might then not match with the ones the Pontoon team chooses?

**Comment by MichaelKohler** [comment]
> I guess the problem with creating it eagerly on the sentence-collector side, is that the locale codes might then not match with the ones the Pontoon team chooses?

Correct. We currently have everything in the ISO 639-1 format, plus (soon) zh-TW, zh-CN, zh-HK (as those do not have separate 639-1 definitions.

**Comment by nukeador** [comment]
Why not using the same ISO format as pontoon is using? That would avoid any mismatches in the future, right?

**Comment by MichaelKohler** [comment]
well, from what I can see from the list at https://raw.githubusercontent.com/mozilla/voice-web/master/locales/all.json is that there is no single standard being used. It's  a mix of ISO 639-1 and 639-3 as well as whatever zh-TW is.

**Comment by MichaelKohler** [comment]
.. but yeah, maybe they have a list we could use. thanks @Gregoor

**Comment by Gregoor** [comment]
Haven't heard back from that yet, but I realized that we can also get that list through the API:
```
curl -X POST \
  https://pontoon.mozilla.org/graphql \
  -H 'Content-Type: application/json' \
  -d '{
	"query": "{  locales { code, name } }"
}'
```

**Comment by MichaelKohler** [comment]
.. which works for currently existing languages, but not for future ones. So we would still need to have a way to create stuff on-the-fly.

**Comment by Gregoor** [comment]
Right, it only works for languages that exist in Pontoon (which is a superset of what exists in CV). For languages that aren't on Pontoon yet, we might be able to determine which code should be used (I'll get feedback from the Pontoon folk on that).

**Comment by Gregoor** [comment]
Just got some word back:

> we try to use two-letter codes where possible, and use three-letter where necessary 
> also a good idea to look into cldr, for which locale code there's data

**Comment by MichaelKohler** [comment]
We are going for the two-letter format for now, and handle anything else when it comes up
