### ISSUE TITLE
"0 sentenses reviewed. Thank you"

### ISSUE THREAD

**Issue by gtimoshaz** [Common-Voice/sentence-collector#128]
If you click the button "finish review" without actually reviewing sentences, you get this message. I think it should be something like "you did not reviewed any sentences" or even better the button should be inactive.
![image](https://user-images.githubusercontent.com/11595498/51504756-bad09100-1df3-11e9-9b6d-8612fc1d1e25.png)
The same thing happens when you review only one sentence: you get "1 sentence**s** reviewed" instead of "1 sentence reviewed"
![image](https://user-images.githubusercontent.com/11595498/51504824-fec39600-1df3-11e9-8a7c-e053c6399586.png)

**Comment by MichaelKohler** [comment]
Thanks for filing this, once we have localization with Fluent, we can easily change the case depending on the amount. Until then, it would be quite an ugly hack, so I'll leave it for now. Localization can be tracked in #3
