### ISSUE TITLE
Sentence validator doesn't report which sentences fail the validation

### ISSUE THREAD

**Issue by ftyers** [Common-Voice/sentence-collector#129]
If there are only 1-5 sentences out of 1000s that fail the validation, it would be good for the tool to show which ones they were.

![captura de 2019-01-22 14-24-52](https://user-images.githubusercontent.com/449545/51541881-d9657500-1e51-11e9-8c43-cff309d76a10.png)

At the moment you just get "one sentence failed" but you have no idea which one it was.

**Comment by MichaelKohler** [comment]
So there is nothing below the "Please check this guidelines"? Can you link me to your sentences so I can test this with the same ones?

**Comment by ftyers** [comment]
@MichaelKohler https://github.com/ftyers/voice-web/blob/00a92e2ed535fda15d7cbec3f2fead76d3050652/server/data/cv/haval_sents.txt

**Comment by MichaelKohler** [comment]
Hah, interesting. When copy/pasting there might be a new line character at the end, therefore creating a new line in the input field. And we don't filter this out and then decide in the validation that an empty line is not a valid sentence. And then we show the empty line in the list (which is not visible to the eye of course). Yep, we should filter out empty lines from the beginning..

Thanks for filing this!

**Comment by ftyers** [comment]
@MichaelKohler no problem, thanks for fixing it!
