### ISSUE TITLE
Ability to mass review sentences

### ISSUE THREAD

**Issue by ftyers** [common-voice/sentence-collector#130]
We checked and reviewed a lot of sentences and sent a [PR](https://github.com/mozilla/voice-web/pull/1720) to Common Voice. It was closed and now we uploaded our sentences to the sentence-collector. But it seems that the only way they can be included is to go through them all and click the thumbs up icon. We already checked the sentences, so this means we will have to check them again. Would it be possible to have some kind of "mass review" button for sentences that have already been checked once? Otherwise we're doubling the work for an already small and busy community.

**Comment by nukeador** [comment]
Please, note that we haven't launched the beta yet, so the database will be cleaned-up when we move to beta, which is expected in the coming days.

I understand this inconvenience if you have run a review process out of the tool, at the same time we want to ensure people can't mass positive review sentences, that will invalidate the whole review purpose.

Having sentences deeply reviewed is important to ensure they are useful for the Deep Speech algorithms, we don't want to lower the bar and having the risk of accepting sentences that will turn useless (wasting more people's time)

**Comment by ftyers** [comment]
What do you mean "cleaned-up" ? You mean stuff that we have submitted and reviewed will be thrown away? Is it worthwhile me going through and reviewing all of the sentences now, or should I wait until the release?

**Comment by ftyers** [comment]
@nukeador I know how it works :) This is not the first set of sentences I have collected, nor the first time I have used DeepSpeech.
