### ISSUE TITLE
Add a single-sentence per window keyboard mode

### ISSUE THREAD

**Issue by ftyers** [Common-Voice/sentence-collector#131]
Instead of having to click on all of those thumbs, it would be great to have a fast keyboard-only mode, where you could see a single sentence and click "y" or "n" and left/right to go through them.

**Comment by MichaelKohler** [comment]
see also #55

**Comment by MichaelKohler** [comment]
Closing this in favor of https://github.com/Common-Voice/sentence-collector/issues/55 so we can keep track of the whole review improvements in one issue for now.
