### ISSUE TITLE
Create missing CV languages?

### ISSUE THREAD

**Issue by MichaelKohler** [Common-Voice/sentence-collector#132]
@nukeador  The following languages from https://raw.githubusercontent.com/mozilla/voice-web/master/locales/all.json do not have a Kinto table yet, should we create those?

```
[
  "ace",
  "ady",
  "ast",
  "bxr",
  "cak",
  "cnh",
  "dsb",
  "fy-NL",
  "ga-IE",
  "hsb",
  "kab",
  "kpv",
  "mdf",
  "mhr",
  "mrj",
  "myv",
  "nb-NO",
  "ne-NP",
  "nn-NO",
  "pt-BR",
  "rm-sursilv",
  "sv-SE",
  "uby",
  "udm",
  "vot"
]
```

**Comment by nukeador** [comment]
Yes, we should be in sync. Do we we have the locale names too?

**Comment by MichaelKohler** [comment]
Yes, will add them tonight so we can run the "prod" commands all at the same time
