### ISSUE TITLE
Specify preference for sentence type in How-To

### ISSUE THREAD

**Issue by Gregoor** [Common-Voice/sentence-collector#139]
Specify that we have a preference for natural/conversational sentences. Maybe reference the german dataset where we had fun sentences written by a community member, which made using Common Voice itself more fun.

_Based on feedback from Alex_

**Comment by nukeador** [comment]
+1

**Comment by MichaelKohler** [comment]
@nukeador do you want to take this on?

**Comment by nukeador** [comment]
Yes, I can try to write something this week.
