### ISSUE TITLE
Statistics for all languages

### ISSUE THREAD

**Issue by MichaelKohler** [common-voice/sentence-collector#149]
Currently we can only see statistics for languages that are added to the profile, and the total count. We should add a page where all languages are listed.

**Comment by nukeador** [comment]
Is there a way aggregated stats don't have to be generated each request? (I'm assuming they are right now)

Maybe there is a way to store them in a kinto table with a timestamp and when stats are requested they are only generated each hour/day whatever and not for each request.

**Comment by MichaelKohler** [comment]
Not as long as we don't have a backend (though we could make it easy and just run a single script on the kinto server that runs scheduled by a cronjob)

**Comment by isemaj** [comment]
Hi, can I join?

**Comment by MichaelKohler** [comment]
Statistics are now available in three places:

* Statistics page listing all added languages
* Profile listing added sentence per added language
* API endpoint to query specifically for a certain language
