### ISSUE TITLE
Review pagination position

### ISSUE THREAD

**Issue by nukeador** [Common-Voice/sentence-collector#150]
When reviewing sentences I usually start at the top of the 3 and then go down.

It's a bit inconvenient not having the pagination after the last bottom one and having to go up again for going to the next page (breaks the flow for me)

I suggest we move pagination at the bottom or we include pagination both top and bottom (which is probably too noisy)

**Comment by MichaelNMaggs** [comment]
Yes, agreed

**Comment by MichaelKohler** [comment]
See also #55 .

**Comment by MichaelKohler** [comment]
Will probably depend on whatever we come up with in #174

**Comment by MichaelNMaggs** [comment]
Hi @MichaelKohler Both this and #174 seemed ready to go, but their statuses have now been set back to Needs Discussion.  Do you know what's being awaited please?  Even a simple upgrade from 3 per page to 5 would really help.

**Comment by MichaelKohler** [comment]
Agreed, let's move forward here and move the position to the bottom. As indicated at https://discourse.mozilla.org/t/common-voice-sentence-collection-tool-launch/35427/18?u=mkohler it would be great if you could create a new topic regarding UX :)
