### ISSUE TITLE
Finish Review fails if too many sentences done

### ISSUE THREAD

**Issue by MichaelNMaggs** [Common-Voice/sentence-collector#152]
The 'Finish Review' button stops working if you review too many sentences at once (over around 100).  There's no way to save, and all the work done is lost

**Comment by nukeador** [comment]
Does stop working or takes too long to finish?

**Comment by nukeador** [comment]
I just did 34 pages, I clicked Finish and after a few seconds I got that only 50 sentences were reviewed.

Console error (displayed dozens of times)

```
vote error 412 
Object { code: 412, errno: 114, error: "Precondition Failed", message: "Resource was modified meanwhile", details: {…} }
sentences-meta.js:266:8
    t sentences-meta.js:266
    t sentences-meta.js:262
    L runtime.js:62
    _invoke runtime.js:288
    r runtime.js:114
    n asyncToGenerator.js:3
    c asyncToGenerator.js:25
```

**Comment by MichaelKohler** [comment]
@nukeador I can't really say why you hit this specific error. We already refresh the data before editing it. Will need to dig deeper on that one at some point.

@MichaelNMaggs thanks for this issue, I could reproduce this.

**Comment by MichaelNMaggs** [comment]
Thanks. What I see is no response to the 'Finish Review' button if more than about 100 sentences are reviewed (I was able to get it to accept 92, but not over 100).  It's not just a slow response, as nothing happens even after 5 minutes. No error message.
