### ISSUE TITLE
Simple log page

### ISSUE THREAD

**Issue by nukeador** [Common-Voice/sentence-collector#154]
Now people are uploading a lot of sentences, I think it would be important to have a simple log page (even if it's for internal use) to be able to see what's going on.

User X added X sentences in LOCALE - Source X
User X reviewed X sentences in LOCALE

Or something like that, also to be able to identify abuse.

**Comment by MichaelKohler** [comment]
I think this will need an evaluation how we could do this. To my knowledge Kinto doesn't have an easily accessible log for this purpose, and parsing the normal logs might be too much work here. We will need to see.
