### ISSUE TITLE
A way to avoid a lot of weird sentences when reviewing

### ISSUE THREAD

**Issue by nukeador** [Common-Voice/sentence-collector#155]
I've found thousands of sentences in Spanish from an old book, most of them have super old and weird language, I would like to skip them all and remove them from my review list, since they are first in the queue and noise in my workflow.

We should probably have a way to vote negative to all sentences from a given upload (or user, but I don't know if this user has uploaded other valid sets).

Cheers.

**Comment by MichaelKohler** [comment]
I'd say even in a single upload there might be good sentences though...

**Comment by nukeador** [comment]
In my mind I see something like this, to offer after selecting reject the option to reject them all

![imagen](https://user-images.githubusercontent.com/531906/52013489-7c1a9500-24dd-11e9-9db6-8d794eb1d444.png)

Or maybe when the site detect you have selected reject for 3 sentences from the same submission.

**Comment by mozillakab** [comment]
If we can also load the old corpus, it's important to get a feature to tag/comment wrong sentences and edit them.

**Comment by MichaelKohler** [comment]
Once the infrastructure improvement is done, we will have the info needed for this. I think we should still discuss on how exactly this should work though.

**Comment by MichaelKohler** [comment]
I have moved this to https://discourse.mozilla.org/t/sentence-collector-open-discussions-input-needed/63925 for further discussion.
