### ISSUE TITLE
Can't sign up for Sentence Collector

### ISSUE THREAD

**Issue by Rubaaw** [Common-Voice/sentence-collector#156]
I tried to create an account using different usernames (alphanumeric, no email), but unfortunately it always gave me **“Login failed.”**
I tried more than different 10 usernames (capital, small and mixed) with different passwords and the result is the same “Login failed.”

 So what should I do to resolve this ?

**Comment by nukeador** [comment]
I have just created an account with no problem. Which usernames have you tried and can you see any console logs if you open your browser developer tools?

**Comment by Rubaaw** [comment]
after trying many usernames , finally it worked
im wondering what was the reason !
Thanks 👍
