### ISSUE TITLE
Improve Review Loading with more than 10k records

### ISSUE THREAD

**Issue by MichaelKohler** [Common-Voice/sentence-collector#160]
Kinto has a hard-limit of 10k results. We need to check our code and decide what to do. Here are the things that just come to my mind right now:

* Export needs to export all - no limit
* The stats page on the home page only shows numbers, maybe we can improve the queries and make Kinto return the full numbers
* The review only loads 10k, which IMHO is a good thing to save bandwidth (we should probably make that even smaller), but breaks our client side sorting to show the sentences with > 0 "approval" reviews first

**Comment by MichaelKohler** [comment]
The first point will be fixed in https://github.com/Common-Voice/sentence-collector/pull/171.

The second point I don't deem important right now, as 14000 would not provide a lot more value than 10000, it's mostly about showing the user that there are unreviewed sentences.

The third point I have no idea how we could fix that.

I'm renaming the issue and setting the discussion-needed flag for point 2 and 3.

**Comment by dabinat** [comment]
#2 could be improved by showing rounded or less accurate numbers. For example, on the Common Voice homepage it just says 1.0k rather than listing every single hour of recording. So it could just say 10.0k+. The problem for me was more that it was implied on the homepage that 10,000 was a definitive amount.

It would also mean the stats would change less often, so there be no need to continue to generate them on every page load, which I know is another issue being discussed.

**Comment by stefangrotz** [comment]
Hey I like the idea of. 10k + as a quick fix. I found the static number very confusing and with this there is at least an indicator that there are more sentences.

**Comment by bact** [comment]
The review page takes too long time to load each time.

I tend to review < 100 sentences then hitting Finished Review, just to make sure that I will not lost my work if there's problem with internet connection.
But this means I have to wait for the reload again and again.

My suggestion is to limit the sentences to be loaded in each review, maybe 200 or 500 sentences max.

**Comment by MichaelKohler** [comment]
This is now fixed in the latest version which just got deployed: https://discourse.mozilla.org/t/action-required-new-sentence-collector-infrastructure-and-improvements/68759
