### ISSUE TITLE
Save the contents of the Add field as a draft until submitted

### ISSUE THREAD

**Issue by dabinat** [Common-Voice/sentence-collector#162]
I typed a bunch of sentences into the text box then submitted it. It told me that some sentences failed validation (too many words).

The options were to click Submit to submit only the ones that passed or Cancel. I clicked Cancel so I could edit the failing ones and resubmit, but it just returned me to a blank text box, losing everything I had typed.

It should therefore save the contents of the text box in a cookie or local storage until submitted and confirmed.

**Comment by MichaelKohler** [comment]
I like that idea, putting this into our backlog
