### ISSUE TITLE
Users shouldn’t be able to validate their own sentences

### ISSUE THREAD

**Issue by dabinat** [Common-Voice/sentence-collector#163]
It seems strange to me that users can validate sentences they submit. Assuming no inadvertent mistakes, all users will presumably vote yes on their own sentences.

A sentence could be unsuitable yet still pass automated validation, and the submitting user could either be malicious or simply not know that the sentence is unsuitable.

It means that sentences may essentially be validated only by a single objective reviewer. That puts a lot of pressure on one person. There’s a discussion on the voice-web PR page about sentences passing validation when they shouldn’t have, and this may have been a contributing factor.

However, there is certainly an argument to be made that submitters may want to reject sentences they submit, so perhaps there should be some way of voting negatively or deleting your own submissions. I don’t see a reason why a user should be able to vote positively on their own submissions though.

**Comment by nukeador** [comment]
Note that users can't validate their own sentences, they can just review them.

Why we took this decision?

Because there is a lot of people who is add sentences that are not their own but external source. We want people to have the chance to be part also of the review.

Having a positive review from the submitter doesn't validate the sentence. Currently a sentence needs at least 3 votes, 2 of them should be positive.

**Comment by dabinat** [comment]
Ok, I’m glad to hear that, but if reviewing positively doesn’t actually do anything useful, why have the button there at all? It feels like one of those elevators where the “close door” button isn’t even wired up but the user feels useful by pressing it.

I feel your own submissions should be shown in another place, not the main queue, and you should have the option there to reject or delete them. I make a point of checking everything thoroughly *before* I submit, so it’s annoying to have to go through and validate it again just to get it to disappear from the queue.

So maybe there’s a review option before you submit, and if you choose not to use it, it just assumes all are approved by you? Or maybe this could be a user preference?

**Comment by nukeador** [comment]
One example of this I experienced the other day. I got 1000 sentences for Spanish from another source, but I didn't write them myself, so is the case for other people. In that situation I would like to be able to review this set.

If submitter don't want to review his own submission that should be fine. What's the issue you see in not voting your sentences and letting others proofread them? You will always need others to review your sentences.

**Comment by dabinat** [comment]
You can already prevent bad sentences from getting through - there’s an optional review step before you submit. It seems more logical to input the text, have a review step (optional?) and then submit. Otherwise you’re submitting potentially junk sentences to everyone and then removing them after the fact.

But to go back to my original point, I don’t feel like every sentence should *require* a yes vote by the submitter. They should be able to vote no *if necessary* but there is no need to *require* a yes that ultimately does nothing IMO.

This could be solved by forcing the review step before submitting. Remove the thumbs up button so there’s only thumbs down. The user can then scroll through, thumbs down any bad sentences and then submit. A much quicker workflow that gets rid of bad sentences before they are submitted to the site, not after.

**Comment by jf99** [comment]
I support @dabinat 's standpoint here. Currently, I often find myself in the cumbersome situation that the first 100 review pages are full of my own sentences. I see no point in reviewing them again. To get to the first contribution of another user, I have to do 100 mouse clicks. Then I review 3 sentences, click "finish review" and find myself on page 1 again.

So please separate reviewing one's own sentences from reviewing other's contributions.

**Comment by nukeador** [comment]
@dabinat @jf99 How do you think we should count votes in that situation? 0 votes? Always 1 vote by default? We really want to have at least 3 people checking each sentence and 2 positive votes.

How do we optimize your proposal for people sending large corpus not their own? Some of these people don't want to review, just contribute the corpus for community to review.

**Comment by dabinat** [comment]
I think a positive vote by the submitter is implied by default. As long as the submitter has the ability to downvote or remove sentences then their failure to do so implies approval of the sentence.

I think the solution here is to not put the sentences in the submitter’s review queue, but instead have the review step before submitting. The user is not forced to approve each one but can remove bad ones.

You can already review before you submit but IMO the option is maybe not that noticeable within the UI. I think there should no longer be a link to review the submissions but the user should just be taken to that page automatically before they submit.

And yes, some users may just paste a lot of junk in the box, but if they’re not conscientious about checking it before they paste, they probably won’t be conscientious about it afterwards either.

**Comment by jf99** [comment]
Giving 1 positive vote by default doesn't make sense, imo. It is equivalent to decreasing the required number of votes from 3 to 2, so why not doing that? Thinking about how to count votes, @nukeador wrote above:

> Currently a sentence needs at least 3 votes, 2 of them should be positive.

So, when a sentence only has two votes, both positive, a third vote is still required? Because it wouldn't have any effect.

Apart from that, the "I didn't write it myself" argument has a point and is a good reason to let contributors review their own sentences. For me, it's not so important how many votes you need for a sentence to pass the review. The separation of own and foreign sentences is more important.

**Comment by MichaelKohler** [comment]
I'm closing this as I understand we're on the same page. If this is not correct, let's open a discussion on Discourse.
