### ISSUE TITLE
Can't sign in to Sentence Collector 

### ISSUE THREAD

**Issue by Rubaaw** [Common-Voice/sentence-collector#166]
Hello there

I had a previous issue here #156  , after many attempts it worked out and I signed up as **rubaaw**
it was working fine at home, today i tried another PC, and again Login failed appeared ! 

I'm totally sure that I typed the password and username correctly
Can someone help me in this issue :) 

![untitled](https://user-images.githubusercontent.com/33860561/52266259-9c63ad00-293e-11e9-8fe3-fd96c57881c6.png)

**Comment by MichaelKohler** [comment]
I'm not aware of any problems with the login in general. Is there any chance you have miss-typed your password when creating the account and now remember the password you had in mind, but that's not the same as the database has?

**Comment by Rubaaw** [comment]
Hello Michael
No im totally sure that it is the same.
Actually after approximately one hour it logged in with the same password!
It is not the first time that happened to me, I don't know the exact problem, but it is working well till now
Im afraid to log out or try a new Pc 😢

**Comment by nukeador** [comment]
Did this problem happen again?

**Comment by Rubaaw** [comment]
Noo, all is good 👍
