### ISSUE TITLE
Warn about possible errors

### ISSUE THREAD

**Issue by dabinat** [Common-Voice/sentence-collector#168]
It would be useful for the system to have the ability to flag up sentences with *possible* errors, bringing the submitter’s attention to them, but still allowing the submitter to override and submit them anyway if no errors actually occurred.

Some examples of things that could be flagged up this way:

* Words not in the dictionary
* Repeated words
* Extraneous punctuation (trailing commas, apostrophes by themselves, etc)

Flagging these up and having the submitter address them would fix the majority of the sentences I have downvoted so far.

**Comment by dabinat** [comment]
I thought of another use-case for this: someone submitted about a hundred French sentences to the English section that I had to downvote one-by-one. It would be good to have some kind of rudimentary language checking that checks for certain keywords and says “Are you sure you want to submit this to English?” if it appears to be another language.

**Comment by MichaelKohler** [comment]
Thanks for filing this issue. I've moved the discussion to https://discourse.mozilla.org/t/sentence-collector-open-discussions-input-needed/63925. Let's file a new issue with more detail once we have feedback there and know how to proceed here.
