### ISSUE TITLE
ambiguity on some FRENCH sentences

### ISSUE THREAD

**Issue by nicolaspanel** [Common-Voice/sentence-collector#169]
I recently took some time to review french sentences from clips.tsv and I noticed the ambiguities below:

 - some acronyms are  pronounced as words and other are spelled letter by letter. For a reader that do not know the acronym it can be hard to decide which "mode" to use. Examples:
   - PHP => P H P
   - SNCF = > S N C F
   - CICE => C I C E
   - MODEM => MODEM
   - PAC => PAC
   - INSEE => INSEE
   - etc

 - some sentences contain special chars. Examples
   -  `{{personnage|JEN NY.|c}}`
   - `M^{me}`

 - some sentences contain abbreviations that may be prononces in different ways:
   - «Loretto contenait un trésor à peu près de `trois,000 liv.`»  which is probably «Loretto contenait un trésor à peu près de `trois mille livres`» 
   - «et dix.000 fr.»  which is probably «et 10 mille francs»
   - `2º` could be:
     - deuxième
     - deuxièmement
     - deuzio
   - «articles L.310-2» could be:
     - «articles L 310 2»
     - «articles L `point` 310 `tiret` 2
   - «c’est déjà quatre cents 000 de plus» could be:
     - «c’est déjà quatre cents `mille` de plus»
     - «c’est déjà quatre cents `zéro zéro zéro` de plus»
     - «c’est déjà quatre cents `zéro` de plus»
     - «c’est déjà quatre cents `trois zéro` de plus»
   - «M.» could be:
     - the letter `M` => «M»
     - «Monsieur» 
   - etc. 
 - etc.

@Gregoor : Are you aware of this ? do you already have a  way to detect and fix (or exclude) them ?

IMHO: this ambiguity should have been detected and fixed during the "sentence collection process". This is why I submit the issue here

@lissyx as discussed

**Comment by nukeador** [comment]
Hi,

Thanks for reporting, the current dataset was not created by this tool, we are already enforcing rules to avoid this happens to sentences coming from this tool.

I suggest you comment this in the dataset release topic. Note we plan to run a clean-up to all existing sentences collected before having this tool

https://discourse.mozilla.org/t/multi-language-dataset-beta-release/34373

Cheers

**Comment by nicolaspanel** [comment]
> Note we plan to run a clean-up to all existing sentences collected before having this tool

:+1:
