### ISSUE TITLE
Submitting from multiple tabs not possible due to shared state

### ISSUE THREAD

**Issue by lissyx** [Common-Voice/sentence-collector#173]
STR:
 - Open two "Add" links in two tabs
 - Paste content in each, with some too long sentences
 - UI asks confirmation

Expected:
 - When I confirm on one tab, it does not confirm on the other tab

Actual:
 - When I clicked on "Confirm" in one tab, the "Confirm" button on the other tab went gray.

**Comment by MichaelKohler** [comment]
Yep, persistent state, maybe not that good after all. I can't say why it was added though, will try to find out.

Thanks for filling.
