### ISSUE TITLE
Uploaded sentences not available for review

### ISSUE THREAD

**Issue by MichaelNMaggs** [Common-Voice/sentence-collector#182]
My last few collections of uploaded English sentences have disappeared and do not appear among those available for review (to me at least – I don't know whether others can see them).    I hope they  have been properly accepted, and will become available for review some point.

I don't know if this is relevant, but this seems to have happened at the same time that the stated number of unreviewed English sentences on the homepage became stuck at exactly 10,000.

**Comment by MichaelKohler** [comment]
Good observation, we cap the number of sentences for review display at 10k for now. It doesn't make sense to load all. See #160
