### ISSUE TITLE
Home page stats == too slow

### ISSUE THREAD

**Issue by JRMeyer** [Common-Voice/sentence-collector#183]
@nukeador - maybe we can calculate the number of sentences collected once a day and cache that number instead of counting in real-time? 

This message on the home page takes too long to load.

First you see this: 

```Loading sentence collector data...```

Then later, this: 

```The Common Voice Sentence Collector has collected 279499 sentences in 29 languages!```

**Comment by MichaelKohler** [comment]
Thanks, see also https://github.com/Common-Voice/sentence-collector/issues/149

**Comment by iveskins** [comment]
The rejected page seems slow also.
I just made a new account with nothing submitted and it is stuck on . Loading rejected sentences..

**Comment by MichaelKohler** [comment]
I'll close this as it's gonna (eventually) be tackled by #149.
