### ISSUE TITLE
Brazilian Portuguese pt-BR

### ISSUE THREAD

**Issue by fcsweb2** [Common-Voice/sentence-collector#184]
Do not have the Brazilian Portuguese pt-BR

**Comment by MichaelKohler** [comment]
@nukeador it seems that the Portuguese in Pontoon is pt-BR, and ours is just Portuguese. I'm not sure if we could just rename it, as it already has sentences and some of them might not be pt-BR compatible. Thoughts?

**Comment by nukeador** [comment]
Portuguese should be just one language, same as Spanish, French, German... and then have accents for the different regions (Portugal, Brazil...).

I'll check with Peiying to make sure Common Voice is just enabled in the languages and not the different accents.
