### ISSUE TITLE
No sentences exported for new locale lv

### ISSUE THREAD

**Issue by raivisdejus** [Common-Voice/sentence-collector#186]
Hi,
I was playing around on local with new locale - Latvian (lv), and no data gets exported.

To test I modified the `scripts/exporter.js` to have the following function call ```await exportLanguage(db, 'lv', exportPath);```

I have added and approved several sentences in the app and I see that the Kinto backend gets called, but the `approvedSentences` array is empty.

Asking this here as it seems that to get new locale added we need to prepare a pull request with some sentences. I have started gathering the sentences, but the export will not work for me. 

Hope you can point me in the right direction!

**Comment by MichaelKohler** [comment]
Did you review the sentences with 3 different users? One positive review is not enough, only after 3 votes (with two of them positive) the sentence is marked as approved.

**Comment by raivisdejus** [comment]
Thanks for note, that was the missing peace. All works fine.
