### ISSUE TITLE
Connection between https://voice.mozilla.org and sentence-collector

### ISSUE THREAD

**Issue by Bullnados** [Common-Voice/sentence-collector#187]
Some ideas:

- same UI
- same login data
- linking between the two websites

Or are these two completly indepentend? If yes, clearify this directly on the collector webpage and write down the usage of the collector

**Comment by MichaelKohler** [comment]
Thanks for filing this issue!

@nukeador this sounds like a good thing to do, we should link to voice.mozilla.org whenever we mention it. Thoughts?

The rest IMHO will be tackled later, and wouldn't require an open issue for this to be tracked, correct?

**Comment by nukeador** [comment]
Same URL and login are currently not our priorities, but nice to have in the future if we integrate the collection into the main site.

For links, please add requests for where you think we should have links inside the main site:

https://github.com/mozilla/voice-web/issues

**Comment by Bullnados** [comment]
For UI, okay we can discuss, but one login would be pretty nice.
My personal thought was, "Strange, is this realy a project linked with voice? Why I have to create a seperate account?
But if you link on startpage and clearify this, for first fast shot it is okay 👍

**Comment by Gaet81** [comment]
I don't understand neither why I need a specific login for this site. Login should be the same for all projects related to the DeepSpeech project...

**Comment by nukeador** [comment]
> I don't understand neither why I need a specific login for this site. Login should be the same for all projects related to the DeepSpeech project...

We all agree, but unfortunately we haven't had time or resources to do that yet, it's planned for the future. I hope you understand.

Cheers.

**Comment by Bullnados** [comment]
Is it possible to split this issue? Atm only note in Website is implemented.

**Comment by MichaelKohler** [comment]
Not sure I understand. This is implemented in the Sentence Collector. For voice.mozilla.org issue tracking happens at https://github.com/mozilla/voice-web/issues

**Comment by Bullnados** [comment]
At the moment same UI and login is still missing,
So I would create two new issues to track  that missings
