### ISSUE TITLE
Review the sentences in https://pontoon.mozilla.org/de/ ?

### ISSUE THREAD

**Issue by Bullnados** [Common-Voice/sentence-collector#188]
Is there a reason why pontoon(backend) isn't used for reviewing the sentences?

**Comment by MichaelKohler** [comment]
@nukeador I'll leave this to you

**Comment by nukeador** [comment]
Pontoon is not a tool to review sentences but to translate a source→target language, it is not designed for this. Localization team can provide a more detailed answer.

We tried in the past experimenting with a similar localization tool for review and it was clearly too confusing for people and very hacky and time consuming to set up property, as well as limited to all our needs.

Feel free to create this question in our discourse if you have additional feedback on how to improve the current tool

https://discourse.mozilla.org/c/voice

Thanks!
