### ISSUE TITLE
Possibility to download sentences...

### ISSUE THREAD

**Issue by Bullnados** [Common-Voice/sentence-collector#189]
... in csv for example, selectable per language.
I would check if all/most of the f.e. German words are represented. Here I want use this list http://pcai056.informatik.uni-leipzig.de/downloads/etc/legacy/Papers/top10000de.txt

Perhaps such lists are also existing for other languages?

**Comment by MichaelKohler** [comment]
I like this idea!

**Comment by MichaelKohler** [comment]
We could just point to the API (review queue) and set the "download" flag on the link, if filters in the URL work as I'd expect. Will have a look.

**Comment by MichaelKohler** [comment]
Nope, that won't work as we could only get the first 10k sentences like that.

**Comment by Bullnados** [comment]
This monolog looks strange. It  seems that you are fighting your an other me. xD

**Comment by MichaelKohler** [comment]
This is now fixed in the latest version which just got deployed: https://discourse.mozilla.org/t/action-required-new-sentence-collector-infrastructure-and-improvements/68759. See the README for more info.
