### ISSUE TITLE
Optimize homepage load using batch requests

### ISSUE THREAD

**Issue by leplatrem** [Common-Voice/sentence-collector#19]
The homepage sends a lot of requests to the server. At least one per language (+CORS etc.)

https://github.com/Common-Voice/sentence-collector/blob/e4ac834a42d46fcb8fb4e561986708579968830b/shared/db/collections/sentences-meta.js#L79-L81

There is a *batch* API on the server that would allow you to group requests. Especially if in the end your goal is just to get the total records of each collection.

Instead you could obtain the list of collections, and build a payload like this one:
```
$ curl -s -X POST -H 'Content-Type: application/json' -d '{
  "defaults": {
    "method": "HEAD"
  },
  "requests": [
    { "path": "/buckets/App/collections/Sentences_Meta_kv/records" },
    { "path": "/buckets/App/collections/Sentences_Meta_ku/records" },
    { "path": "/buckets/App/collections/Sentences_Meta_kk/records" }
  ]
}' https://kinto.mozvoice.org/v1/batch | jq '.responses[].headers["Total-Records"]'

"0"
"0"
"0"
```

By default you can batch 25 requests in one POST, but you could also set the `KINTO_BATCH_MAX_REQUESTS` server setting to a higher value...

The kinto-http.js client has a batch API abstraction, but it may deserve some improvements since it's mainly thought to be used within a collection... 

We also had thought of a server plugin that would denormalize this information (number of collections/records stored in bucket metadata for example... https://github.com/Kinto/kinto/issues/360)

**Comment by MichaelKohler** [comment]
Absolutely, thanks for the input!

**Comment by MichaelKohler** [comment]
Without digging further into the npm package, it *seems* batch only works on collections, and not overall: https://www.npmjs.com/package/kinto-http#batching-operations

Am I missing something?

**Comment by leplatrem** [comment]
As I noted in the issue description, the kinto-http.js client has a batch API abstraction that was meant to be used on collections only. 

But it would be interesting to improve it or document what can be done for use-cases like yours ;)

I'm pretty sure you can use something like this (untested):

```js
const resp = await client.batch((batch) => {
  for (cont cid of ["Sentences_Meta_kk", "Sentences_Meta_ku", "Sentences_Meta_kk"]) {
    batch.collection(cid)
         .getTotalRecords();
  }
}, { bucket: "App" });

const results = resp.json();
```

**Comment by mikehenrty** [comment]
> I'm pretty sure you can use something like this (untested):

Nice! I was looking for something like that. Hopefully it works.
