### ISSUE TITLE
Review queue capped at 10,000?

### ISSUE THREAD

**Issue by dabinat** [Common-Voice/sentence-collector#194]
The review queue seems to be capped at 10,000 items. No matter how many I review, there are always 3334 pages (on which the last always has a single sentence) and the home page always says there are 10000 in the queue.

Is there a particular reason for this? I don’t see that it would affect performance much as it’s still only showing 3 items per page no matter which page you’re on.

**Comment by MichaelKohler** [comment]
Thanks for filing this issue. This is due to Kinto having a limit of 10k results per request, so we don't wanna spam Kinto just to get the total records number according to our filtering. More info here: https://github.com/Common-Voice/sentence-collector/issues/160
