### ISSUE TITLE
Testing the validators

### ISSUE THREAD

**Issue by jotaro-sama** [Common-Voice/sentence-collector#195]
Hi, I'm working on the validator for the italian language on behalf of the italian Mozilla community. I was following [these guidelines](https://github.com/Common-Voice/sentence-collector/blob/master/shared/validation/VALIDATION.md) and I've also built and run the whole server on my machine, but I can't find any way of testing the validators from the web interface. How should I proceed in order to test them on some sentences?

**Comment by jotaro-sama** [comment]
Nevermind, I just realized that the validator filters bad sentences when you try to add them from the "Add" section, telling you which ones are wrong.

**Comment by MichaelKohler** [comment]
Correct. Thanks for working on this, looking forward to the PR!

**Comment by jotaro-sama** [comment]
I've already submitted [it](https://github.com/Common-Voice/sentence-collector/pull/197)!
