### ISSUE TITLE
Script to delete specific sentences

### ISSUE THREAD

**Issue by MichaelKohler** [Common-Voice/sentence-collector#198]
As we can't 100% make sure that invalid sentences are approved by someone, we should create a script that deletes a set of given sentences from the DB to delete them from the export.

This need comes out of https://github.com/mozilla/voice-web/pull/1890

The script would take:
* a language
* a list of sentences to delete

The script would output:
* Any sentences it couldn't delete
* Number of sentences deleted

**Comment by Mte90** [comment]
I like that, this enable to automatize the removal of sentences also by their content like we did with the txt files with other scripts instead now that is manually.
