### ISSUE TITLE
Common Voice logo not displayed on site

### ISSUE THREAD

**Issue by Adrijaned** [Common-Voice/sentence-collector#200]
In the top-left corner of the site there is a common voice logo supposed to be displayed, but it isn't.
![Screenshot_20190328_150410](https://user-images.githubusercontent.com/22203805/55163804-c0878180-516a-11e9-858b-b8a482f2970a.png)

**Comment by MichaelKohler** [comment]
Good catch, thx!

**Comment by MichaelKohler** [comment]
That completely went wrong, let's try that again..

**Comment by MichaelKohler** [comment]
This is now fixed with version 1.8.3.. https://common-voice.github.io/sentence-collector/#/
