### ISSUE TITLE
Disallow sentences starting with lowercase letter

### ISSUE THREAD

**Issue by Adrijaned** [Common-Voice/sentence-collector#202]
Would it be possible/viable to update the new sentence validator to disallow any sentences starting with lowercase letters/not ending in `[.?!]`/containing `[?!]` in the middle?

After all, sentences should be spelled correctly - thus starting with uppercase character in almost any language I can imagine. Blacklisting lowercase characters is however better choice than whitelisting uppercase due to the wide amount of scripts used around the world.

This arose mainly after having to review a great bunch of sentences that were basically probably coming from a large block of text, just randomnly split after every few words.

The ending check is because: 1) sentences should just end in one of those to be considered sentences 2) I have too reviewed a great bunch of sentences which were "Head one", "Paragraph five" and similar

The `[?!]` check in the middle is for ensuring only one sentence per line. `.` intentionally not included due to some languages using that for other things.

**Comment by nukeador** [comment]
Having sentences starting with lowercase is not an issue for the deepspeech algorithm.

It seems like a too high bar to ask people to also make sure every sentence starts with upper case. Do you have other ideas to identify sentences that are no making any sense because they are not complete sentences?

**Comment by MichaelKohler** [comment]
> The [?!] check in the middle is for ensuring only one sentence per line. . intentionally not included due to some languages using that for other things.

I think that definitely makes sense. I doubt there is any language that this would be valid. And if so, we can still allow it through that locale's validator if necessary. Would you like to create a PR for this? :)

**Comment by jotaro-sama** [comment]
> > The [?!] check in the middle is for ensuring only one sentence per line. . intentionally not included due to some languages using that for other things.
> 
> I think that definitely makes sense. I doubt there is any language that this would be valid. And if so, we can still allow it through that locale's validator if necessary. Would you like to create a PR for this? :)


I can handle this since we already check for `.` in the middle of the sentences in the Italian validator. Do you want me to add the `[!?\.]` check in the middle only, or also to enforce the ending `[!?.]`?

Note: I will make those fully overridable in their specific language validators, since it looks like some languages could use these characters in other ways.

**Comment by MichaelKohler** [comment]
> Do you want me to add the [!?\.] check in the middle only, or also to enforce the ending [!?.]?

In the middle only please.

> Note: I will make those checks fully overridable in their specific language validators, since it looks like some languages could use these characters in other ways.

Do you have examples?

**Comment by jotaro-sama** [comment]
> > Note: I will make those checks fully overridable in their specific language validators, since it looks like some languages could use these characters in other ways.
> 
> Do you have examples?

I have none as of now, but just like we are not making the check for the `.` in the middle right now because @Adrijaned says some languages use it in other ways, I'd like to make as few assumptions as possible about how specific validators may want to handle this. Anyway it's no big deal, it'll be overridable just like the other checks are as of now. I'll start working on it ASAP.

**Comment by MichaelNMaggs** [comment]
Please don't enforce those checks in the middle of sentence. It's extremely common to have [?!] in the middle, for example:

"Where are you going?" he asked.
"Help!" she shouted.

**Comment by MichaelNMaggs** [comment]
In English it would actually be useful to disallow sentences that start with a lower case letter. I think they often occur when the uploader is extracting sentences from a PD source and the sentence tokenizer has split a sentence in the wrong place.

eg where "_We need help. Now." the boy said._" is wrongly split as

We need help.
Now.
the boy said.

The first two parts are OK, but the last part needs to be trapped either by the user, or by the upload filter.  

(This type of construction is a favourite of Dickens. I've seen it hundreds of times and had to filter it out myself).

**Comment by Adrijaned** [comment]
Personally, if I have seen a sentence like one of those two you are suggesting, I would probably reject - It is not a converationary sentence, and there might be some inclarity in the pronounciation of the sentence (+ with the sheer amount of sentences when in doubt, just reject)

**Comment by MichaelNMaggs** [comment]
@nukeador, in reply to @Adrijaned's request you've said that 

_> Having sentences starting with lowercase is not an issue for the deepspeech algorithm._

Even so, there are strong practical volunteer-related issues for rejecting such fragments.

They are non-grammatical, and fail the stated test that "_**The sentence must be grammatically correct**_" (see the existing rules at https://common-voice.github.io/sentence-collector/#/how-to).  That's an easy and straightforward test for people to understand, and can be stated shortly.  Adding "**_can also be a non-grammatical sentence fragment_**" introduces all sorts of ambiguity as to what is and is not allowed.

Validators know that sentence-fragments frequently seem to surprise readers. They don't know what to make of them, nor how to read them, particularly where the fragments make no sense.  Those that try often stumble over the words.

Fragments virtually never, in my experience, come from users who are making sentences up themselves. Rather, they are an artefact of user scripts to extracts sentences from old books and the like, where the tokeniser wrongly thinks that an exclamation or question mark can only come at the end of a sentence.  Original sentences such as

_**- What do you want me to do? replied John angrily, not expecting an answer.**_
**_- “Look out!”, she shrieked, not realising he couldn't do any such thing._**

results in non-grammatical fragments such as

**_- replied John angrily, not expecting an answer._**
**_- she shrieked, not realising he couldn't do any such thing._**

Filtering out such fragments won't make it any harder for users to run extraction scripts, but it will save volunteer time in checking and rejecting invalid fragments. Or alternatively, it will avoid the need to add complex and unclear validation rules in order redefine them as valid.

There's no need to invalidate existing fragments that are already in the corpus, but new ones should in my view be prohibited.

**Comment by nukeador** [comment]
By your observations, what's the rate of sentences that make sense vs don't make sense from the ones starting with lower case?

**Comment by MichaelNMaggs** [comment]
I'd say that the vast majority of texts starting with a lower case letter don't make sense when read alone.  Very few indeed (I'd guess only a few percent) are full sentences, or fragments that could be read that way.  Almost always, the most one can make of most of them is "_this is a partial sentence that I can't fully understand, but I realise that something must be missing_".

**Comment by dabinat** [comment]
Although I am also struggling to think of situations in English where starting with a lowercase letter would be valid, this might be best addressed by having hard and soft validation failures as outlined here: https://github.com/Common-Voice/sentence-collector/issues/168

So the site flags up the sentence as possibly being incorrect and the submitter can choose to override it if necessary.

**Comment by MichaelKohler** [comment]
I've created #311 to use the Sentence Extractor rules for the Sentence Collector as well. This would already be included there.
