### ISSUE TITLE
Filter curly quotes

### ISSUE THREAD

**Issue by dabinat** [Common-Voice/sentence-collector#205]
I noticed when doing some digging into sentence-collector.txt that we have sentences with words like "that's" and sentences with words like "that\xe2\x80\x99s". I'm guessing that's because the writer's word processor changed the apostrophe to a curly quote.

DeepSpeech's alphabet.txt does include apostrophes so I'm not sure how it behaves when faced with curly apostrophes. But regardless of that, I think all "stylized" symbols, including things like long dashes, should be converted to their ASCII equivalents so that we're at least treating them all consistently.

**Comment by MichaelNMaggs** [comment]
Gutenberg texts are by no means consistent.  Some of their texts also use the same character for both quotes and apostrophes.

**Comment by MichaelKohler** [comment]
I've created #311 to use the Sentence Extractor rules for the Sentence Collector as well. This would already be included there.
