### ISSUE TITLE
Notifications for languages

### ISSUE THREAD

**Issue by Mte90** [Common-Voice/sentence-collector#206]
Right now to see if there are new sentences I have to go on the website, wait for loading and start doing the review.
It will be more simple to receive an email notification, so we can organize as team to review them in time instead after months.

**Comment by MichaelKohler** [comment]
Thanks for filing this issue. I've moved the discussion to https://discourse.mozilla.org/t/sentence-collector-open-discussions-input-needed/63925. Let's file a new issue with more detail once we have feedback there and know how to proceed here.
