### ISSUE TITLE
Add OAuth (Firefox, GitHub, Google) authentification like Common Voice website

### ISSUE THREAD

**Issue by pinage404** [Common-Voice/sentence-collector#208]
I have an account with Google (it was the simplest option at the moment), i don't find any place to set a password on Common Voice website, so i don't know how to use my Common Voice account to login

I would like to be able to login with OAuth methods (Firefox, GitHub, Google) like in the Common Voice website

**Comment by MichaelKohler** [comment]
Hi, thanks for filing this issue. This will come at some point, though there are currently other priorities. I'll move this to the backlog.

**Comment by MichaelKohler** [comment]
We will do this as well as part of the infra work, so I'm putting this into progress and will do some work here.

**Comment by MichaelKohler** [comment]
This is now in the latest version which just got deployed: https://discourse.mozilla.org/t/action-required-new-sentence-collector-infrastructure-and-improvements/68759
