### ISSUE TITLE
How is the author of the strings?

### ISSUE THREAD

**Issue by Mte90** [Common-Voice/sentence-collector#209]
I was wondering if there is a way to reach who uploaded the strings to discuss the kind of content that uploaded.

**Comment by MichaelKohler** [comment]
You can get the Italian sentences through https://kinto.mozvoice.org/v1/buckets/App/collections/Sentences_Meta_it/records. You can then also filter by username for example: https://kinto.mozvoice.org/v1/buckets/App/collections/Sentences_Meta_it/records?username=Jean

**Comment by Mte90** [comment]
As I can see from the JSON the same uploaded of the sentences can vote them.
This perhaps doesn't help on validating them, as I can remember to get approved require only 2 approval.

**Comment by Mte90** [comment]
Also now that I have the username how I can find his profile to reach the author?

**Comment by MichaelKohler** [comment]
> As I can see from the JSON the same uploaded of the sentences can vote them.
This perhaps doesn't help on validating them, as I can remember to get approved require only 2 approval.

See https://github.com/Common-Voice/sentence-collector/issues/163

> Also now that I have the username how I can find his profile to reach the author?

There are no profiles. If you can't do anything with the username, we won't be able to help here.

**Comment by Mte90** [comment]
Ok I have no idea who is Jean and reach him to discuss about the content he uploaded :-/
