### ISSUE TITLE
Autosubmit when all the sentences are marked

### ISSUE THREAD

**Issue by Mte90** [Common-Voice/sentence-collector#210]
Because It is very boring with only 5 to press all this buttons to review sentences. For italian we have 1040 pages of sentences...
Or I will do an extension for that 😂

**Comment by MichaelKohler** [comment]
Existing Discourse topic, https://discourse.mozilla.org/t/suggestions-for-the-sentence-collector/37734. Can you add your suggestion there? Thanks
