### ISSUE TITLE
Review all the Basque sentences

### ISSUE THREAD

**Issue by Txopi** [Common-Voice/sentence-collector#212]
Some months ago, just after the Sentence Collector data-base was cleaned up, I loaded all the Basque sentences in the Sentence Collector and you deployed (great!) them on Common Voice, but the truth is that I never reviewed the sentences one by one.

Time goes by and Basque people is working hard to record as many clips as the can. I'm not sure if in the future any user will run out of sentences. So before that, I ask to put the Sentence Collector's Basque sentences in a stable situation, i.e. all validated.

If we upload new sentences in some months, it has no sense to find 1.243 pages of old sentences not accepted yet. I could accept them one by one though the interface of the application but in my opinion that's a big amount of silly work and I ask for a massive automatic accept of the existing Basque sentences as they are deployed long ago. I haven't added any Basque sentence in the Sentence Collector since the first (and unique) deployment of Basque sentences. Is it possible?

Thank you very much!

**Comment by MichaelKohler** [comment]
I'll defer to @nukeador for this.

**Comment by nukeador** [comment]
Hi there,

Unfortunately the agreement we got is that we won't bypass sentence collector workflow, I know this can be a bit inconvenient.

We are currently investing our time to find a better solution for the future where we can automate most of the process and extract from large sources:

https://discourse.mozilla.org/t/extending-our-sentence-collection-capabilities/38783/

But it's going to take us some time with the current workload we have.

I hope you understand. Thanks!
