### ISSUE TITLE
I should be able to update the sentences that I have submitted (on the Sentence Collector itself).

### ISSUE THREAD

**Issue by roshangm1** [Common-Voice/sentence-collector#217]
I think, I should be able to make changes in the sentences that I collect in the Sentence Collector platform. 
Moreover, I wonder if there can also be a way where there are 1 or more reviewers who have power to force update the sentences (to fix minor issues) while reviewing.

**Comment by MichaelKohler** [comment]
I think #284 would solve most of that. For the force updating part, this would require user roles which we currently don't have. Let's re-evaluate this once we've migrated to using Auth0.
