### ISSUE TITLE
Add review criteria to Review Form

### ISSUE THREAD

**Issue by iveskins** [Common-Voice/sentence-collector#220]
It would be nice if the review page could have a tooltip or expandable text area or something to provide reference to the review criteria directly as one is reviewing.

**Comment by MichaelKohler** [comment]
I think that's a good idea.

**Comment by MichaelKohler** [comment]
I think we could add the review criteria from "How To" section "Make sure the sentence meets the following criteria:" directly on the review form. However, this should take as little space as possible, to make sure that the sentences are still fitting on one screen (of course that depends on the screen resolution..). I think something like a "help" section which is expandable would be great.

**Comment by parshva-b** [comment]
@MichaelKohler, I would like to contribute to this issue, Can I **claim** this issue?

**Comment by MichaelKohler** [comment]
There is already an open PR for this: https://github.com/Common-Voice/sentence-collector/pull/282.

**Comment by MichaelKohler** [comment]
@parshva-b there is https://github.com/Common-Voice/sentence-collector/issues/271 which would need a fix, if you are interested :)
