### ISSUE TITLE
Change logic to decide if sentence is approved

### ISSUE THREAD

**Issue by gion-andri** [Common-Voice/sentence-collector#224]
I think, the following logic to decide, if a sentence was approved, does not make any sense: 

```
  checkIfApproved(record) {
    const validVotes = record.valid.length;
    const invalidVotes = record.invalid.length;
    const totalVotes = validVotes + invalidVotes;

    if (totalVotes < APPROVAL_MIN_TOTAL_VOTES) {
      return;
    }

    return validVotes >= APPROVAL_MIN_VALID_VOTES;
  }
```

Lets say, a record was marked as valid two times. To be approved, it is necessary that a third reviewer reviews the sentence. Even if the third marks the sentence as invalid, the sentence would be approved. So the third reviewer has no effect (his time is actually just wasted).

I think, something like
```
  checkIfApproved(record) {
    const validVotes = record.valid.length;
    const invalidVotes = record.invalid.length;
    const totalVotes = validVotes + invalidVotes;

    if(validVotes >= APPROVAL_MIN_VALID_VOTES) {
      return true;
    } else if(totalVotes >= APPROVAL_MIN_TOTAL_VOTES) {
      return false;
    }

    return;
  }
```

would have the same effect but save quite some community time. 

What do you think? If you agree, I can open a PR for this change.

**Comment by MichaelKohler** [comment]
Hi @gion-andri, good to hear from you! I can totally see how this impacts smaller communities such as yours :) I fully agree that this should be fixed and I wanted to do that for a long time now, but I totally forgot by now as I didn't create an issue. Thanks for bringing this up again!

Would love to have a PR for this :)

Thanks!

**Comment by gion-andri** [comment]
@MichaelKohler Yeah, long time no see :)
Yes, as our community is very small and we need to collect sentences (and finally voice samples) for 5 different idioms, every minute we can save by improving processes is quite valuable :)
