### ISSUE TITLE
Sentence collector shows zero counter for Abkhazian 

### ISSUE THREAD

**Issue by danielinux7** [Common-Voice/sentence-collector#230]
Sentence collector shows zero counter for Abkhazian, here is a screenshot:
![Screenshot from 2019-06-26 14-21-34](https://user-images.githubusercontent.com/2645266/60176094-ff86ab00-981d-11e9-8a77-0a841cc947a0.png)

**Comment by nukeador** [comment]
Thanks for reporting. I've already informed about this to @MichaelKohler 

(It might take a while since he is on a different timezone and off for this week)

**Comment by MichaelKohler** [comment]
I personally don't have access to the server and it seems there are some issues restarting the backend service. For the time being, I'll put up a banner explaining it until we've successfully restored services.

**Comment by MichaelKohler** [comment]
This has been fixed in the mean time.
