### ISSUE TITLE
Can't add a language to sentence collector

### ISSUE THREAD

**Issue by danielinux7** [Common-Voice/sentence-collector#231]
Can't add arabic language to sentence collector, here is a screenshot:
![Screenshot from 2019-06-26 14-25-44](https://user-images.githubusercontent.com/2645266/60176217-555b5300-981e-11e9-942e-ab53b8d1b5ba.png)

**Comment by nukeador** [comment]
Thanks for reporting. I've already informed about this to @MichaelKohler 

(It might take a while since he is on a different timezone and off for this week)

**Comment by MichaelKohler** [comment]
I personally don't have access to the server and it seems there are some issues restarting the backend service. For the time being, I'll put up a banner explaining it until we've successfully restored services.

**Comment by nukeador** [comment]
Is this issue already solved?
