### ISSUE TITLE
Possibility for articles from Wikipedia

### ISSUE THREAD

**Issue by filips123** [Common-Voice/sentence-collector#237]
Would it be possible to allow sentences from articles from Wikipedia? This would massively increase the number of sentences.

"How to" page says:

> Unfortunately we can’t have Wikimedia articles **yet**. So do not copy paste from there.

So that we can't use articles from Wikipedia **yet**. This should mean that they will be supported at some time. When will that be?

---

Also, is it currently possible to use sentences from Wikisource? Most of the content there is in the public domain.

**Comment by nukeador** [comment]
We can't use sources that are not public domain, wikipedia is not.

Having said that, this is where we are right now:

https://discourse.mozilla.org/t/extending-our-sentence-collection-capabilities/38783

Cheers.

**Comment by filips123** [comment]
Most Wikipedia articles are licenced under *CC BY-SA 3.0* which requires attribution to the original author. Would it be possible to somehow implement this?

**Comment by nukeador** [comment]
Unfortunately no, currently Common Voice dataset is released under Public Domain CC-0, which is not compatible with CC BY-SA.

Please refer to the discourse topic I linked for more details on the alternative and legal ways we are exploring.

Thanks!
