### ISSUE TITLE
number of validated/rejected sentences

### ISSUE THREAD

**Issue by mozillakab** [Common-Voice/sentence-collector#240]
#Stats seem blocked at 10 000

![2019-07-17 16_39_56-Common Voice Sentence Collector](https://user-images.githubusercontent.com/7033740/61390037-4ebe7980-a8ba-11e9-9a53-f9ab3a53c701.jpg)

**Comment by stefangrotz** [comment]
More and more languages are passing the 10 000 sentences threshold, what exactly causes this bug? This looks solvable by a simple change of the number format.

**Comment by MichaelKohler** [comment]
Pagination in kinto is limited to 10k per page, I wish it was that simple. If we do pagination, it's gonna get even slower. Nothing we seriously can do until we have invested in a real backend (I have a concept, but no plan yet).

**Comment by missuniverse** [comment]
@MichaelKohler If I have 100 000 sentences of Romanian to upload, is there a way I could email them to you or something? Or should I just wait for this to be fixed?

**Comment by MichaelKohler** [comment]
@missuniverse for 100'000 sentences at once I'd suggest to go through the same process as here: https://github.com/mozilla/common-voice/pull/2869

**Comment by MichaelKohler** [comment]
This is now fixed in the latest version which just got deployed: https://discourse.mozilla.org/t/action-required-new-sentence-collector-infrastructure-and-improvements/68759
