### ISSUE TITLE
Sentence collector: rejection message

### ISSUE THREAD

**Issue by mozillakab** [Common-Voice/sentence-collector#252]
Some kab sentence collectors are getting this message when sending sentences: last modifed precondition failed. Could someone explain what does this mean?

![5092c5906f645301645233a809242d1297e9d3f7](https://user-images.githubusercontent.com/7033740/63818219-53a62c80-c940-11e9-969b-02913e10e098.png)

**Comment by MichaelKohler** [comment]
@mozillakab thanks for the report. Could it be that these sentences had been added by another contributor right before submitting? If not, do you see any common pattern when this error occurs?

**Comment by mozillakab** [comment]
@MichaelKohler as we are sharing the same repo on github where we are putting raw corpora, I suspect that some of us have sent same sentences on SC. It's not the first time we got such a message.

**Comment by MichaelKohler** [comment]
Let's keep an eye on it, as this possibly is quite hard to reproduce to debug, any better steps on how to get into that state would help.

**Comment by MichaelKohler** [comment]
I'm closing this, feel free to reopen if this happens again.
