### ISSUE TITLE
Visual page navigation bug when submitting reviewed sentences

### ISSUE THREAD

**Issue by Adrijaned** [Common-Voice/sentence-collector#258]
When displaying the "Submitting senteces, please do not close", the page nav looks like in the picture

![Screenshot_20190922_182038](https://user-images.githubusercontent.com/22203805/65391135-fb5b2280-dd65-11e9-8992-ca4dfcd03f4b.png)

**Comment by MichaelKohler** [comment]
Thanks, I guess we are using a fixed width somewhere instead of being nicely responsive.

**Comment by michael-dean-haynie** [comment]
@MichaelKohler, @alejandroclose - Any recent movement on this issue? I'd like to pick it up but don't want to snipe it.

**Comment by MichaelKohler** [comment]
@michael-dean-haynie feel free to take this one as it's been 23 days :)

**Comment by Shubhamchinda** [comment]
Hey, I'd like to work on this issue!

**Comment by Adrijaned** [comment]
Hey @Shubhamchinda, I'm afraid this was already fixxed in #262 . Closing as such.
