### ISSUE TITLE
Research: ability/feasibility of sentence import from WikiData

### ISSUE THREAD

**Issue by Adrijaned** [Common-Voice/sentence-collector#260]
WikiData is somewhat new project by Wikimedia Foundation, providing database-style data on about everything, while being CC0. One of the specific subsets of data they are providing over there are lexemes, which sometimes include example sentences. Those might be fit for inclusion in the Common Voice dataset.
Pros: 
- Everything is CC0
- As those are example sentences for all kinds of lexemes, the dataset can get to include even less usual words
- Those are already individual sentences, so there should be no issues with splitting them up as is the case when harvesting complete works

Cons:
- That project of wikimedia foundation is not really that succesfull - at the moment of writing, there are 130 english sentences, and some of them are duplicates, or, occasionaly, swedish
- In case of multiple consecutive imports from that source, sentences could get included multiple times

Expected outcome of this:
Unless someone gets some geeky pleasure from implementing this, or the wikidata project really takes off, this should probably be left alone as long as there are other things to do. Making this issue just in case though.

**Comment by nukeador** [comment]
Thanks for bringing this up. Let's definitely keep an eye on how this project evolves.

**Comment by MichaelKohler** [comment]
Let's track this in https://github.com/Common-Voice/common-voice-wiki-scraper/issues/92
