### ISSUE TITLE
Add French Cleanup file

### ISSUE THREAD

**Issue by MichaelKohler** [Common-Voice/sentence-collector#268]
According to https://github.com/mozilla/voice-web/pull/2262#issuecomment-553848602 the EN cleanup does not work for FR. This should be changed. Here are the rules that are valid for French:

```
      .replace('  ', ' ')
      .replace(/^,+\s/, '') // we do not want commas at the beginning of the sentence
      .replace(/^,+/, '') // we do not want commas at the beginning of the sentence
      .replace(/,+$/, '') // we do not want commas at the end of the sentence
```

**Comment by MichaelKohler** [comment]
To add a new cleanup file for a given language, refer to https://github.com/Common-Voice/sentence-collector/blob/master/shared/cleanup/CLEANUP.md. Let's hold off this until we figured out https://github.com/mozilla/voice-web/issues/2259 so we don't create a complete mess.

**Comment by lissyx** [comment]
> Here are the rules that are valid for French

They are not complete, but at least this set would not introduce typographic errors :)
