### ISSUE TITLE
Rejected sentence: add an icon 

### ISSUE THREAD

**Issue by mozillakab** [Common-Voice/sentence-collector#275]
Add a red icon to indicate that there are rejected sentences.

A contributor on Sentence Collector (kab language) said he didn't know that some of his sentences were rejected. I think a small red icon next Rejected Sentences should help.

Note that kab speaking people are also French Speaking people but not English. That's why we have few kab contributors on IRC, Discourse, Github, ...and other Mozilla's platforms.

![2019-12-12 15_00_08-Common Voice Sentence Collector](https://user-images.githubusercontent.com/7033740/70718488-983bb500-1cf0-11ea-8f77-d27865e11ab3.jpg)

**Comment by MichaelKohler** [comment]
I like the idea of having a badge showing the numbers of rejected sentences. That would however require more backend work than we're gonna do for now. So I don't think that is gonna happen anytime soon.

What maybe could be done for now is a indication if there are new rejected sentences in the past week or so, but that wouldn't clear once seen. So not really a great mid term solution.

**Comment by mozillakab** [comment]
@MichaelKohler for now, we need an indication to show there are some rejected sentences. Later, we can plan as you suggested a badge showing the number of the rejected sentences when hovering an icon for example.

**Comment by SelyanKab** [comment]
Hello @mozillakab @MichaelKohler 
Yes, many contributors have reported this problem, we would like to have a way to know which sentences were rejected.
Thank you muhend for offering this option.

**Comment by MichaelKohler** [comment]
Thanks for filing this issue. I've moved this to https://discourse.mozilla.org/t/sentence-collector-open-discussions-input-needed/63925 to discuss a possible approach here that helps most users.
