### ISSUE TITLE
Add a filter - added by (user)

### ISSUE THREAD

**Issue by mozillakab** [Common-Voice/sentence-collector#280]
I suggest, when reviewing sentences, to add a filter by user (added by).
![2019-12-17 20_35_32-2019-12-17 12_10_59-Common Voice Sentence Collector jpg - Visionneuse de photos ](https://user-images.githubusercontent.com/7033740/71028381-746fd900-210d-11ea-80ce-8eb7086b8069.jpg)

**Comment by MichaelKohler** [comment]
What would this enable you to do that you can't do right now?

**Comment by mozillakab** [comment]
We have in the kab team some people adding sentences. They are graduated from the Amazigh (Kabyle) language departments in Kabylia , so I'd like first verify their sentences.

**Comment by MichaelKohler** [comment]
Thanks for filing this issue. I've moved the discussion to https://discourse.mozilla.org/t/sentence-collector-open-discussions-input-needed/63925. Let's file a new issue with more detail once we have feedback there and know how to proceed here.
