### ISSUE TITLE
Some Arabic Sentences have the period at the wrong place

### ISSUE THREAD

**Issue by MichaelKohler** [Common-Voice/sentence-collector#281]
Some of the Arabic exported sentences have the period on the wrong side of the sentence. A block of examples can be found at https://github.com/mozilla/voice-web/blob/master/server/data/ar/sentence-collector.txt#L1627.

We are splitting on line breaks, so I'm not sure if the splitting of multiple sentences is to be blamed here. Should we further investigated.

**Comment by abusarimhindi** [comment]
The Arabic is a RTL language, if we see this sentences in RTL the period will be at end of the sentence.

**Comment by MichaelKohler** [comment]
> The Arabic is a RTL language, if we see this sentences in RTL the period will be at end of the sentence.

So you're saying these are correct, but GitHub doesn't show it in RTL and therefore it just appears to be wrong but isn't? That would be great :)

**Comment by abusarimhindi** [comment]
There is no need to put (.) period, the sentence collector doing wrong, he is also putting number in sentence https://github.com/mozilla/voice-web/blob/master/server/data/ar/sentence-collector.txt#L1240

**Comment by abusarimhindi** [comment]
This character (.) is not RTL, it is LTR character.

**Comment by MichaelKohler** [comment]
> There is no need to put (.) period, the sentence collector doing wrong
> This character (.) is not RTL, it is LTR character.

Can you show me an example of a sentence with a period that would be correct? And this means that generally we could forbid the use of the LTR . ?

> he is also putting number in sentence

This has to do with the fact that there is no validation file for Arabic yet: https://github.com/Common-Voice/sentence-collector/tree/master/shared/validation/languages . Would be great if we could get one, would you be interested in helping with this? :)

**Comment by abusarimhindi** [comment]
> > There is no need to put (.) period, the sentence collector doing wrong
> > This character (.) is not RTL, it is LTR character.
> 
> Can you show me an example of a sentence with a period that would be correct? And this means that generally we could forbid the use of the LTR . ?
> 
> > he is also putting number in sentence
> 
> This has to do with the fact that there is no validation file for Arabic yet: https://github.com/Common-Voice/sentence-collector/tree/master/shared/validation/languages . Would be great if we could get one, would you be interested in helping with this? :)

We use this period (۔) for Urdu language. And these are the digits of Arabic [٠١٢٣٤٥٦٧٨٩] from 0 to 9

**Comment by abusarimhindi** [comment]
Dear @MichaelKohler , I am not expert in coding and don't know any coding language, I came on GitHub to create pull request for my Urdu language, but I failed to create this, getting errors, and I couldn't understand where I am wrong.

For Urdu language limitation of 14 words is a problem, we need approx 25 words for a complete meaningful sentence.

I request you to please help me to create this PR.

**Comment by MichaelKohler** [comment]
> I request you to please help me to create this PR.

Let's keep the discussion in the Pull Requests and not in this issue, as this issue is about Arabic.

**Comment by abusarimhindi** [comment]
> > I request you to please help me to create this PR.
> 
> Let's keep the discussion in the Pull Requests and not in this issue, as this issue is about Arabic.

OK

**Comment by abusarimhindi** [comment]
> > There is no need to put (.) period, the sentence collector doing wrong
> > This character (.) is not RTL, it is LTR character.
> 
> Can you show me an example of a sentence with a period that would be correct? And this means that generally we could forbid the use of the LTR . ?
> 

I checked some Arabic News websites and found they are using full stop (.) as period, and you know full stop is a LTR character.

مما يستلزم تعليق أعمال التشييد للقيام بإجراء الإصلاحات اللازمة.

See I paste here a sentence, but the period symbol is at starting of the sentence, see the below screenshot. 
![image](https://user-images.githubusercontent.com/22712698/72667262-e191c980-3a3f-11ea-9098-079f46067e05.png)

**Comment by MichaelKohler** [comment]
Thanks!

**Comment by abusarimhindi** [comment]
> Would be great if we could get one, would you be interested in helping with this? :)

Guide me how to write RegEx for Symbol.
Or
I can provide you all the digits, symbols and periods for this language, which should be not allowed in sentence.
