### ISSUE TITLE
Include information about number of sentences still not approved/rejected

### ISSUE THREAD

**Issue by Adrijaned** [Common-Voice/sentence-collector#283]
On the home page of the sentence collector, there is included information about:

* The total amount of sentences in language in the dataset
* The amount of sentences still unreviewed by **you**
* The total amount of validated sentences

One statistic I'm kinda missing in this is the amount of sentences that haven't had yet an approve/reject cast on them, even when you might have already reviewed those sentences.  I could mainly use such statistic to know how many more sentences do I have to add to the sentence collector to maintain a steady review buffer for my language.

**Comment by MichaelKohler** [comment]
All kinds of stats would be useful. But whatever we do, this is basically running into the same issue as https://github.com/Common-Voice/sentence-collector/issues/240

**Comment by MichaelKohler** [comment]
See also https://github.com/Common-Voice/sentence-collector/issues/149 which goes into that direction as well.

**Comment by Adrijaned** [comment]
This is not an issue about the Kinto limit, this is more in the way the retrieved data is processed to display the stuff that is already displayed, to include one additional number. It is also kinda a feature that would be most useful for languages with smaller datasets so far, only as an indicative if whatever enthusiastic maintainer is driving that language should rather push for more people to review sentences, or if he should strive to rather collect more sentences to review.

**Comment by Adrijaned** [comment]
If was thinking along the lines of just include something like 
``` JS
  async getNotDecided(language) {
    const filters = {};
    filters['has_approved'] = false;
    const collection = await this.getCollection(language);
    const result = await collection.listRecords({ filters });
    return result.data;
  }
```
in `/shared/db/collections/sentences-meta.js` and display it in `language-info.jsx` the same way as the other statistics are displayed.

**Comment by MichaelKohler** [comment]
Sure, what I wanted to say with that is that once that number reaches 10k, it will have the same issue.

**Comment by MichaelKohler** [comment]
This is now fixed in the latest version which just got deployed: https://discourse.mozilla.org/t/action-required-new-sentence-collector-infrastructure-and-improvements/68759
