### ISSUE TITLE
Process rejected sentences

### ISSUE THREAD

**Issue by mozillakab** [Common-Voice/sentence-collector#284]
How to process rejected sentences:

1. When loading the rejected sentences view, two buttons  will be shown: "Edit" button and "ok" button for incorrect sentences. So we have to add a tag to these sentences (correct, incorrect).  
2. When clicking on the "ok" button, an inline text box with a Save button will be shown to edit the sentence and save it. (I guess the user won't modify the whole of the sentence)
3. When clicking on the the "ok" button, it will be replaced with the "no" button and the "send" button will be displayed to resubmit the sentence.
4. We can also add a mass "send" button if we want resubmit more than one sentence tagged as "correct".  
5. Show 5 sentences at one (per page).

Sorry for the design.

![2019-12-21 09_21_11-2019-12-21 08_49_30-Common Voice Sentence Collector jpg - Paint](https://user-images.githubusercontent.com/7033740/71305419-001a8b80-23d4-11ea-845c-136ecfaa5234.jpg)

**Comment by Adrijaned** [comment]
Simple python script to retrieve all rejected sentences in language, to be able to work with them at least externally for now if need be:
```python
# /bin/python3

import urllib.request, json

langCode = 'cs'
lastTimeStamp = 0 # timestamp of the date of rejection all retrieved sentences should be newer than

print('\n'.join([x['sentence'] for x in json.loads(urllib.request.urlopen(urllib.request.Request(f"https://kinto.mozvoice.org/v1/buckets/App/collections/Sentences_Meta_{langCode}/records?approved=false")).read().decode('utf-8'))['data'] if int(x['approvalDate']) > lastTimeStamp]))
```

**Comment by mozillakab** [comment]
@Adrijaned Thanks for the script.

**Comment by MichaelKohler** [comment]
Thanks for filing this issue. I've moved the discussion to https://discourse.mozilla.org/t/sentence-collector-open-discussions-input-needed/63925. Let's file a new issue with more detail once we have feedback there and know how to proceed here.
