### ISSUE TITLE
Uploaded Sentences failed for unknown reason

### ISSUE THREAD

**Issue by mozillakab** [Common-Voice/sentence-collector#285]
It was also reproted by some kab contributors. Some sentences are rejected and we don't know why.

![2020-01-03 10_50_29-Common Voice Sentence Collector](https://user-images.githubusercontent.com/7033740/71717101-441b8080-2e17-11ea-8419-cd2e011b28e4.jpg)

Here is the list of the rejected sentences:
    

Ɣezzifeɣ anect n baba.: last modified precondition failed
    Tettak ibdilen.: last modified precondition failed
    Tettubeddal tsedrit mačči d ṭṭbiɛa.: last modified precondition failed
    Aslaɣ ibeddu daxel.: last modified precondition failed
    Tetteflili am ubeckiḍ.: last modified precondition failed
    Terẓiḍ-t.: last modified precondition failed
    Terẓiḍ-tt.: last modified precondition failed
    Terẓam-tt.: last modified precondition failed
    Terẓamt-tt.: last modified precondition failed
    Terẓam-t.: last modified precondition failed
    Yettbeccic tignaw.: last modified precondition failed
    Yettbeccic deg wusu.: last modified precondition failed
    Bu yiles, medden akk yines.: last modified precondition failed
    Yeɣli-d yimi-s d abiba.: last modified precondition failed
    Yemlal wabbu-nneɣ.: last modified precondition failed
    Ay ack-itt!: last modified precondition failed
    Abrid ɣezzif.: last modified precondition failed
    Nekkini d aqbayli.: last modified precondition failed

**Comment by MichaelKohler** [comment]
This indicates that the entry has been modified on the database and therefore the "new" entry is  outdated. I do not see how that would make sense in this scenario as these are new sentences being uploaded.

What happens when you re-upload those again?

**Comment by mozillakab** [comment]
I just tried and got the same message.

May be they were uploaded by other contributors. Some of theses sentences come from the Kabyle oral/spoken popular literature, but not all of them.

I can't check if they were already upoladed since we thousands of waiting sentences on sentence collector. I just checked on CV corpus and I'm sure they are not synchronized yet.

It's better to display the right reason.

**Comment by MichaelKohler** [comment]
I'll check later tonight if those are already uploaded.

> It's better to display the right reason.

There is no real reason apart from what Kinto gives us. There is no way to get more specific than the actual failure code we get back ;)

**Comment by mozillakab** [comment]
I mean a message like: "Sentence already uploaded" :)

**Comment by MichaelKohler** [comment]
I've checked and it doesn't seem those are duplicates. This doesn't happen locally, so it's not a general issue with those sentences. However, this will make it very hard to debug.

> I mean a message like: "Sentence already uploaded" :)

That's what you get if it's actually a duplicate.

**Comment by mozillakab** [comment]
I hope also it's not a general issue for the other locales. For now, the kab team is uploading sentences and the recording is going on.

**Comment by MichaelKohler** [comment]
In the latest version which just got deployed this should not happen again: https://discourse.mozilla.org/t/action-required-new-sentence-collector-infrastructure-and-improvements/68759
