### ISSUE TITLE
Number of validated sentences and not yet synchronized

### ISSUE THREAD

**Issue by mozillakab** [Common-Voice/sentence-collector#286]
We need to know how many sentences that are validated and not yet synchronized to Common Voice.
This KPI shoud be reinitialized to 0 after every synchronization.

I noticed that the kab team is recording quickly, so we need this KPI (stats) to decide how to spend our effort (recording campaigns) on CV or SC.

**Comment by MichaelKohler** [comment]
Once https://github.com/Common-Voice/sentence-collector/issues/241is done, this shouldn't be an issue from our side anymore. However given that sentences are only deploy from time to time on the CV site, there is nothing we can measure here.
