### ISSUE TITLE
Expanding the swipe review tool

### ISSUE THREAD

**Issue by Etua** [common-voice/sentence-collector#292]
As I can see the current swipe review tool does not allow to skip the sentence which can lead to rejecting many sentences if the contributor is unsure or even worse adding bad strings to the base. The other improvement would be adding support for keyboard shortcuts allowing for better workflow on a PC.

**Comment by MichaelKohler** [comment]
Good points! We definitely should allow skipping.

Regarding shortcuts, maybe we could check if the device supports touch and if not fallback to the normal view?

**Comment by Etua** [comment]
Personally I find single-focused UI better for verification tasks rather than lists of 5 or frankly any number greater than 1 as the sentences are checked each on their own and not in conjunction. [Mapillary Verifier tool](https://help.mapillary.com/hc/en-us/articles/115001964171-Verifier-tool) is a good reference on how to do it right: it uses the same responsive UI for mobile and desktop with big buttons suited for touchscreens and support for keyboard allowing for fast checking without tiresome moving of the mouse on PC for the sake of data safety a user may skip a task or go one step back in case of misclick.

**Comment by ftyers** [comment]
I would like to add a massive +1 on the keyboard shortcuts. Most of the time I'm reviewing on my laptop with no external mouse, so reviewing either via swiping or via the next thing is close to RSI-inducing.

**Comment by MichaelKohler** [comment]
Improvements to the Swipe Review Tool have been made, including keyboard shortcuts and skipping. Actually saving the skipped sentences and not showing them anymore will be tracked in https://github.com/common-voice/sentence-collector/issues/421.
