### ISSUE TITLE
Error during importation: "NetworkError when attempting to fetch resource." and "Failed to fetch"

### ISSUE THREAD

**Issue by stefangrotz** [Common-Voice/sentence-collector#297]
Hi there,
there is a weir error happening when I try to import a collection of sentences. It first happened during this live YouTube workshop of a donor, she always got "failed to fetch" when she tried to import sentences:
https://youtu.be/eNkpfnPUq1U?t=16697

She gave me the sentences:
https://docs.google.com/document/d/17S3OLVakp25ortqeGLzgY71yUjwpY82aGqqZb2B1-7g/edit
I deleted a few suspicious signs and tried a few things but I always get the message: "NetworkError" when attempting to fetch resource."

Any idea what's going on here?

**Comment by MichaelKohler** [comment]
Will have a look in an hour

**Comment by d-p-y** [comment]
Hi Michael,
I have exactly the same issue

![image](https://user-images.githubusercontent.com/18470256/73606710-9504cd00-45ad-11ea-8a81-d0f31e6e8723.png)

**Comment by MichaelKohler** [comment]
Yep, seems I screwed something up. This should work again, @stefangrotz @d-p-y can you verify?

**Comment by stefangrotz** [comment]
works again, thanks :)

**Comment by d-p-y** [comment]
It works. Thank you
