### ISSUE TITLE
Fixing typos in Frisian sentence collection

### ISSUE THREAD

**Issue by Fjoerfoks** [Common-Voice/sentence-collector#299]
[mozillaCVkorreksjes.xlsx](https://github.com/Common-Voice/sentence-collector/files/4198859/mozillaCVkorreksjes.xlsx)
As mentioned in [chat](https://matrix.to/#/!WpvTgzNfcLIgzJZdSE:mozilla.org/$aUsMcJw3cZJz3qSpdG2qGLcuGCOruWhiyW3bx6r6VlY?via=mozilla.org), we would like to replace some sentences with typos with corrected sentences, or delete the existing and add new ones.
@MichaelKohler can you handle attached file?
TIA.

**Comment by MichaelKohler** [comment]
@Fjoerfoks Yes, that looks good. I assume the sentences in the first column are the wrong ones?

Once you confirm, we can do the following:

* I delete the incorrect sentences from the Sentence Collector DB and run a new export
* You add the corrected sentences to the Sentence Collector for review again

**Comment by MichaelKohler** [comment]
I have deleted these sentences and created a new export. You can now add the corrected versions to Sentence Collector as you would do with any other new sentence. Thanks for reporting!

Also note that the following 3 sentences could not be found:

```
De reuze-aronskelk sil nei ferwachting moandeitemiddei om in oere of trije begjinne te bloeien.
Gean nei Postvak Yn.
Klik Postvak Yn.
```
