### ISSUE TITLE
Disallow sentences with Mimic unicode characters 

### ISSUE THREAD

**Issue by iveskins** [Common-Voice/sentence-collector#301]
for example "Τаylοr Ѕwіft" looks just like "Taylor Swift", but the first is made of Greek, Cyrillic and Latin characters, not just Latin characters.
Maybe check for homoglyphs like the mimic project makes. 
https://github.com/reinderien/mimic/blob/master/mimic/__init__.py

**Comment by MichaelKohler** [comment]
Thanks for filing this. Best case would probably be if we can share the rules from the [scraper](https://github.com/Common-Voice/common-voice-wiki-scraper/tree/master/src/rules) where we already have a config for forbidden characters as well as one for allowed.

**Comment by iveskins** [comment]
I would add  \u2060 "a zero width non-breaking space" to this list too.
it appears many times in the sentences in https://kinto.mozvoice.org/v1/buckets/App/collections/Sentences_Meta_en/records 
(it can be found like: `fold -w80 mozilla.sentence.collector.20200527.records.json | grep u2060`)

**Comment by MichaelKohler** [comment]
I've created #311 to use the Sentence Extractor rules for the Sentence Collector as well. This would already be included there.
