### ISSUE TITLE
Sentence Counters not working

### ISSUE THREAD

**Issue by MatejMecka** [Common-Voice/sentence-collector#305]
<img width="480" alt="Screen Shot 2020-04-23 at 6 42 54 PM" src="https://user-images.githubusercontent.com/24255804/80125648-3fc7ce80-8592-11ea-8400-ae5791876dbd.png">

<img width="1108" alt="Screen Shot 2020-04-23 at 6 41 43 PM" src="https://user-images.githubusercontent.com/24255804/80125540-173fd480-8592-11ea-8880-ca6dc2d28bb5.png">

Browsers: Firefox 75 on Mac and Chrome 81 on Android

**Comment by MichaelKohler** [comment]
https://kinto.mozvoice.org/v1 seems to be down, will have somebody look into it. Thanks for the report!

**Comment by MichaelKohler** [comment]
Looks like we lost the DNS mapping or domain we rely on. For now I've pointed the calls to the URL, which of course gets blocked as mixed content. But with that we won't suddenly get served with something else in case we indeed did lose the domain.

**Comment by MichaelKohler** [comment]
@bacharakis @mbransn can you check what happened with that domain and why it's not pointing to our server anymore? I'd guess we just lost the domain? If so, I'll need a new domain and the certificate on the server would need to be updated to reflect that.

**Comment by mbransn** [comment]
Thanks for flagging us here @MichaelKohler -- sounds like @phirework is looking into this. More soon.

**Comment by mikehenrty** [comment]
Hi folks, indeed the mozvoice.org domain was registered to my account until yesterday, when it expired.

Just now, I tried to renew it, with the goal of transfering ownership to someone here on the team. Unfortunately, my provider NamesCheap did not allow me to renew since I let it expire. This was the error `2020166-Domain has expired. Please reactivate your domain.`

Looks like to renew now from my account, it will cost $30 USD. Happy to do that and transfer ownership to Mozilla (will need to be re-imbursed of course). Just let me know.

Conversely, maybe it's time to bring this project under a more official Mozilla domain?

**Comment by phirework** [comment]
Thanks for the update @mikehenrty! Can you renew the domain for a year and transfer ownership to me for now (jennyzhang@mozilla.com)? We definitely want to bring it to an official Mozilla domain but I'd prefer to have sentence collector up and running while we do the IT-SRE handover and cert updates.

**Comment by mbransn** [comment]
Thanks @mikehenrty -- +1 to @phirework on renewal & migration plans. Please send the receipt to both of us via email and we'll get the reimbursement sorted. 👍

**Comment by mikehenrty** [comment]
@phirework done! you will need to sign up for Namescheap account with that email if you haven't already. You should have gotten a notification email about this, so let me know if you don't see it.

Will send the receipt the receipt (looks like they waived have the fee).

**Comment by phirework** [comment]
@mikehenrty Done and confirmed that the domain is back up and running! Thanks for your quick response here, really appreciate it.

**Comment by MichaelKohler** [comment]
Thank you everyone, this is now working again for me. This might take a few more hours for everyone to get the new DNS records, but after that everything should be working again.

If you still can't perform any actions by tomorrow this time, please comment here and we'll have another look. Thanks!
