### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by mozillakab** [Common-Voice/sentence-collector#306]
Login failed since yesterday. Same issue reported by kabyle members adding and validating sentences on SC.

Also, we noticed some slowness since some weeks.

![2020-04-24 07_43_30-Common Voice Sentence Collector](https://user-images.githubusercontent.com/7033740/80182718-c9fe4a00-8607-11ea-939a-e8f31ffd30bf.jpg)

**Comment by Adrijaned** [comment]
Same root issue as #305

**Comment by mozillakab** [comment]
thanks, i'll close this one
