### ISSUE TITLE
Feature request: Read cards with text to speech api. 

### ISSUE THREAD

**Issue by iveskins** [Common-Voice/sentence-collector#308]
I was thinking how it would be nice to be able to review sentences while resting my eyes.  This probably wouldn't work for spelling, only for reviewing grammar (maybe check sentences against a dictionary and skip sentences with mismatching words in speaking mode). But given the sheer volume that needs to be reviewed, some alternative to sitting at a keyboard staring at a screen would help make it possible to get reviews done while out walking or the like.

I put together a mockup here (not having used react before its just a hack, but it gives the idea of what it could be like.)
https://github.com/iveskins/sentence-collector/commit/9feadca1809e56c7082a43f7b28a9a287404ce4e

**Comment by MichaelKohler** [comment]
Thanks for filing this. Could you please create a discussion at https://discourse.mozilla.org/c/voice/239 so others can chime in as well? Thanks!
