### ISSUE TITLE
Feature request: Voting via API.

### ISSUE THREAD

**Issue by iveskins** [Common-Voice/sentence-collector#309]
I was playing around with the pending sentence data, and noticed a large amount of sentence in french, or with mangled words. using command line tools one can quickly make a list of sentences that should be rejected. if there was a way to post json to the sentence-collector server with votes included, then a few technical users could vote more efficiently.

**Comment by MichaelKohler** [comment]
I think we should make voting more user friendly on the website itself if needed. If there are general patterns of errors, those should be included in the rules files.
