### ISSUE TITLE
Short sentences flagged as long sentences in Odia

### ISSUE THREAD

**Issue by psubhashish** [Common-Voice/sentence-collector#310]
<img width="1091" alt="Screen Shot 2020-05-28 at 5 31 10 PM" src="https://user-images.githubusercontent.com/1258090/83142987-e4e44280-a10e-11ea-8b29-d45c20fd8d73.png">
As you can see above, a fairly short sentence in [Odia](https://en.wikipedia.org/wiki/Odia_language) is flagged as a long sentence. I see much longer sentences in English. Ideally it should NOT be the number of Unicode characters when it comes to [abugida](https://en.wikipedia.org/wiki/Abugida) scripts but the number of words. Odia, for instance uses multiple characters, marks and [conjunct consonants](https://en.wikipedia.org/wiki/Conjunct_consonant) which would increase the total number of characters even though the sentence would be a short one. Can the higher limit be increased to 10-15 words as a large chunk of data is being discarded otherwise, especially when there is very little Public Domain text content?

Secondly, I see "The Operation Was Aborted" message far too many times even before uploading sentences. It did not allow me to upload several times and I had to save the text locally, switch browsers to finally do it after multiple attempts. Used Firefox 76.0.1 on a MacOS.
<img width="1136" alt="SS2" src="https://user-images.githubusercontent.com/1258090/83143559-c03c9a80-a10f-11ea-9ab7-888c5dfafdd9.png">

**Comment by MichaelKohler** [comment]
There is an open PR with open questions at https://github.com/Common-Voice/sentence-collector/pull/227. That would solve the first part.

> Secondly, I see "The Operation Was Aborted" message far too many times even before uploading sentences. It did not allow me to upload several times and I had to save the text locally, switch browsers to finally do it after multiple attempts. Used Firefox 76.0.1 on a MacOS.

Can you give me more logs (mostly responses from the "Network" tab) for these errors?

**Comment by psubhashish** [comment]
Thanks @MichaelKohler. I have responded on [Discourse](https://discourse.mozilla.org/t/increase-the-number-of-words-limit-for-odia/41713/5?u=psubhashish) to keep the discussion thread less messy. :) So, we don't need to discuss that issue here.

Can you let me know about your response to the 2nd question -- I didn't quite get your ask. Also, I don't have more screenshots and I am not facing the issue after a couple of restarts.

**Comment by MichaelKohler** [comment]
> Can you let me know about your response to the 2nd question -- I didn't quite get your ask. Also, I don't have more screenshots and I am not facing the issue after a couple of restarts.

This could have been a local network issue, or on the server side, or somewhere in between. Hard to say.
