### ISSUE TITLE
Use Sentence Extractor Rules

### ISSUE THREAD

**Issue by MichaelKohler** [common-voice/sentence-collector#311]
We have already defined rules for the Sentence Extractor, for example: https://github.com/Common-Voice/cv-sentence-extractor/blob/master/src/rules/de.toml

We should only need to have one source of truth for validation, so we should use the same rules here. 

What would need to be done here:
* Integrate the toml files into our build
* How do we update the rule files? Regular build deployment? Only on deployments we do anyway?
* Migrate existing rules from here to Sentence Extractor if they don't exist yet there
* How do we handle rules that are currently not in the Sentence Extractor?

**Comment by HarikalarKutusu** [comment]
I'm writing as this came back to triage. I think the following filters would limit our chances.
`
min_word_count = 2
may_end_with_colon = false
needs_uppercase_start = true
`
**Ex-1:**
"Come!" would be rejected

**Ex-2:**
"Afterwards he whispered: can ve please go?"  (think of a longer sentence) can actually divided into two meaningful sentences if there are >14 words.

"Afterwards he whispered:" would be rejected
"can ve please go?" would be rejected

In the related Discourse discussion, people tend to allow these...
https://discourse.mozilla.org/t/discussion-of-new-guidelines-for-uploaded-sentence-validation/37718

I think it is normal to have two different rule sets for automatic extraction from thousand of pages and handpicked manual entry...

**Comment by MichaelKohler** [comment]
Yeah, this would definitely need more discussions. I don't see this happening anytime soon.

**Comment by MichaelKohler** [comment]
I'm closing this for now. We can pick this up later on, but as said before, this would require extensive discussions first.
