### ISSUE TITLE
Unable to contribute with new sentences.

### ISSUE THREAD

**Issue by codracir** [Common-Voice/sentence-collector#313]
I'm trying to contribute with new sentences to the Portuguese language, but when i hit the submit button, i keep getting the message "Please add a source" and the sentences not submitted

I have the Portuguese language selected and the checkbox "I confirm that these sentences are public domain and I have permission to upload them" checked.

By the way. It would be a good idea to have the contribution page translated to the portuguese language.

Best Regards,

Ricardo

**Comment by MichaelKohler** [comment]
Hi Ricardo, thanks for filing this issue.

Have you filled out this field as well? That one is required so we know where the sentences came from exactly. If you wrote the sentences, you can just write "wrote them myself" or a similar source.

![image](https://user-images.githubusercontent.com/330324/87222281-12551a80-c362-11ea-9759-b4888504610a.png)

**Comment by MichaelKohler** [comment]
For the localization there is https://github.com/Common-Voice/sentence-collector/issues/3
