### ISSUE TITLE
randomize sentence order

### ISSUE THREAD

**Issue by flammie** [Common-Voice/sentence-collector#314]
The sentences in Finnish sentence collector seem to be in alphabetical order and contain a large number of very similar sentences, it gets rather boring after 100th page of "Mr president, I think/propose/... blah", it might be more interesting to have them in random order?

**Comment by MichaelKohler** [comment]
We are currently surfacing the sentences with the most votes first. This enables us to get approvals fairly quickly. However this also leads to the case you describe: if somebody uploads an alphabetical list of sentences, and reviewers go through that page by page, the number of votes will still be in that order, so it will again be surfaced in that order.

However maybe we could randomly sort within their respective buckets, so we'd still have the sentences close to approval first, but in a more random order to make it more interesting.

**Comment by MichaelKohler** [comment]
Thanks for filing this issue. I've moved the discussion to https://discourse.mozilla.org/t/sentence-collector-open-discussions-input-needed/63925. Let's file a new issue with more detail once we have feedback there and know how to proceed here.
