### ISSUE TITLE
request to improve ux

### ISSUE THREAD

**Issue by thg303** [Common-Voice/sentence-collector#320]
When I want to add a sentence, I have to select the language each time and click the "confirm" button. it is painful, we need to allow clients to submit as many sentences as they can, and allow them to review it later on.
It would be great to improve the UX. if that's ok I can come up with a PR.

**Comment by MichaelKohler** [comment]
I'm not sure I understand you correctly, can you please elaborate?

It is possible to add multiple sentences, one per line and therefore upload multiple sentences, as the placeholder suggests:

![image](https://user-images.githubusercontent.com/330324/91349020-31095680-e7d4-11ea-817e-2258ddee23c8.png)
