### ISSUE TITLE
delete added sentences

### ISSUE THREAD

**Issue by abtinmo** [Common-Voice/sentence-collector#321]
I added around 1300 sentences to "sentence-collector" for Persian language, then i found out that there is license issue with Wikipedia content . is there any way to remove all of them? or i must reject them one by one manually?

is there any undo or bulk delete ?

**Comment by MichaelKohler** [comment]
I can delete those for you. Can you give me the username and "source" text so I can correctly find those?

**Comment by abtinmo** [comment]
my username is "abtinmo" and i used https://fa.wikipedia.org/ as source.

**Comment by MichaelKohler** [comment]
Thanks for reporting this, I've now deleted all these.
