### ISSUE TITLE
[Question] Data quality guideline - semantically wrong sentence should be Accept or Reject during review?

### ISSUE THREAD

**Issue by bact** [Common-Voice/sentence-collector#322]
If it is obvious that the sentence is semantically wrong, should the user click on "Accept" or "Reject"?

Example from Thai sentence collector:
- "บันไดบนรถดับเพลิงไม่นานพอ" which can be translated back to English as "The ladder on fire engine is no LONG (in temporal length) enough."
- As a native speaker, this sentence is very strange.
- It is very likely that the original sentence is something near to "The ladder on fire engine is no LONG (in spatial length) enough."

Lots of data added recently added for review are from subtitles (foreign language -> Thai language) and I found this kind of mistranslated from time to time.

What is Common Voice guideline for this?

If Accept (included for speech recording), will this affect the application of the data set in the future?

If Reject (excluded from the recording), will this affect the expansion of the data set?

In any case, I recommended to include the decision to the Review guideline. Thanks.

**Comment by bact** [comment]
cc: @wannaphong @heytitle

**Comment by MichaelKohler** [comment]
In general sentences should be easy for people to record, so semantic errors might throw them off. So I'd opt for rejecting wrong sentences.

Would you mind asking these kinds of question over at Discourse in the future? https://discourse.mozilla.org/c/voice/239 . There are more people there and some topics might even already be covered.

**Comment by bact** [comment]
Thank you. Will go to Discord next time.

**Comment by Adrijaned** [comment]
@bact Also, if the data are coming from subtitles, there is quite a big chance that they are not licensed properly and **must** be removed. You know, since subtitles are usually parts of movies, and those are rarely if ever released under CC0 or equivalent. To learn how to check for the sources of the sentences and potentially report them, check the link in sidebar for reporting copyright violations.
