### ISSUE TITLE
Feedback from review sprint event (UI)

### ISSUE THREAD

**Issue by bact** [Common-Voice/sentence-collector#323]
Yesterday (29 Aug 2020), a community in Thailand organized a review sprint for Thai sentences in Common Voice
https://www.facebook.com/events/964192724056470/ (hosted by @cstorm125 et al) 

We managed to pushed up 1,000+ validated sentences from the event.  Here are some feedback about the Sentence Collector platform.

- It takes quite some time to load/reload Review page
- Lots of people in the same event experienced the "sentence lost": they review N sentences and when hit "Finish Review" the UI reports that they had submitted M sentences, where M is a lot smaller than N.
  - Does it possible because of some of them reviewing the same sentences at the same time?
- It will be helpful if the Review Criteria infobox also has information like ones from #322 (semantically wrong sentence) and https://github.com/Common-Voice/sentence-collector/pull/319#discussion_r477544092 (target length in time). As well as suggestions from "Add new sentences" section in https://common-voice.github.io/sentence-collector/#/how-to 

Thanks again to the Common Voice team. I'm very optimistic that we can aim for 9,000 sentences mark within next week :)

**Comment by MichaelKohler** [comment]
The first two issues should we fixed with the changes I'm doing currently. See https://github.com/Common-Voice/sentence-collector/issues/315.

For the last part, can you start a thread on discourse.mozilla.org? I'd like to hear what others think how that dialog should look like before we do anything.

**Comment by MichaelKohler** [comment]
This is now in the latest version which just got deployed: https://discourse.mozilla.org/t/action-required-new-sentence-collector-infrastructure-and-improvements/68759
