### ISSUE TITLE
Issue with Kashmiri language

### ISSUE THREAD

**Issue by ahangarha** [Common-Voice/sentence-collector#331]
Today I checked language list and tried to find if there is any entry for Kashmiri language. I saw this:

![image](https://user-images.githubusercontent.com/11241315/95085526-97b75380-0734-11eb-8727-2adcea144e37.png)

Kashmiri language uses some script similar to Urdu, Persian and Arabic and should be written like کشیر I guess but it is written in Hindi script. If you need, I can ask and share the right text in Kashmiri language and script.

**Comment by MichaelKohler** [comment]
Looks like "ks" on Pontoon (https://pontoon.mozilla.org/ks/) is indeed the Arabic script as well, so we'll most likely end up with the Arabic script in Common Voice as well. Thanks for reporting!

@ahangarha is "كٲشُر" the correct native name for Kashmiri?

**Comment by ahangarha** [comment]
It seems so. It is the same on Kashmiri Language page on wikipedia as well: https://en.wikipedia.org/wiki/Kashmiri_language
