### ISSUE TITLE
Keyboard shortcuts in swipe review mode

### ISSUE THREAD

**Issue by ftyers** [common-voice/sentence-collector#359]
This has been mentioned before, in #131 and in #292, but I think it's worthwhile revisiting given the discomfort that the current interface causes when reviewing 100s or 1000s of sentences. 

The minimal improvement would be to have two keys. They could be arbitrary, e.g. `Y` and `N` or `g` and `b`. In the swipe mode, the user (me) would see a sentence and then press either `Y` or `N` to accept or reject it respectively. 

A greater improvement would be to have four keys. The two keys for accept/reject and in addition a key for "skip" and a key for "back".

**Comment by MichaelKohler** [comment]
Improvements to the Swipe Review Tool have been made, including keyboard shortcuts and skipping. Actually saving the skipped sentences and not showing them anymore will be tracked in https://github.com/common-voice/sentence-collector/issues/421.
