### ISSUE TITLE
Empty sentences if you review before confirming

### ISSUE THREAD

**Issue by nukeador** [Common-Voice/sentence-collector#37]
When you add new sentences you are prompted to review before confirming them, if you do so you will end up with a list of empty sentences to review: 

![imagen](https://user-images.githubusercontent.com/531906/50589690-ecef7280-0e87-11e9-8c03-2aae61c43db3.png)
![imagen](https://user-images.githubusercontent.com/531906/50589701-f24cbd00-0e87-11e9-8b59-9af6856396ab.png)

What's the purpose of asking to review when you haven't confirmed yet?

**Comment by MichaelKohler** [comment]
Oh, I've seen that bug with the "fix" button as well, which I have removed for now due to that exact problem. Somehow doesn't surprise me that happens with the "Review" link as well.

I wonder if it even makes sense to review own sentences? Should that then be counted towards the 2/3 approvals? IMHO no.

**Comment by nukeador** [comment]
Some people might send sentences from other sources, so they are not their own. It would be fair for them to review them.

**Comment by MichaelKohler** [comment]
If we add this, we also need to make sure that there is a way back to finally submitting the sentences after reviewing as mentioned in #41

**Comment by nukeador** [comment]
Ideally both final screens for add or review workflows should suggest to add more sentences or review more sentences, so people will always have a next step.

**Comment by danielsjf** [comment]
I think the review option should only show up after confirming. If I click review there, my sentences aren't added.

**Comment by nukeador** [comment]
@MichaelKohler I see review is still offered but now I can see the sentences, is this intentional?

**Comment by MichaelKohler** [comment]
Yes, I've intentionally fixed this :)
