### ISSUE TITLE
Typo in profile if no sentences submitted yet

### ISSUE THREAD

**Issue by MichaelKohler** [Common-Voice/sentence-collector#38]
"No sentences submitted or validated, Try reviewing some sentences now?"

--> should be "try"

@nukeador though I wonder what that even means. Do we want people to review first when they start? Or should we advertise adding new sentences here?

<img width="743" alt="screenshot 2019-01-02 at 12 38 03" src="https://user-images.githubusercontent.com/330324/50590433-43aa7b80-0e8b-11e9-96ff-ebdf9a055b0f.png">

**Comment by nukeador** [comment]
If there are no sentences we should encourage to submit new ones.

If there are some sentences we should encourage add new ones or review existing, probably emphasis on review if there are still unapproved ones.

**Comment by nukeador** [comment]
And in this case, if you haven't added your language we should encourage adding a language first.

**Comment by MichaelKohler** [comment]
Oh, yes. So we only want to show "No sentences submitted or validated, try reviewing some sentences now?" when there is a language added already. Otherwise we shouldn't show anything so the user sees that there is no language added it (next paragraph). Possibly also rephrasing that to "You have not added any language yet. Please do so below."

**Comment by nukeador** [comment]
+1
