### ISSUE TITLE
No footer

### ISSUE THREAD

**Issue by nukeador** [Common-Voice/sentence-collector#39]
Footer is currently displaying "Footer".

Let's use the same footer we have at https://voice.mozilla.org

**Comment by MichaelKohler** [comment]
Would you agree that we can take the footer without the "sharing" part? That might get a bit more complicated otherwise.

**Comment by MichaelKohler** [comment]
To keep design efforts lean, I've added the links to the sidebar and remove the "Footer" line. We will be doing design at a later stage anyway.
