### ISSUE TITLE
Changing kurdish(kurdî) to central kurdish(sorani) or kurdish(sorani)

### ISSUE THREAD

**Issue by jwtiyar** [common-voice/sentence-collector#391]
Hey
In profile page we have kurdish(kurdî) It is the main language and there is two main dialects of kurdish which are Central Kurdish(Sorani) and Northern Kurdish(kurmanci)
To understand the name:
Central Kurdish = Sorani 
Northern Kurdish = Kurmanci
Their code:
Kmr = Northern Kurdish
Ckb = Central Kurdish

The best option is to use Central Kurdish for kurdish(kurdî) And using Northern Kurdish for kurdish(kurmanci).

Best Regards.

**Comment by MichaelKohler** [comment]
Taking your feedback and what Pontoon has, I'd suggest the following:

| Code    | Name    | Native Name | Name in Pontoon | New Name | New Native Name
| :------------- | :---------- | :-----------|:----------- |:----------| ----------- |
| ckb | Kurdish | Kurdî | Central Kurdish | Central Kurdish | سۆرانی (taken from Wikipedia, and double checked script indeed is Arabic in Pontoon)
| kmr | Kurmanji | Kurmancî‎ | Kurmanji Kurdish | Kurmanji Kurdish | kurmanci

Does that make sense?

**Comment by MichaelKohler** [comment]
also cc @ftyers

**Comment by ftyers** [comment]
Actually, we had just this confusion a couple of days ago when meeting with `kmr` contributors. The native name *Kurdî* in Latin script is ambiguous between `ckb` and `kmr`. 

I think that potentially the easiest and less divisive way around this is to make the native name of `ckb` in the Perso-Arabic script and the native name of `kmr` in the Latin script. For example:

ckb = Central Kurdish = کوردی 
kmr = Kurmanji Kurdish = Kurmancî (Kurdî)

Note that what you wrote, *سۆرانی* corresponds to *Soranî* in Latin script and @jwtiyar has a preference against that naming.

I'm also tagging @sinaahmadi as he may have some thoughts on the matter.

**Comment by sinaahmadi** [comment]
Thanks for raising this issue @jwtiyar. I also noticed this and second @ftyers's suggestion.

**Comment by jwtiyar** [comment]
> Taking your feedback and what Pontoon has, I'd suggest the following:
> 
> | Code    | Name    | Native Name | Name in Pontoon | New Name | New Native Name
> | :------------- | :---------- | :-----------|:----------- |:----------| ----------- |
> | ckb | Kurdish | Kurdî | Central Kurdish | Central Kurdish | سۆرانی (taken from Wikipedia, and double checked script indeed is Arabic in Pontoon)
> | kmr | Kurmanji | Kurmancî‎ | Kurmanji Kurdish | Kurmanji Kurdish | kurmanci
> 
> Does that make sense?
> 
> 

No this wrong bro 
Pontoon calls it central kurdish. 
Kurdish is both kurmanci and sorani
ckb = sorani = central kurdish 
Kmr = kurmanci = northern kurdish

**Comment by jwtiyar** [comment]
Thank you michael
Every thing is ok.
