### ISSUE TITLE
add yue (cantonese)

### ISSUE THREAD

**Issue by irvin** [common-voice/sentence-collector#396]
Hi, reference to the discussion here (https://github.com/mozilla/common-voice/issues/2926) and the following discourse thread, please add Cantonese (yue) to sentence-collector as a new language.
https://discourse.mozilla.org/t/requesting-the-cantonese-language-yue/69928

**Comment by irvin** [comment]
@MichaelKohler does it been deployed to the live site? Didn't find it at the add language dropdown list.

**Comment by MichaelKohler** [comment]
@irvin retriggered the deployment, it should now show up. I thought I had verified it with the last deployment, but this makes me fairly unsure now..

**Comment by irvin** [comment]
@MichaelKohler I also remember that I had check it after the issue closed. weird.
