### ISSUE TITLE
Statistics not updating

### ISSUE THREAD

**Issue by ibelarouci** [common-voice/sentence-collector#398]
the content of my Statistics page and he is never be updated!!
Last Update: never 
I dont why?
if i persist to refresh this page it redirect me to this page
https://commonvoice.mozilla.org/sentence-collector/callback?code=iiXQTXaMnCZihib2
502 Bad Gateway
nginx/1.17.8

**Comment by MichaelKohler** [comment]
Is this still the case? My initial guess would be that this was during a deployment I just did. Can you try again?

**Comment by ibelarouci** [comment]
Yes, the problem still persists, my stats page is unrespond to showing me info and even my profile with 
0 added by you
of which 0 got validated 
but i add a lot of sentences
my account **i.belarouci@gmail.com**

**Comment by MichaelKohler** [comment]
I would only expect you to be redirected to that page right after login. Does the redirect still happen or is it now just not updating the stats? Do you see "Loading.." at the top of the stats page?

Adding and reviewing sentences works? Which languages did you add to your profile?

**Comment by ibelarouci** [comment]
Well adding and reviewing sentences works perfectly, I see the word being updating ... on the stats page after a moment it disappears but nothing happens, my profile (i.belarouci@gmail.com)  is assigned to Arabic language
I  contribute normally  to the project, I've added about a million sentences  , and I would sometimes like to take a look at the stats page.

**Comment by MichaelKohler** [comment]
Thanks for the info, I'll have a closer look.

**Comment by mozillakab** [comment]
The bug is still happening.
Scenario:
1- Go to stats page and wait for some seconds
2- Reload the page

![2020-12-19 20_09_48-502 Bad Gateway](https://user-images.githubusercontent.com/7033740/102697755-7bf22280-4238-11eb-8ada-d9dd85e8ccdb.jpg)

**Comment by MichaelKohler** [comment]
@ibelarouci Can you try this again? The statistics should now update again. It will still take some time as there are 1.8 million sentences, but it should not timeout anymore.

For the 502 error, I unfortunately can't reproduce this.
