### ISSUE TITLE
Questions about the sentence collecting guidelines

### ISSUE THREAD

**Issue by laubonghaudoi** [common-voice/sentence-collector#399]
This is @laubonghaudoi from @CanCLID. Mozilla [just opened](https://github.com/mozilla/common-voice/issues/2926#issuecomment-748120993) a new `yue` locale(Cantonese) and we are adding new sentences to it. However, we have some confusions about the guideline. According to the [How to](https://commonvoice.mozilla.org/sentence-collector/#/how-to), new sentences should be:
> - Foreign letters. Letters must be valid in the language being spoken. For example, “ж” is a letter in the Russian alphabet but is never used in English and so should never appear in any English source text.
> - Length. Sentences must be 14 words or less.

And our questions are:
1. Hong Kong Cantonese has a lot of English loan words. It is inevitable to include sentences written in mixed-Chinese characters and English letters, unless we purge these sentences and remain those with pure Chinese characters. But this will significantly diminish the size of collection. So is it okay to add mixed-code sentences?
2. East Asian languages do not have spaces in written texts, so sentences can't not be measured with the unit of "word", only "character". But if sentences are limited to only 14 characters or less, we can hardly include any meaningful sentences. So is there another criterion for measuring the lengths of East Asian texts?

**Comment by MichaelKohler** [comment]
Hi, thanks for filing this. It would be better though to open this discussion over at https://discourse.mozilla.org/c/voice/239. There is way more exposure over there than in the repository here.

**Comment by laubonghaudoi** [comment]
> Hi, thanks for filing this. It would be better though to open this discussion over at https://discourse.mozilla.org/c/voice/239. There is way more exposure over there than in the repository here.

Thanks for reminding! I have posted this issue [here](https://discourse.mozilla.org/t/questions-about-the-sentence-collecting-guidelines-for-cantonese-yue/72411)

**Comment by mozillakab** [comment]
The bug is still hapenning.
Scenario:
1- Go to stats page and wait for some senconds
2- Reload the page

![Uploading 2020-12-19 20_09_48-502 Bad Gateway.jpg…]()
