### ISSUE TITLE
Guarani: Please remove all sentences that are not approved

### ISSUE THREAD

**Issue by ftyers** [common-voice/sentence-collector#400]
Language code `gn`. Eg. everything that isn't in https://github.com/mozilla/common-voice/blob/main/server/data/gn/sentence-collector.txt

There are a lot of sentences that have to be discarded because of typos, so we'll just fix the typos and verify the sentences externally, and then I'll reimport them and verify them in SC myself.

**Comment by MichaelKohler** [comment]
I can't promise I'll get around to this soon, but I'll tell you once the PR for it is open, so you can verify again that there are no new sentences not yet approved that would be deleted through that.
