### ISSUE TITLE
On mobile device, popups hide the control buttons

### ISSUE THREAD

**Issue by drzraf** [common-voice/sentence-collector#408]
On Firefox (Mobile), after I collect 5 sentences, the popup all stay over the screen after any button is pressed resulting in button being hidden (but still clickable) :

![Screenshot_20201229-142350](https://user-images.githubusercontent.com/1169926/103302187-ca928000-49e1-11eb-9155-85047ecac118.jpg)

This the UI very error-prone for inexperienced users.

**Comment by MichaelKohler** [comment]
Thanks for filing this issue. Unfortunately I don't seem to be able to transfer it to the correct repository. This should live over at https://github.com/mozilla/common-voice/issues. @drzraf would you mind filing it there? If not, I'll figure out how to transfer it.. thanks!

**Comment by drzraf** [comment]
https://github.com/mozilla/common-voice/issues/2977

**Comment by MichaelKohler** [comment]
Thanks!
