### ISSUE TITLE
Norwegian listed three times

### ISSUE THREAD

**Issue by ftyers** [common-voice/sentence-collector#409]
I went to try and add or review some sentences for Norwegian, but am presented with three options:

![photo5215263511066816607](https://user-images.githubusercontent.com/449545/105567475-0a6f2d80-5d2a-11eb-963a-767956f5e39d.jpg)

There should be 1-2 options, either just 
* *Norsk* (`no-NO`, `nor-NO`) or
* *Norsk nynorsk* (`nn-NO`, `nno-NO`) and *Norsk bokmål* (`nb-NO`, `nob-NO`). 

Note that neither *Norsk nynorsk* nor *Norsk bokmål* are spoken languages, they are written standards.

**Comment by MichaelKohler** [comment]
Common Voice knows about `nn-NO` and `nb-NO`. Both of these also have sentences in the Sentence Collector. `Norwegian (Norsk)` does not have any sentences, and also would never be exported.

So I suggest the following if that makes sense from a language point of view:

* Remove "Norwegian (Norsk)"
* Check why `nn-NO` doesn't get exported
* Fix the names. What should the names in that dropdown be for each of those? Right now it seems fairly confusing which is which?

@ftyers does that make sense?

**Comment by ftyers** [comment]
Those look good. The names should be:
* Norsk nynorsk (nn-NO, nno-NO) -- or just Nynorsk, and 
* Norsk bokmål (nb-NO, nob-NO) -- or just Bokmål.

**Comment by MichaelKohler** [comment]
This is more of a mess than I initially thought:

```
133 | Object { id: "no", name: "Norwegian", nativeName: "Norsk" }
134 | Object { id: "nb", name: "Norwegian Bokmål", nativeName: "Norsk bokmål" }
135 | Object { id: "nb-NO", name: "Norwegian Bokmål", nativeName: "Bokmål" }
```

@ftyers would you mind checking whether both "Norsk bokmål" and "Bokmål" should be consolidated into `nb-NO` before we continue by having a look at the sentences in the review queue? If not, which one would correspond to `nn-NO`?

**Comment by ftyers** [comment]
So, `nb` and `nb-NO` can be consolidated. If you give me a link to the `no`, I'll eyeball them and see what is there.

**Comment by MichaelKohler** [comment]
Thanks for the response.

> If you give me a link to the no, I'll eyeball them and see what is there.

`no` is empty, so that's fine.

So I'll do the following:

* consolidate `nb` and `nb-NO` into `nb-NO` - Norwegian (Norsk bokmål)
* Remove `no` completely
* Add `nn-NO` as that already exists on Pontoon - Norwegian (Norsk nynorsk)
