### ISSUE TITLE
Add page. Bug when clicking on the "Review" link after add sentences

### ISSUE THREAD

**Issue by Txopi** [Common-Voice/sentence-collector#41]
After adding sentences, the interface ask for confirmation. The text gives information about how many of the sentences have been added and shows a link called "Review" to review the sentences. But, we are in the confirmation page, we can review sentences without confirm its adding?

If I push the "Confirm" button the sentences are added and I can review them. If I click on the "Review" link of the page (not in the menu, in the add page content), I go to a strange page; inside the Add page I see the Review page's content, with the paginator, but **all the sentences look empty**!

In that point, I lost the sentences I just (almost) added, because I can't Confirm them and if I use the "Review" option in the menu, I will not find them for revision.

I propose just to remove the "Review" link in the sentences add confirmation page. The steps are clear: 1) Add, 2) Review. For me it isn't good to offer reviewing sentences before confirming to add them.

**Comment by MichaelKohler** [comment]
Thanks for filing this issue, there is already a discussion happening about this in https://github.com/Common-Voice/sentence-collector/issues/37 . Therefore I'm closing this as duplicate. Thanks for all your testing!
