### ISSUE TITLE
Sentence collector statistics not updating 

### ISSUE THREAD

**Issue by jwtiyar** [common-voice/sentence-collector#412]
hey 
I already made some review for central Kurdish in sentence collector but it won't get updated, I did rejected sentence and add new ones, But statistics still shows old data. Anything wrong with it?

**Comment by MichaelKohler** [comment]
The statistics only get updated every 6 hours. You can see the "Last updated" timestamp at the top of the page. Given that you filed this issue about 6 hours ago, can you retry now and see if it updates?

**Comment by jwtiyar** [comment]
> The statistics only get updated every 6 hours. You can see the "Last updated" timestamp at the top of the page. Given that you filed this issue about 6 hours ago, can you retry now and see if it updates?

Thank you dear Michael sentence added is updated, But rejected ones not show up still 0, even i did some review on previous days and today also.

**Comment by jwtiyar** [comment]
And i did review new sentences but validated sentences nit changed, How validated sentences will be updated?

**Comment by MichaelKohler** [comment]
Sentences are only marked as validated/rejected once enough reviews are done. The result is calculated based on 2 out of 3 votes:

* 2 times rejected -> marked as rejected as another vote won't change the result
* 2 times approved -> marked as approved as another vote won't change the result
* 1 time approved, 1 time rejected -> no result yet as the 3rd vote will decide

So any sentence to be marked as validated/rejected needs at least 2 reviews. Does that explanation make sense?

**Comment by jwtiyar** [comment]
Thank you very much. got it.
