### ISSUE TITLE
Login page. Keep clear the sign up and sign in operations

### ISSUE THREAD

**Issue by Txopi** [Common-Voice/sentence-collector#42]
I didn't know how to login to do this tests. I used my e-mail as username (it seems "@" is a wrong character but the error messages really doesn't help to understand what's happening) and didn't know which password should I use: Pontoons one? Github's one?

It was my first login so it was supposed that I was creating a new user (register, sign up), not really authenticating. So, to avoid this misunderstood probably many people will have, I propose the following:

1) **Separate the sign up and sign in operations with two links** (of course, you can implement them with the same page with a parameter or something like that). This way, the user will get an error when login with a not existing user, and when trying to register with an already existing user.

2) If that's a lot of work for now, at least, add a note in the login page saying something like this: **If this is you first login, a new user will be created so please, choose you password for the Sentence Collector.**

**Comment by MichaelKohler** [comment]
The rejection is due to characters used that are not allowed, I would say. We should add a note for that.

**Comment by nukeador** [comment]
We decided to keep the login as it was, so yes, let's add a note explaining the behavior.
