### ISSUE TITLE
Profile data not updated without going to Statistics page

### ISSUE THREAD

**Issue by MichaelKohler** [common-voice/sentence-collector#423]
If a user doesn't visit the statistics page, we never download the stats and therefore the numbers on the profile section will always show 0.

Notes:
* We can use the same endpoint/logic as for the statistics
* However we need to make sure that we don't query too often, every 6 hours maximum (same as stats)

Initially reported here: https://discourse.mozilla.org/t/contributions-not-being-reflected-after-contributing-sentences/77497

**Comment by bact** [comment]
Currently, you will have to go to the page, wait for a bit, and the stats will get updated on the page dynamically
(but I think the refetch of new data is now limited to once or twice a day).

For a user who get used to it, I think it's fine (and I personally like it this way, concerning the impact to system performance).

For a new user, this might be an issue as it doesn't provide a straight forward feedback loop and may affect their willingness to continue the contribution.

**Comment by MichaelKohler** [comment]
With #149 the architecture would need to change a bit to optimise database load, which we then also can leverage for the stats page. Until then I'd rather leave the stats page as it is while improving the experience on the profile page. But there will be waiting times.
