### ISSUE TITLE
Is there a way to mass-clean a language overrun by trolls or religious far-from-neutral texts?

### ISSUE THREAD

**Issue by int-ua** [common-voice/sentence-collector#425]
Ukrainian language right now is overrun with texts from a couple of (halfway to swastika-level harmful) pagan religious texts. Whether it was done by russian trolls or someone real, it has to be cleaned up in bulk. What can we do about it?

Also there are a lot of single words and that is not supposed to happen, right?

**Comment by MichaelKohler** [comment]
Yes, there is a way for mass cleanups. What we need to know though is the source, which is shown in the review page per card. This let's us easily identify them and making sure we're deleting the correct ones.

For the single words I'm not sure if we ever discussed this. @ftyers what do you think of that in terms of helpfulness/harm for the models?

**Comment by MichaelKohler** [comment]
> For the single words I'm not sure if we ever discussed this. @ftyers what do you think of that in terms of helpfulness/harm for the models?

As per https://discourse.mozilla.org/t/need-help-with-batch-deleting-300k-in-sentence-collector-inappropriate-samples/78493 it's basically a dictionary, which seems useless.

**Comment by ftyers** [comment]
Single words can be useful, especially if they are frequent like interjections "Yes", "No" or interrogatives "What?" "Who?" or numerals (e.g. the 0...9 of the target segments corpus). 

It won't cause a problem for the model unless they are the majority of entries and recordings. I think that incorporating whole dictionaries is a terrible idea. If any single-words are incorporated they should be done by frequency and ideally things that are typically said as either responses to questions or questions themselves.

**Comment by MichaelKohler** [comment]
> What we need to know though is the source, which is shown in the review page per card. This let's us easily identify them and making sure we're deleting the correct ones.

@int-ua have you seen this?

**Comment by int-ua** [comment]
Thank you! I'll try to find some time to investigate further tomorrow.

**Comment by int-ua** [comment]
Someone is just uploading whole books split automatically, with some "sentences" being one word of one letter and a comma. How can I verify if they asked the authors for permissions to publish under PD0? I doubt that they did. Right now the whole queue in Ukrainian [review](https://commonvoice.mozilla.org/sentence-collector/#/review) is just one book.

**Comment by int-ua** [comment]
Additional discussion is at https://discourse.mozilla.org/t/topic/72154

**Comment by MichaelKohler** [comment]
> How can I verify if they asked the authors for permissions to publish under PD0?

I don't think you can. I will remove it tomorrow.

**Comment by int-ua** [comment]
Where can I download English sentences to start translating and submitting them? The https://kinto.mozvoice.org/v1/buckets/App/collections/Sentences_Meta_en/records is not available for some reason. Sorry, I didn't have time to read all the docs of the project yet and wanted to just dictate and review.

**Comment by int-ua** [comment]
Reading [SENTENCES.md](https://github.com/common-voice/common-voice/blob/main/docs/SENTENCES.md), do I understand correctly that I can make a PR with modifications to https://github.com/common-voice/common-voice/blob/main/server/data/uk/sentence-collector.txt ?

**Comment by MichaelKohler** [comment]
> Where can I download English sentences to start translating and submitting them? The https://kinto.mozvoice.org/v1/buckets/App/collections/Sentences_Meta_en/records is not available for some reason. Sorry, I didn't have time to read all the docs of the project yet and wanted to just speak and review.

Easiest way is to look at https://github.com/common-voice/common-voice/tree/main/server/data/en. However I would suggest translating sentences only as a last chance. You need a lot of sentences, so finding existing public domain sentences might be better worth your time.

> I think this can be closed after a link to the English dataset is found.

Let's not close this until I have deleted the sentences in the queue.

> Reading SENTENCES.md, do I understand correctly that I can make a PR with modifications to https://github.com/common-voice/common-voice/blob/main/server/data/uk/sentence-collector.txt ?

No, you can only do a PR if it is *not* sentence-collector.txt.

**Comment by int-ua** [comment]
Should I fix sentences with errors or should I remove them?
