### ISSUE TITLE
Add page. Explain when possible why each sentence has been rejected.

### ISSUE THREAD

**Issue by Txopi** [Common-Voice/sentence-collector#43]
I added 60 sentences in Basque language and this one has been rejected: "Amerikar Estatu Batuak AEB bezala laburtzen dira." (it means something like "United States of America is shorted as USA.")

They are too many uppercase words? The problem is with the acronym? Too many words? The interface give no explanation so I don't know how to reformulate the sentence.

I understand that some regular expressions used in the source code don't have an easy explanation, but other do have (or should have). I think it deserves to make an effort and try to give a reason (at least one) why each sentence has been rejected:
- More than 10 words are not allowed
- Acronyms are not allowed
- ...

NOTE: while adding the sentences, the "Confirm" button should be disabled and the interface should say what's happening, because if they are many sentences or the server is busy, this process can take long (and users tend to click and double click all the buttons if you don't give feedback all the time...) .

**Comment by MichaelKohler** [comment]
Do you think it would help for now if we linked to https://common-voice.github.io/sentence-collector/#/how-to ?

Longer term, giving exact reasons sounds reasonable.

**Comment by nukeador** [comment]
Let's include a link to that page in a way it doesn't take a lot of space or distracts the workflow.

**Comment by Txopi** [comment]
For the moment, it would help to link that page, but giving the exact reason next to each sentence would be really helpful for many users.

NOTE: I saw that filtered sentences are added anyway (like the one in the example above). That's what we want? That's not a list of errors, just a list of warnings?

**Comment by MichaelKohler** [comment]
I've created a PR to add the link to the rejection list. 

> NOTE: I saw that filtered sentences are added anyway (like the one in the example above). That's what we want? That's not a list of errors, just a list of warnings?

Oh no, this is a huge bug. I've filed an issue to track this: https://github.com/Common-Voice/sentence-collector/issues/51
