### ISSUE TITLE
Request to remove sentences with invalid characters [th]

### ISSUE THREAD

**Issue by bact** [common-voice/sentence-collector#430]
Lots of sentences with invalid characters/patterns were added to the Sentence Collector before the implementation of Thai validation filter. This effectively takes a lot of time for reviewers to remove them.

If possible, I would like to request to delete sentences that contain any of the following characters from the review queue:
- <s>Digits [0-9]</s>
- Latin alphabets [A-Za-z]
- Thai Digits [\u0e50-\u0e59]
- Thai Mai Yamok [\u0e46]
- Thai Paiyannoi [\u0e2f]

and also any sentence that is longer than 80 characters.

This will helping the ongoing sentence review process. Thank you.

(continuing discussion from a closed PR #426)

**Comment by MichaelKohler** [comment]
Thanks for filing a new issue for this. Definitely makes it easier to keep track. I will have a look at this within the next few days.

Do you really have sentences with 0-9 digits in them? Even before there was a Thai validation specifically, the English (fallback) validation should not have allowed those.. If that's the case, I'll need to further investigate why that happened.

**Comment by bact** [comment]
Sorry, may be that's the case. Currently, I personally haven't seen any 0-9 digits, only ๐-๙ Thai digits.

**Comment by MichaelKohler** [comment]
This is now done.

**Comment by bact** [comment]
Thank you.
