### ISSUE TITLE
Long source text wrapped and overflown to a text box below, make the next sentence in review unreadable

### ISSUE THREAD

**Issue by bact** [common-voice/sentence-collector#432]
In Review Sentence mode, when source text is longer than the text box, it will be overflown to the box below, rendering the text below to be unreadable or difficult to spot for misspellings.

Example,
![175717634_10157742009557595_8880919367482120462_n](https://user-images.githubusercontent.com/128572/115339917-f2476700-a1cf-11eb-8b2e-4a6728717028.jpg)
(from https://www.facebook.com/groups/527601721545161/permalink/546417532996913?comment_id=546422779663055 )

## Possible solutions

Possible solution | Pros | Cons
--|--|--
1 Expand the box (horizontally/vertically) to accommodate the source text  | Can see full source text | May have to (horizontally/vertically) scroll the review screen a lot. Can make the content text difficult to read
2 Truncate the source text | Compact review screen | Can't see full source text
3 Truncated source text with link | Compact review screen, can see full source text (when clicked) | Can be a distraction
4 Smaller font for source text | May help a little without changing much | Not solve all the cases
5 Let the source text overflown the box horizontally | Same layout, no change | Can't see full source text

**Comment by darigovresearch** [comment]
Would prefer options 1 or 3 if either are possible. It is more distracting having the text as it is currently than the proposed solutions especially when you are trying to do many sentence verifications

**Comment by MichaelKohler** [comment]
The new Swipe Review Tool has somewhat been optimized for this. Could in theory still happen there, but certainly less often. I've created https://discourse.mozilla.org/t/sentence-collector-deprecating-normal-review-tool-in-favor-of-swipe-review-tool/82235/2 to deprecate this "old" review form.

**Comment by MichaelKohler** [comment]
The Swiping Review Tool is now the default (and only) review tool. I've also made a minor fix to it for the overlap.
