### ISSUE TITLE
[BUG] Source when reviewing sentences overlaps

### ISSUE THREAD

**Issue by darigovresearch** [common-voice/sentence-collector#435]
Often when reviewing the sentences on a mobile the source ends up wrapping over the next sentence in the list.

Is there any way re can resolve this?

**Comment by MichaelKohler** [comment]
Thanks for reporting this. It sounds very similar to #432. I'm closing this as a duplicate, but feel free to reopen it in case it's not the same issue. Thanks again!

**Comment by darigovresearch** [comment]
Yes indeed it is a duplicate, thanks @MichaelKohler for pointing it out and taking a look at the issue!
