### ISSUE TITLE
Improve wording for validation errors

### ISSUE THREAD

**Issue by mishari** [common-voice/sentence-collector#436]
The following sentence is rejected as multiple sentences:
"พื้นท่ีที่มีความได้เปรียบเชิงที่ตั้ง"
<img width="353" alt="image" src="https://user-images.githubusercontent.com/503018/117404499-3a86b900-af34-11eb-8b27-2d337b8cae7c.png">

This should be just one sentence

cc @bact in case you know anything about this.

**Comment by mishari** [comment]
This seems to be related to the word "ที่" when removed or not in the middle of the sentence, it seems to work. The word "ใน" also seems to trigger this.

**Comment by mishari** [comment]
I think I've figured it out, it's not an issue with multiple sentences, but rather an invalid sequence of characters. Is there to fix this in pre or post processing? The sentence is valid, it's just the order needs to be switched.

**Comment by MichaelKohler** [comment]
Thanks for jumping in here. Let's keep this issue open to figure out if we can improve the wording depending on the language.

**Comment by mishari** [comment]
If I may suggest, knowing very little about Javascript, to make this check a series of pairs in an array?
for example
```
STRUCTURE_REGEXES = [
{ regex: "Someregex1",
  error: "Corresponding error
},
{ regex: "Someregex2",
  error: "Corresponding error2"
}
]
```

From what I can tell, this would require minimal code change.

**Comment by MichaelKohler** [comment]
Thanks for the suggestion. Such an approach paired with possibly getting rid of the different groups to make it more flexible might be good indeed. Needs a bit more investigation to not only fix it for this, but also make it as flexible as possible without investing hours and hours into it :)

Performance should be fine in either case, but needs to be validated.

**Comment by MichaelKohler** [comment]
I've changed how rules are defined using the approach suggested by @mishari . @bact feel free to have a look at the new rules file and adjust the error messages as desired :)
I will deploy this later today, so might not be live in the next few minutes..

**Comment by bact** [comment]
Thanks a lot. This is impressive and help a lot in UX for users - also for debugging.
