### ISSUE TITLE
Review page. Substitute Skip, Yes and No buttons.

### ISSUE THREAD

**Issue by Txopi** [Common-Voice/sentence-collector#44]
They are too many boxes in the review page. I think it't not necessary to put each sentence inside a box, because they are a lot of boxes around the sentences.

What's the difference between click on Skip and then Submit or directly Submit? I understand there isn't. So you can remove the Skip option or at least activate Skip by default when loading the page. This way, the user will know what will happen after pushing Submit button (nothing!).

Yes and No labels could be clearer. I think Correct and Wrong labels will work better.

Instead of buttons in both sides of the sentence, why not put **all in the right side as radiobuttons**?
- **Skip** <-- _default option_
- **Wrong**
- **Correct**

**ENHANCEMENT:** like other management systems (for example translation management interfaces), I think the best way to manage the review is adding one more stated: Not sure, Need to evaluate later/by other one. This is a bigger change and also means to add an option inside the Review page or so to view only the problematic sentences.

In fact, it would be great to have this tabs of filters in the Review page:
- Pending (105) <-- _default tab_
- Need evaluation (12)
- Wrong (40)
- Correct (1.103)

**Comment by MichaelKohler** [comment]
Marking this as question, so we can look at this at a later point. As far as I know there is also somebody working on a more elaborate UX workflow and design for a future version. @nukeador can say if I've understood that right or not. Either case, let's keep this around.

**Comment by nukeador** [comment]
Ideally in the future we will have a more polished UX, for this version let's make sure we don't include things that can confuse people, meaning: Let's just do small changes here:

- I agree, the skip button is redundant (I think by default if you don't choose an option you are skipping) so let's hide/remove it (and make sure that if you click again on approve or reject it is deselected)
- Let's use a :+1: and :-1: instead of words and add a tooltip explaining (Approve, Reject)
- Also let's clean up redundant titles and strong borders.



![screenshot_2019-01-02 sentence collector](https://user-images.githubusercontent.com/531906/50603946-a6b50600-0ebd-11e9-8a19-e313d0175fc7.png)

**Comment by nukeador** [comment]
I've also noticed the skip button is not working correctly, if on the 3 sentences you click:

Yes on the first one
No on the second one
Skip on the first one
Yes on the third one

Then the first one will go to yes again even if the last action was skip. So I'm i favor of removing it and just skip by default and click again deselect option.

**Comment by Txopi** [comment]
Look clear and useful. Don't forget to allow the user to click again in the Approve and Reject button so the sentence returns to the initial state (Skip). If not, if I click some hands in different sentences and I change my opinion with one sentence, I'll be in a trouble when I push the Confirm button.

I personally would show more than just 3 sentences per page. Perhaps 5? 10?

**Comment by MichaelKohler** [comment]
I agree regarding the boxes and the skip button. However, I'm disagreeing with the 👍 👎  emojis. The meaning of hand gestures heavily depends on where you come from, ranging from what we actually want to mean here to being insulting. Let's avoid that. Would "Approve" / "Reject" make more sense?

**Comment by MichaelKohler** [comment]
The box itself is already fixed in my other PR: https://github.com/Common-Voice/sentence-collector/pull/48/files

**Comment by nukeador** [comment]
@MichaelKohler About the hands, I followed what I know UX had planned for a future version and they used hands 🤷🏻‍♂️

**Comment by MichaelKohler** [comment]
Let's double check with UX then. Can you take on this task and share my concerns?

**Comment by MichaelKohler** [comment]
✓ and ❌ might be better signs to play it safe? however I couldn't find two similar looking unicode characters right now..

**Comment by MichaelKohler** [comment]
So far I could not remove the skip button, but at least I fixed it. Will need to think more about this.
