### ISSUE TITLE
Why can't I see the sentences added already?

### ISSUE THREAD

**Issue by fnielsen** [common-voice/sentence-collector#445]
Why can't I see the sentences added already? For instance, I do not see how I can download them.

**Comment by MichaelKohler** [comment]
What's your use case for downloading them? I suppose for that use case you'd want approved sentences only? If so, the easiest way is the `sentence-collector.txt` per language at https://github.com/common-voice/common-voice/tree/main/server/data. 

For anything else there is https://commonvoice.mozilla.org/sentence-collector/api/. 

If you mean your own sentences, see https://github.com/common-voice/sentence-collector/issues/118

**Comment by fnielsen** [comment]
Thanks! I did not discover these resources.
