### ISSUE TITLE
Incorrect sentences for Uzbek in sentence collector

### ISSUE THREAD

**Issue by imamasolih** [common-voice/sentence-collector#452]
**1.** Validated sentences in Uzbek should be deleted. There are around 485 so far and invalid due to following reasons:
a) Sentence fragments. Majority of the reviewed sentences are not full sentences, they have almost no meaning to end. Maybe, it is because of improper uploading, split into sentence parts.
b) Grammatically and orthographically incorrect. It comes with a) and separate diacritic marks of few letters. For example, in every day use **o‘** and **g‘** ( ‘ Alt+0145 used) can be expressed with ‘ (not the same with the former) or ' but formally it would be wrong. There is also a hard sign ( ’ Alt+0146) in some specific words which is sometimes confused with other similar ones.

I am not saying that all sentences are invalid. There are a few accurate sentences which passed through two assessments above )
However, they can be counted only with fingers :( Therefore, I think it would be easier to erase altogether.

**2.** There are many like these in sentence collector, not reviewed. I can only see 1k of them as the system allows. They came in sources, named **ok** and **private** (I hope no more :). So, these source sentences should be removed too.

I uploaded 4.5k triple-checked sentences (more so soon) and ready to launch my language production after reviewing them. However, waiting for removal of incorrect sentences out of dataset.

**Comment by ftyers** [comment]
Does this mean that:
1) all of the currently validated sentences in sentence collector should be deleted? 
2) after the currently validated sentences are deleted you will validate the remaining sentences? 
@MichaelKohler could you let @imamasolih the procedure for deleting all the currently validated sentences? :)

**Comment by imamasolih** [comment]
1. Yes. It is better to delete all rather than sort them out.
2. And there are many not-reviewed sentences in sentence collector like currently validated. I cited the sources above. They should be deleted too. After that, I can validate my sentences without a problem.

**Comment by MichaelKohler** [comment]
> a) Sentence fragments. Majority of the reviewed sentences are not full sentences, they have almost no meaning to end. Maybe, it is because of improper uploading, split into sentence parts.

Can you give us examples? I've taken a few and translated them through Google Translate and they at least sounded okay when auto-translated. 

> Grammatically and orthographically incorrect. It comes with a) and separate diacritic marks of few letters. For example, in every day use o‘ and g‘ ( ‘ Alt+0145 used) can be expressed with ‘ (not the same with the former) or ' but formally it would be wrong. There is also a hard sign ( ’ Alt+0146) in some specific words which is sometimes confused with other similar ones.

This feels like something that we should have a validator for: https://github.com/common-voice/sentence-collector/blob/main/server/lib/validation/VALIDATION.md . Otherwise this will happen over and over again.

**Comment by imamasolih** [comment]
1. Sure. For example the following sentences:

```
Albatta u paydo bo‘lgunga qadar
Lion isyon ko‘tardimi, demak, endi Lion yo‘q shiori ostida jazolash boshlanadi
Shu bois unga ham
o'nta so'zli chiroyli gap bo'lishi mumkin edi.
O‘shanda o‘n to‘rt yosh
ba'zilarini o‘qib madoring quriydi
Zebo yigit bo‘libdur
tayanchi madam Rolan edi
Yuk mashinasida O'zbekistinga kirib kelishadi va qamoqqa olinib, shu yerda halok bo‘lishadi
Bu yil darxtlar erta barg tashlagandi
```

Translation may sound well, but it doesn't always work with the original. Moreover, if a sentence contains an error, Google Translator won't let you know that and it translates with an inaccurate word in a way that is right. In the last sentence daraxtlar* is correct, but it won't affect the translation.

I do not want to erase the sentences too, because they are made up of extensive and amazing vocabulary. That is why I made a copy of the validated sentences for myself and will upload them to the sentence collector again after modification and rectifying errors so that we won't lose them.

2. Definitely! I asked my friend to give a hand.  So, we are working on it. As I understood, he is trying to find a suitable library for validation.

**Comment by mkholjuraev** [comment]
@MichaelKohler I am a friend of @imamasolih who is working on sentence validation. We are facing an issue with how words get extracted during the validation process. The [talisman tokinizer](https://github.com/common-voice/sentence-collector/blob/main/server/lib/validation/languages/en.js#L1) library is splitting words that has **O'** or **G'** letters in [the Uzbek language](https://www.google.com/search?q=o%27zbek+alifbosi&tbm=isch&source=iu&ictx=1&fir=xnGQJH6Y13P-vM%252CTPQiJyl1dh8wuM%252C_&vet=1&usg=AI4_-kQox1Vi2v5YHkw6Yihcb54WeLokTQ&sa=X&ved=2ahUKEwiGy7m-67fxAhURwKQKHY5ABYIQ9QF6BAgMEAE&biw=1920&bih=977#imgrc=K35vv9m51ntKAM) e.g **O'zbekiston** into **O** and **zbekiston**. I believe that it is because of how the word **Don't** gets extracted and divided into **do** and **not**. I am wondering if you have an existing solution? if not, can we use a different tokenizer library or can we create our own extractor?

**Comment by MichaelKohler** [comment]
While the English validation file uses `talisman`, you don't necessarily need to use it. [Italian](https://github.com/common-voice/sentence-collector/blob/main/server/lib/validation/languages/it.js#L6) and [Thai](https://github.com/common-voice/sentence-collector/blob/main/server/lib/validation/languages/th.js#L34) for example are counting characters. Would that work for you? Alternatively using a different npm package to split up into words might be okay as well.

**Comment by imamasolih** [comment]
@MichaelKohler Great! It might work. But how many characters can be displayed on Speak/Listen window on the website at most? 
I had a look that Italian team put a 125-character limit on their validation.

**Comment by MichaelKohler** [comment]
> But how many characters can be displayed on Speak/Listen window on the website at most?
I had a look that Italian team put a 125-character limit on their validation.

This heavily depends on the window size. If it gets too long the Speak/Listen cards become scrollable.

If I remember correctly we're aiming for clips at around 7-8 seconds maximum, but I might be misremembering this.
