### ISSUE TITLE
Swipe mode cards are on top of modals

### ISSUE THREAD

**Issue by Ugzuzg** [common-voice/sentence-collector#453]
![image](https://user-images.githubusercontent.com/1078004/123253218-c2bd1f80-d4dc-11eb-8d07-ec34f1380726.png)

**Comment by MichaelKohler** [comment]
Thanks for reporting, fixed in https://github.com/common-voice/sentence-collector/commit/17814dc5c1216ed821821a43e7b246113bcf5c7a
