### ISSUE TITLE
Investigation: Armenian/Armenian Western not well reflected in Sentence Collector

### ISSUE THREAD

**Issue by MichaelKohler** [common-voice/sentence-collector#454]
Currently in the Sentence Collector we have `hy`, which currently contains 2132 sentences. These currently do not get exported as Common Voice knows `hy-AM` and `hyw`. We need to adjust this.

Sentences in Sentence Collector: https://commonvoice.mozilla.org/sentence-collector/sentences/text/hy

## Questions to be answered

* Are the current sentences `Armenian` or `Armenian Western`?
* What's the correct native name for `Armenian Western`?

## Migration

| Code  | English  | Native  |  Action |
|---|---|---|---|
|  hy | ???  | ???  | Figure out where to migrate to  |
| hy-AM  | Armenian  |  Հայերեն  | Create in Sentence Collector  |
|  hyw | Armenian Western  | ???  | Create in Sentence Collector  |

**Comment by MichaelKohler** [comment]
@ekeleshian given that you have added the Armenian sentences from Wikipedia, could you help out here?

FYI @ftyers

**Comment by ekeleshian** [comment]
Thank you for the ping @MichaelKohler 
So your question relates to a bigger question that the Armenian Common Voice community extensively talked about in posts and meetups - should we maintain one or multiple voice corpora for the Armenian language?  The TLDR version of the answer is: let's maintain only one voice corpus that merges all dialects and both forms of Armenian orthography.  We ultimately think that the Wikipedia language split is an anti-pattern that we want to prevent from bleeding into other systems. As a result, we merged together hyw.wikipedia and hy.wikipedia sentences in [this PR](https://github.com/common-voice/common-voice/pull/3067).   The non-TLDR version is explained in this [blogpost](https://ekeleshian.github.io/posts/common-voice-armenia-frequently-asked-questions/#how-are-dialects-addressed-is-there-a-voice-corpus-for-each-dialect-similar-to-how-the-language-is-split-in-wikipedia).
I think hy-AM should be migrated to hy; hy-AM &  hyw should be taken out.

**Comment by ekeleshian** [comment]
So I think the quick fix here is to merge hy into hy-AM. 

The ideal fix is to merge hy-AM into hy and get rid of hy-AM and hyw altogether.

**Comment by MichaelKohler** [comment]
Thanks for the quick response! In that case this is bigger than just the Sentence Collector. Pulling in @phirework (and sent it to Hillary as well, didn't know her GitHub handle).

**Comment by MichaelKohler** [comment]
@jessicarose I'm closing this issue, but might be worth for you to have a look at. This does not only go for Sentence Collector but also Common Voice itself.
