### ISSUE TITLE
Buttons are disapearing in Chrome

### ISSUE THREAD

**Issue by stefangrotz** [common-voice/sentence-collector#461]
I am using Chrome 92.0.4515.107 on OS X. When I hover over the buttons on slide mode they are flickering and disappear after that: 
![Bildschirmfoto 2021-07-28 um 09 50 15](https://user-images.githubusercontent.com/5982239/127285147-8344016e-85f4-4471-9d83-b8600f8ca04c.png)

**Comment by MichaelKohler** [comment]
Thanks, I was able to reproduce this on the same Chrome version and also Mac OS X.

**Comment by MichaelKohler** [comment]
When switching back to Chrome after writing this comment in Firefox it got even worse... I'm fairly sure that has something to do with the Swipe Card implementation. Will have a look.

<img width="1673" alt="Screenshot 2021-07-29 at 18 10 24" src="https://user-images.githubusercontent.com/330324/127527109-20ee2340-ce4d-43e7-a788-9066d89f0697.png">

**Comment by MichaelKohler** [comment]
Ignore this message ^. There seems to be an issue with deployment, will report back once the fix is live.
