### ISSUE TITLE
review sentences bug for esperanto and italian 

### ISSUE THREAD

**Issue by Espero84** [common-voice/sentence-collector#462]
Hello,
For several days Review Sentences no longer works for Esperanto and Italian.
But for German it works perfectly.
description:
the sentence is displayed with the three buttons and the button finish review.
When you click on one of the three buttons, they all disappear.
Sometimes, if you have pressed "aprobe", a new sentence is entered, but partially erased by the previous sentence.

these problems appear on my Huawei phone, on my Samsung tablet, and on my Compaq computer.
Thanks if you can help me.

And thanks for the replies you sent yesterday, but I couldn't log in to write.

Espero84
Bonjour,
depuis plusieurs jours Review Sentences ne fonctionne plus pour l'esperanto et pour l'italien.
Mais pour l'allemand, il fonctionne parfaitement.
description : 
la phrase s'affiche avec les trois boutons et le bouton finish review.
Quand on clique sur un des trois boutons, ils disparaissent tous.
Parfois, si on a appuyé sur "aprobe", une nouvelle phrase s'inscrit, mais en partie effacée par la phrase précédente.

ces problèmes apparaissent sur mon téléphone Huawei, sur ma tablette Samsung et sur mon ordinateur Compaq.
Merci si vous pouvez m'aider.

Et merci pour les réponses que vous avez envoyées hier, mais je n'arrivais pas à me connecter pour écrire.

Espero84

**Comment by MichaelKohler** [comment]
Thanks for filing this. We'll track this in #461
