### ISSUE TITLE
Add Nyankole language

### ISSUE THREAD

**Issue by Atukunda-Gift** [common-voice/sentence-collector#468]
I would like to have a sentence-collector for nyn-nyankole language on common voice

**Comment by MichaelKohler** [comment]
Reference: https://github.com/common-voice/common-voice/issues/3221

ISO code: `nyn`
English name: Nyankole
Native name: <tbd>

@Atukunda-Gift is "Nyankole" also the name of the language as used when speaking Nyankole? In Sentence Collector we usually display it in the format: "English name (native name)" - for example "German (Deutsch)".

<img width="539" alt="Screenshot 2021-08-07 at 16 57 34" src="https://user-images.githubusercontent.com/330324/128604382-52e32298-5952-43d8-b410-c609160ea5de.png">

**Comment by Atukunda-Gift** [comment]
Native name: Runyankore

**Comment by Atukunda-Gift** [comment]
Awesome, thanks! @Micheal Kholer
