### ISSUE TITLE
Improve UX of Language Selector in Profile

### ISSUE THREAD

**Issue by MichaelKohler** [common-voice/sentence-collector#473]
Currently the profile has a standard dropdown to list all languages. This is currently how the dropdown looks on the "Profile" page:

![image](https://user-images.githubusercontent.com/330324/132983814-ed53fede-d0a4-4cdc-8a59-76185ec11ad1.png)

The dropdown is built here: https://github.com/common-voice/sentence-collector/blob/0ea738a73a558b5508e7a7d6c58248642930d115/web/src/components/language-selector.tsx

This could be improved with a combobox that allows searching, see https://omnilingo.xyz/ for an example. This then would make it easier to search for a language and users wouldn't need to scroll through the whole dropdown. Preferably this would use an already existing dropdown available through npm, rather than building our own.

One thing to note here is that the same dropdown is also used for the "Add" and "Review" sections. For those it should still be a dropdown with a selection to make it easier to choose. Therefore I think it would be great if the dropdown implementation would support a "list" (like a normal dropdown) and a search for it.

Thanks @ftyers for suggesting this.

**Comment by venkateshprabhu2** [comment]
Can I work on this? How do I get started?

**Comment by MichaelKohler** [comment]
Yes, this is free to be worked on. Here's the approach I would suggest:

* Set up the local environment as outlined in the [README](https://github.com/common-voice/sentence-collector/blob/main/README.md#local-development)
* Look at the issue description, make sure you can find the necessary parts of the website locally and fully understand what should be implemented here
* Find a dropdown UI library that is well maintained, regularly updated, and fulfills the requirements here (happy to verify if we want to use a certain library once you found one, just post here to get feedback!)
* Implement what is needed
* Test it locally and verify that your changes fix the issue
* Make sure that the automated tests pass locally (see the README for how to run the tests)

You might want to start with the other issue you commented on first though, as this one here might not be a super easy task at first.

If you have any questions and run into issues, feel free to either post here or join our [Matrix chat](https://matrix.to/#/#common-voice:mozilla.org).

**Comment by venkateshprabhu2** [comment]
I will work on this during next week.

**Comment by MichaelKohler** [comment]
@venkateshprabhu2 how is it going? Are you still interested in working on this? Is there any blocker I could help you with?

**Comment by venkateshprabhu2** [comment]
> @venkateshprabhu2 how is it going? Are you still interested in working on this? Is there any blocker I could help you with?

@MichaelKohler Sorry about the delay. Office work took over. Give me until the end of this week and I will get back on this.

**Comment by venkateshprabhu2** [comment]
Thanks for understanding, Michael. Running a bit more late. You will have an update by end of this week.

**Comment by venkateshprabhu2** [comment]
I came across https://react.semantic-ui.com/modules/dropdown/ as a top result. Is it good to use?

**Comment by MichaelKohler** [comment]
Thanks for looking into this. Functionality-wise this looks pretty good to me. Is there a way we could us this without the remaining parts of Semantic UI? What would the impact on the final `main.js` file be? (You can include it and run `npm run build` to generate that file and then compare against the file generated currently without modifications)

In the end I'd like to avoid including something that would be blowing up the bundle size just for a dropdown, but can't really say if it would be bad without knowing that number (and I don't currently have time to compare it myself).

**Comment by HarikalarKutusu** [comment]
An alternative suggestion for this: https://www.npmjs.com/package/react-select

**Comment by venkateshprabhu2** [comment]
Thank you. @MichaelKohler Should I compare both and share the results?

**Comment by MichaelKohler** [comment]
That might be interesting. I can't say if there will be a big impact at all though, but worth checking :)

**Comment by MichaelKohler** [comment]
> One thing to note here is that the same dropdown is also used for the "Add" and "Review" sections. For those it should still be a dropdown with a selection to make it easier to choose. Therefore I think it would be great if the dropdown implementation would support a "list" (like a normal dropdown) and a search for it.

Looking at both libraries, I think it would be fine to use the same approach for all dropdowns (Language select in profile, as well as the ones for Review, Add and Stats). Important thing here is to make sure that the language gets preselected if there is only one available.

**Comment by venkateshprabhu2** [comment]
Sure. I will work on that. Thanks.

**Comment by venkateshprabhu2** [comment]
Here's where I am at right now:

Current main.js without installing anything new - 305 KB.

1. Using semantic-UI: Running into a build issue when I install it and try to import it. Apparently there is a bug https://github.com/Semantic-Org/Semantic-UI-React/issues/4287 and the solution is to use CDN(add css link). Is this alright to do?

2. react-select: I Installed, imported it in language-selector module and ran npm build but the size of main remains 305kb. Is this expected or am I missing something?

**Comment by HarikalarKutusu** [comment]
> react-select: I Installed, imported it in language-selector module and ran npm build but the size of main remains 305kb. Is this expected or am I missing something?
Tree-shaking? Did you implement it in JSX code or just imported the module?

**Comment by MichaelKohler** [comment]
> Using semantic-UI: Running into a build issue when I install it and try to import it. Apparently there is a bug https://github.com/Semantic-Org/Semantic-UI-React/issues/4287 and the solution is to use CDN(add css link). Is this alright to do?

Thanks for looking into this. In that case I'd say let's go for `react-select`, as using a CSS link makes it harder to update (somebody needs to remember to change the version in the link, compared to running upgrades on npm packages).

**Comment by venkateshprabhu2** [comment]
> > react-select: I Installed, imported it in language-selector module and ran npm build but the size of main remains 305kb. Is this expected or am I missing something?
> 
> Tree-shaking? Did you implement it in JSX code or just imported the module?

I just imported the module. TIL about tree-shaking. Will implement and compare. 

@MichaelKohler Sure, will look into react-select and update here. 

(Sorry about the delay again. I will speed it up.)

**Comment by MichaelKohler** [comment]
> (Sorry about the delay again. I will speed it up.)

Absolutely no issue :)

**Comment by venkateshprabhu2** [comment]
I imported react-select and used it and ran the build. main.js is 382KiB after that. Without react-select, it is 309 KiB currently. Is that alright?

**Comment by HarikalarKutusu** [comment]
As per https://bundlephobia.com/package/react-select@5.2.2 that is mostly because of the styling-related dependencies as far as I can see...

At the bottom of that page, there are smaller alternatives. I also found this post: https://bestofreactjs.com/repo/based-ghost-react-functional-select-react-select

**Comment by venkateshprabhu2** [comment]
Thank you. I tried react-functional-select and it is coming up to 374 KiB. It's not supposed to be that much? Am I missing something? I imported it and added the example component in the code and ran the build.

**Comment by HarikalarKutusu** [comment]
react-select has many dependencies, but react-functional-select has none.  If you also used styled-components, it will add many of course.

Interesting to see such a rather small functionality would add some 21-23% increase.

**Comment by venkateshprabhu2** [comment]
So, should I continue on the implementation with react-select? @MichaelKohler Any thoughts?

**Comment by MichaelKohler** [comment]
Further thought a bit more about this. Generally I would like to keep the Sentence Collector as lean as possible. Given that not everyone around the world has a great internet connection, I think this should be a goal we're thriving for. That being said, increasing the bundle size to 382 KB is okay to me, as we introduce functionality that is helpful.

@venkateshprabhu2 yes, please go ahead with using `react-select`. I just had a look at `language-selector.tsx` and I think we can also simplify the code a bit, I don't think we need `Options`, `Option` and `NullOption` all separated out, given that `react-select` just takes an array of values. I'd be fine with doing this all in one component. I'll leave it up to you what the best approach here is, but feel free to adjust this component as you think is best :) Thanks for the help here!

**Comment by MichaelKohler** [comment]
Thanks for bringing this up. The Sentence Collector now has moved to https://commonvoice.mozilla.org/write and therefore is now hosted in the main Common Voice repository. That being said, this issue is no longer relevant as that part of the code does not exist anymore.
