### ISSUE TITLE
Add link to Language Addition process in Profile

### ISSUE THREAD

**Issue by MichaelKohler** [common-voice/sentence-collector#474]
Currently there is no way to request a new language if the language is not in Sentence Collector yet. We should mention that flow next to the dropdown, and point to https://discourse.mozilla.org/t/readme-how-to-see-my-language-on-common-voice/31530

![image](https://user-images.githubusercontent.com/330324/140608480-f4920882-eb07-4a01-960a-04d12f9b43aa.png)

The section can be found at https://github.com/common-voice/sentence-collector/blob/ed168c802bdbe3290848bea6b876d4f54965da12/web/src/components/add-language-section.tsx.

Let's add the following string below the dropdown: "If your language is not listed here, you can request it through [this process](https://discourse.mozilla.org/t/readme-how-to-see-my-language-on-common-voice/31530)."

**Comment by HarikalarKutusu** [comment]
After the decision on Option 2 [here](https://discourse.mozilla.org/t/sentence-collector-localization-update/87904), is this still necessary or will this just become a link to Pontoon?

**Comment by MichaelKohler** [comment]
If the language is not yet enabled in Sentence Collector, it's highly likely that it's not enabled in Common Voice at all. For that case I think it's more beneficial to link to the Discourse topic, as that also explains the process apart from the localization itself.

**Comment by MichaelKohler** [comment]
> I still could not get how Localization & SC database & CV languages will be related...

I'll document the Localization process for Sentence Collector soon-ish. The Localization part does not change anything on how the Sentence Collector database and Common Voice languages work. I'll CC you on the documentation PR and you can then file a new issue with questions in case the documentation does not answer a question you have, does that make sense?

**Comment by HarikalarKutusu** [comment]
OK...
