### ISSUE TITLE
Languages enabled in Pontoon but not sentence-collector

### ISSUE THREAD

**Issue by ftyers** [common-voice/sentence-collector#476]
Mapudungun (native name *Mapudungun*) is [enabled in Pontoon](https://pontoon.mozilla.org/arn/common-voice/), but not in sentence collector, could it be added?

**Comment by MichaelKohler** [comment]
I renamed this issue to also look into other languages that we might have missed. Will report back.

**Comment by MichaelKohler** [comment]
I implemented #477 which gave me the following list:

* izh
* arn
* hy-AM / hyw (to be handled in https://github.com/common-voice/sentence-collector/issues/454)

I will add both arn and izh and close this issue.
