### ISSUE TITLE
Localization: Use Fluent for all strings so we can eventually translate the UI

### ISSUE THREAD

**Issue by MichaelKohler** [common-voice/sentence-collector#479]
We want to use Fluent to translate the Sentence Collector User Interface. As there are still some open questions in #3, we can start by changing the strings to use Fluent for English. This means:

* Integrate Fluent libraries as needed
* Change all strings to use Fluent
* Implement mechanism to fetch fluent file
* Have all strings in English use Fluent already

This excludes:
* Language negotiation
* Language parameter in the URL

**Comment by HarikalarKutusu** [comment]
Hi @MichaelKohler, please raise a hand if you need any help in coding/extracting. I can also beta test by a rather speedy translation.

**Comment by MichaelKohler** [comment]
I'm not sure if I could tackle this anytime soon, so if you want to help out, go or it! :) Happy to answer questions if there are any.

**Comment by HarikalarKutusu** [comment]
I though you started and I would help :/ I'll get it to local and have a first look, it would be a complete overhaul I suppose... Fluent is new to me, so don't go away :)
Is [this](https://github.com/MichaelKohler/sentence-collector/tree/feature/localization) the correct one?

Your comments [here](https://github.com/common-voice/sentence-collector/issues/3#issuecomment-917394346) are very important, such as the use of Pantoon.

**Comment by MichaelKohler** [comment]
Yes, that branch was my initial try. However that also includes language negotiation and everything, so I'd rather not build off that one. Also note that a lot has changes since then, so yeah, maximum useful for inspiration.

For now, let's just extract the EN strings, use them through Fluent and leave it at that. The comments you mentioned will need to be figured out before we do more.

**Comment by HarikalarKutusu** [comment]
OK... But, are there any plans to eventually integrate this to the CV dashboard? I think I read about it but it is not under project timeline. If this is the case half of the strings will deleted/change...

**Comment by MichaelKohler** [comment]
Eventually, maybe. There have been some ideas in the past, but I don't see that happening anytime soon. Even if, most strings will still be valid.

**Comment by HarikalarKutusu** [comment]
OK, I quickly examined the code, I can start it about 10 days later when I get to my development environment, I'll be travelling next week...
Do we need to do also the /server folder or just /web portion?

**Comment by MichaelKohler** [comment]
> Do we need to do also the /server folder or just /web portion?

Most strings are in `/web`. There are two parts that are currently in the `/server` portion, but let's think about that later:

* Validation messages
* Language names (though I really doubt we should translate every single language name into every single language, that seems not beneficial really)

**Comment by HarikalarKutusu** [comment]
I have two problems on my local environment. These might be related to my environment if you have none of these.

**1. Loading of local css gives the following**

> GEThttp://localhost:3333/main.css [HTTP/1.1 404 Not Found 4ms]
> The resource from “http://localhost:3333/main.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).

**2. After clicking statistics, "Updating..." is shown but never goes away. **

I must test once again if the results are correct thou...

**Comment by MichaelKohler** [comment]
The first one is not an issue at all. Definitely not optimal, but not an issue, as we're using inline styles for dev.

For the second part, is that already with your fix applied that fixes the wrong `sc-stats-updating` usage? And, can you post a screenshot for me to better understand what you're seeing?

**Comment by HarikalarKutusu** [comment]
Iy can be what you said...
I cannot replicate the second one although I restarted everything. It is showing "Last Update: ..."
What is the schedule or any trigger for this?

**Comment by MichaelKohler** [comment]
I would need to check, but I think every 6 hours. However, you can either open it in a private window or delete the localStorage key to circumvent that.

**Comment by HarikalarKutusu** [comment]
It is getting weird... Can we talk on Matrix?

**Comment by MichaelKohler** [comment]
This is now done in https://github.com/common-voice/sentence-collector/pull/507.
