### ISSUE TITLE
Possible regression in new interface - Source overlap

### ISSUE THREAD

**Issue by HarikalarKutusu** [common-voice/sentence-collector#480]
As shown in the image below, there are multiple lines of "source"s listed at the back of the box. If you copy paste that area into a text editor you will see the whole set (which might be useful sometimes :) ).
OS: Win 10x64
Browser: Opera (latest)

![image](https://user-images.githubusercontent.com/8849617/132959296-214c5935-a42e-40cf-8888-7448eabd4551.png)

**Comment by MichaelKohler** [comment]
Thanks for filing this. The cards are indeed all stacked on top of each other. However it should not overflow the card. I don't have Opera installed right now, but I can test this tomorrow. Does this also happen in other browsers for you (if you have access to any)?

**Comment by HarikalarKutusu** [comment]
Tested on Chrome same result, could not test on others as auth process is preventing... But anyway it is a CSS issue, it would be the same on all modern browsers...

It only happens when the "source" field is too long. The following solves it...

.card-sentence-box {
 ...
 overflow: hidden;
}

.card-source {
 ...
 overflow-wrap: anywhere;
}
