### ISSUE TITLE
Citing sources and how to page

### ISSUE THREAD

**Issue by Heyhillary** [common-voice/sentence-collector#481]
Hey 

Following a discussion with a community member. I would like to suggest two changes for discussion.

1. On the how-to page, it might be good to include examples of how to attribute the source of the sentence text submitted. E.g Website link, Harvard referencing for public domain books (non-digital material).

This might help with public license text that is not digitized 

2. On the how to-page could you also include a link to the [cc-0 waiver process](https://common-voice.github.io/community-playbook/sub_pages/cc0waiver_process.html) with the following. "For text that is copyrighted and the copyright owner of the text wants to waiver the cc-0, please use the [following process](https://common-voice.github.io/community-playbook/sub_pages/cc0waiver_process.html)"

**Comment by MichaelKohler** [comment]
Hi Hillary, I like those suggestions. This would definitely improve the How To.

Would you like to create a PR for this? The file can be found at https://github.com/common-voice/sentence-collector/blob/main/web/src/components/how-to.tsx. Alternatively, could you provide the text you'd like to see for the first point?

**Comment by Heyhillary** [comment]
yeah sure !
