### ISSUE TITLE
Make sentence requirements in HowTo more generic

### ISSUE THREAD

**Issue by HarikalarKutusu** [common-voice/sentence-collector#484]
When I look at the following I can see different settings between languages.

https://github.com/common-voice/sentence-collector/tree/main/server/lib/validation/languages

So, two questions arise:
1. Does every language need to have one?
2. Some languages have way larger max-word-count, or is it char count in these languages? I can understand small variations of course based on average word length in each language but it will be different from the advertised 14 words - so localized pages in CV should reflect it. How do you optimize it?

A small increase would mean many new allowed sentences of course...

**Comment by MichaelKohler** [comment]
> Does every language need to have one?

In a perfect world every language would probably have one, but we never really did any outreach to do it. It's a good way to keep the review queue clean, as some things can be enforced if they happen too often leading to too many rejections.

> Some languages have way larger max-word-count, or is it char count in these languages? I can understand small variations of course based on average word length in each language but it will be different from the advertised 14 words - so localized pages in CV should reflect it. How do you optimize it?

Some languages use word count, some use char count. Italian for example uses number of characters. I suppose that's indeed the big difference you're seeing. If I remember correctly the general suggestion was to not use sentences that would take more than 7 seconds to read out aloud. I might be wrong on that number though.

> so localized pages in CV should reflect it

Could you elaborate on this? I'm not sure if I understand what you mean.

**Comment by HarikalarKutusu** [comment]
Sorry, I meant this page: https://commonvoice.mozilla.org/sentence-collector/#/how-to

There are also Discourse posts stating 14 words... It didn't see it in the playbook thou.

**Comment by MichaelKohler** [comment]
Ah, I see. This poses an interesting question, which probably should be answered in #3 (I've added it there). Should the language adapt to the language you're contributing to or is that independent? Common Voice's UI changes when you change contribution language, but for the Sentence Collector this might be odd to have the UI language change when you select another language from the Add/Review dropdowns?

I would probably argue that should be independent. In that case I don't think that could be solved through localized pages only. Imagine the following scenario: I want my UI in Spanish, but I'm contributing to English and Spanish. If we use the localized strings for this, it would tell me the localized string for Spanish, even when contributing to English. That might not be correct.

> In a perfect world every language would probably have one, but we never really did any outreach to do it. It's a good way to keep the review queue clean, as some things can be enforced if they happen too often leading to too many rejections.

This was a bit vague. Sentences still get validated when there is no language specific file, it just uses the fallback English validation. So if that one doesn't fit the language, or there are more cases for a language that make sense, then it's worthwhile to add a separate validation.

Given that, I wonder if we shouldn't just remove "Length. Sentences must be 14 words or less." from the HowTo. The validation tells the user about it anyway when submitting. The others seem generic enough that they still make sense IMHO. Also I think integrating a text-representation of the full validations is not worth it.

**Comment by HarikalarKutusu** [comment]
Sorry for answering late, I was on travelling a lot lately.
Of course you are right in that. On the other hand some sentence contributors pre-process the extracted text and feed them to this tool, like I do. I use Notepad++ and Excel with some formulae to find suitable sentences and those which can be correctable (like numbers). I use 14 words + 100 characters for Turkish. I don't know either if extractions tools are honoring these....
There must be some resource reflecting these requirements for contributors for the language they are adding sentences, not the UI language - before they are hitting the validation rules - I think.

**Comment by MichaelKohler** [comment]
Fair point. Do you think adding something like "Languages can have their [own validation rules](https://github.com/common-voice/sentence-collector/tree/main/server/lib/validation/languages) with additional requirements" would be enough"? That would be easy to do and wouldn't require to be dynamic.

**Comment by HarikalarKutusu** [comment]
I think it will be a good start. That phrasing might be expanded in the future when the integration to the main CV stage comes.
Maybe adding "If your language is not listed, the default EN rules are used" will remove some confusion.
Most of the languages there already have communities for further instructions and as far as I can see this tool is not used by casual volunteers, but rather more dedicated people who would also be part of the communities...

**Comment by MichaelKohler** [comment]
# Summary of what needs to be done

* Remove "Length. Sentences must be 14 words or less."
* Add instead "Languages can have their [own validation rules](https://github.com/common-voice/sentence-collector/tree/main/server/lib/validation/languages) with additional requirements. If there is no specific validation file for a language, we are using the generic English rules."
