### ISSUE TITLE
[Turkish] Word limit due to apostrophe

### ISSUE THREAD

**Issue by HarikalarKutusu** [common-voice/sentence-collector#485]
I've been pre-processing the sentences in Excel against limits, duplicates etc. This time I got several rejections where I calculated 14 words. All these had apostrophes in the sentence. Examples:

İkinci Dünya Harbi'nden az önceki sıralarda olduğu için, belki lordlarda gezip dolaşma hevesi yoktu.
Güveyin kardeşi Hüseyin, Yakup Ağa'nın yanına sokularak kulağına eğilmiş, özür dileyen bir sesle mırıldanıyordu.
Yaptığı resme baktıkça bunu kendisi de fark ederek, "Ah, Fransa'da birkaç sene daha kalabilseydim"

I think "İkinci Dünya Harbi'nden" should not be counted as four words...
What do you think?

**Comment by HarikalarKutusu** [comment]
It is not critical of course :) I think we might leave it as is for now, as it is an edge case. But these are used commonly with proper name use Turkish.
That should also cause problems for English I think (possessive case)... 
To prevent global changes, I'll take a look at the server-side validation code, which is your second bullet point.

**Comment by ftyers** [comment]
[commonvoice-utils](https://github.com/ftyers/commonvoice-utils/) has a tokeniser that supports most of the languages in Common Voice.

```python
>>> from cvutils import Tokeniser
>>> s = "İkinci Dünya Harbi'nden az önceki sıralarda olduğu için, belki lordlarda gezip dolaşma hevesi yoktu."
>>> t = Tokeniser('tr')
>>> t.tokenise(s)
['İkinci', 'Dünya', "Harbi'nden", 'az', 'önceki', 'sıralarda', 'olduğu', 'için', ', ', 'belki', 'lordlarda', 'gezip', 'dolaşma', 'hevesi', 'yoktu', '.']
>>> len(t.tokenise(s))
16
>>> from cvutils import Tagger
>>> tagger = Tagger('tr')
>>> tagger.tag(s)
>>> tagger.tag(t.tokenise(s))
['X', 'PROPN', 'PROPN', 'X', 'X', 'X', 'X', 'X', 'PUNCT', 'X', 'X', 'X', 'X', 'X', 'X', 'PUNCT']
>>> [i for i in tagger.tag(t.tokenise(s)) if not i == 'PUNCT']
['X', 'PROPN', 'PROPN', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X']
>>> len([i for i in tagger.tag(t.tokenise(s)) if not i == 'PUNCT'])
14
```
Not sure if this is helpful or not?

**Comment by MichaelKohler** [comment]
Generally helpful, but not in this case, we can't easily integrate Python libraries.

**Comment by HarikalarKutusu** [comment]
Thank you @ftyers, I was going to look for a tokenizer to create a dictionary to see how much we covered until now. That will help me indeed...

**Comment by MichaelKohler** [comment]
Thanks for bringing this up. The Sentence Collector now has moved to https://commonvoice.mozilla.org/write and therefore is now hosted in the main Common Voice repository. That being said, this might still be an issue there and might be worth a more generic issue covering a more language-spanning approach.
