### ISSUE TITLE
Enabling uppercase for key based validation

### ISSUE THREAD

**Issue by HarikalarKutusu** [common-voice/sentence-collector#487]
I think it is in web/src/components/review-form.tsx... It only handles lowercase letters. I hit this while reviewing with caps-lock on. Maybe it is a good idea to lowercase it before checks...

**Comment by MichaelKohler** [comment]
Indeed, the code block in https://github.com/common-voice/sentence-collector/blob/main/web/src/components/review-form.tsx#L111-L123 should first convert it to lowercase and then do these checks. Nice find!
