### ISSUE TITLE
Localization: Set up Pontoon infrastructure and release schedule

### ISSUE THREAD

**Issue by MichaelKohler** [common-voice/sentence-collector#491]
Can we somehow merge the Common Voice project on Pontoon with the Sentence Collector repo so we do not need a separate project on Pontoon? Can Pontoon handle two repos?

If not, how can we streamline the process otherwise?

What strategy do we want to use to deploy new translations, as it is right now we do not have a fixed release schedule?

**Comment by MichaelKohler** [comment]
https://discourse.mozilla.org/t/sentence-collector-localization-update/87904

**Comment by MichaelKohler** [comment]
Cross-posting from the Discourse topic, from what I understand these would be the two options:

## Option 1

* We set up a new project (analog to Common Voice) in Pontoon and link it with the Sentence Collector repository
* The strings would live in the Sentence Collector repository
* We enable all current languages from Common Voice in that new project as well
* Every time a new language is enabled in Common Voice Pontoon, we should also enable it in the new project
* With this approach we would not have any special setup in the repository and everything would be “standard”

## Option 2

* We integrate Sentence Collector into the Common Voice Pontoon project
* The strings would live in the Common Voice repository
* We need to sync the source strings somehow to the Common Voice repository so Pontoon knows about changes
* Any translations would end up in the Common Voice repository, where they would not be used. We would need to regularly sync them to the Sentence Collector repository ourselves.
* This would lead to quite some work to get the synchronization set up correctly, and would need extensive documentation as it’s not a setup new contributors would expect.

**Comment by HarikalarKutusu** [comment]
From this, what I can understand is the Option 1 is viable. - until/unless SC is merged programmatically into CV.

**Comment by MichaelKohler** [comment]
I quickly talked to Jenny and she would prefer Option 2. She also reminded me that we don't need to keep the translation files in sync in this repo, and we can fetch them when building and pushing the deployment. This means that there is less work in terms of synchronization, now I agree with Option 2 as well. So we're gonna implement this in the same Pontoon project as the existing Common Voice strings. This will require some work on the Sentence Collector side, for which I will file separate issues. In terms of Pontoon itself there is nothing to be done.

**Comment by MichaelKohler** [comment]
Ah, and in terms of release schedule, we can align with Common Voice and do bi-weekly releases if needed.
