### ISSUE TITLE
Localization: Handle Language names

### ISSUE THREAD

**Issue by MichaelKohler** [common-voice/sentence-collector#492]
CV translates all the language names, we might be able to use that. However we should still show the native name as well.

**Comment by MichaelKohler** [comment]
As of https://github.com/common-voice/sentence-collector/pull/514 the places where we still show the English and Native name are:

* "Add" language selection dropdown
* "Review" language selection dropdown
* "Profile" language add section dropdown

All these are using the same `LanguageSelector`. At least for Add and Review it would be fine to only show the native name. For adding a language in the profile it might be fine too, but then we would need everyone to find it by native name, and not by English name. Not sure if that would be good UX?

**Comment by MichaelKohler** [comment]
I think this doesn't block the release of localization and can be followed up upon later on. For now the only English name left is in the "Add language" language selector dropdown. While this is not great, we need to figure out how we can handle all the language names. Common Voice already has translations for some languages, but Sentence Collector has a few languages that are not yet enabled on Common Voice. But maybe that indeed is the problem itself. We will need to discuss this.

**Comment by HarikalarKutusu** [comment]
If there is no hindrance, I would suggest putting the sentences to Pontoon. Translation + accept process in Pontoon will take quite a few time, 

> Sentence Collector has a few languages that are not yet enabled on Common Voice. But maybe that indeed is the problem itself. We will need to discuss this.

IMHO this is normal per the New Language process.
If there are languages in SC that are not in Pontoon that would be not normal.
I think keeping Pontoon & SC in parallel would be a good idea for these.

**Comment by MichaelKohler** [comment]
I've created #531 to handle that initial discussion.

**Comment by MichaelKohler** [comment]
I'm closing this as this will eventually be handled with #534. Until then I think we're fine.
