### ISSUE TITLE
Issues with CSS text-transform in several languages

### ISSUE THREAD

**Issue by HarikalarKutusu** [common-voice/sentence-collector#500]
This is the ages-old "text-transform: uppercase;" issue.

Some characters do not turn to correct uppercase in the menu. Although it is stated that they are handled, it is not always the case, implementations differ. Therefore in every website I build, I remove "text-transform"s from the template and put capitals (İĞÜŞÇÖ) hardcoded if necessary. I suggest the same for Sentence Collector, other languages also have similar issues.

Ex: 
![image](https://user-images.githubusercontent.com/8849617/139306308-a56a48fa-a48a-4572-b610-f4e5fa29e8b5.png)
These should actualy be:
Cümlelerim => CÜMLELERİM
İstatistikler => İSTATİSTİKLER
Profil => PROFİL

**ONLY OTHER SOLUTION:**
Changing the upper-most level language in the html-tag:

```
<html lang="tr">
```

So these must be generated programmatically...

---------------

Here are some references:
Mozilla reference mentioning transforms:
https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform

This is the browser compatibility table (not really for Turkish):
https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform#browser_compatibility

caniuse.com page (you can see many problems):
https://caniuse.com/?search=text-transform

One complaint I filed 10 years before to a template producer:
https://www.joomlart.com/forums/topic/text-transformuppercase-and-turkish/

**Comment by MichaelKohler** [comment]
![image](https://user-images.githubusercontent.com/330324/139489686-f79c3d65-efaf-4f4d-990b-5a0f80f8b24d.png)

With the latest localization changes I think this is taken care of. We're setting the `lang` attribute correctly and this seems to work now. Please reopen if you disagree :)
