### ISSUE TITLE
Localization: Remove placeholder strings

### ISSUE THREAD

**Issue by MichaelKohler** [common-voice/sentence-collector#518]
At this point the fallback language mechanism for localization should work well enough so that we can remove all the placeholder strings in the components.

**Example:**

```
<Localized id="sc-settings-failed">
  <p className="form-error">Could not change settings. Please try again.</p>
</Localized>
```

should become

```
<Localized id="sc-settings-failed">
  <p className="form-error"></p>
</Localized>
```

**Comment by HarikalarKutusu** [comment]
I can handle these if you want so that you can focus on Pontoon integration etc.

**Comment by MichaelKohler** [comment]
That's up to you, feel free to work on this if you want to :)

**Comment by HarikalarKutusu** [comment]
OK, I'll handle that tomorrow... The campaign is doing not bad anyway.
