### ISSUE TITLE
Export localization file on sentence export to CV

### ISSUE THREAD

**Issue by MichaelKohler** [common-voice/sentence-collector#525]
We will translate the Sentence Collector strings in the same project as Common Voice. For that to work we need to export the FTL file to the Common Voice repository, so that Pontoon can pick up new strings to show for translation.

For now to keep it simple, and because we don't expect many changes per week, we will export the file to the Common Voice repo whenever we also export the sentences. This makes the general Actions setup easier for now. We can still re-evaluate that if we need to export it more often.

**Comment by HarikalarKutusu** [comment]
Hey @MichaelKohler, please check Matrix channel for a possible issue...
