### ISSUE TITLE
Blacklist offensive language

### ISSUE THREAD

**Issue by nukeador** [Common-Voice/sentence-collector#53]
Not a priority right now, but this idea was coming from different people, the ability to avoid sentences with offensive language.

**Comment by MichaelKohler** [comment]
I wonder how we could make sure that this scales. I'd like to avoid having full lists of blacklisted words in the code base, but maybe there are existing lists out there..

**Comment by stefangrotz** [comment]
There is this repository offering basic word lists for many languages: https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words

**Comment by MichaelKohler** [comment]
I've created #311 to use the Sentence Extractor rules for the Sentence Collector as well. We already have a blocklist included there.
