### ISSUE TITLE
UI Language selection

### ISSUE THREAD

**Issue by MichaelKohler** [common-voice/sentence-collector#533]
I think we should add a UI language dropdown somewhere once all the localization is ready. We might want a certain amount of strings already translated to enable that, similar to what Common Voice decides whether a language is ready to contribute to. This is to be figured out.

**Comment by HarikalarKutusu** [comment]
I was just adding that to #532 ...
Many languages in Pontoon are <90% already and translation of SC strings will take some time.

In my past projects, in these situations, I was outputting the fallback language strings in different colors and warning the user that UI is not fully translated, providing them with a link. Maybe this idea will be of help...

**Comment by MichaelKohler** [comment]
I'm not sure if we'd even need that. Right now English is the only thing. If somebody gets English with a few translated sentences it's not perfect, but might be better than English only. We can also leave it without any selection for some time and then enable it once more and more languages have translated the Sentence Collector strings as well. The selection through the url '/de/review` for example would still work.

**Comment by MichaelKohler** [comment]
Also filed #535 inspired by your suggestion :)

**Comment by HarikalarKutusu** [comment]
You might be able to get the lines starting with "sc-" from locale/messages.ftl and calculate the percentage for a decision?
That can be done at release time perhaps?
If it is 100%, do not put the Pontoon link, else put warning etc...

**Comment by MichaelKohler** [comment]
Yeah, we could do that. I'm currently creating milestones and for now I'm putting it in the first quarter of 2022. But we could do it before then of course.

**Comment by HarikalarKutusu** [comment]
Can't we target January 1st? It is International Public Domain Day...

I'm eager to help wherever I can like always :)

**Comment by MichaelKohler** [comment]
We can see how it goes until the end of the year and enable the dropdown whenever we feel it's beneficial already.

**Comment by HarikalarKutusu** [comment]
In the meantime, if you can put the data into Pontoon, people will get started and many languages can be ready in the meantime :)

There can only be a handful of additions due to code changes that can easily be done...

**Comment by MichaelKohler** [comment]
Yeah, I just assigned #525 to me and will do that this weekend.
