### ISSUE TITLE
Guide on where to find public domain corpus

### ISSUE THREAD

**Issue by nukeador** [Common-Voice/sentence-collector#54]
Improve how to and include guidance on where to find public domain sentences.

**Comment by limapedro** [comment]
Hi, I have a similar problem, for example the OpenSubtitles would be the perfect dataset for Common voice, it is large and rich, but its license it's MIT, maybe we could write our own sentences or translate from the English one to other languages, I really want to add Portuguese to the project. If you find any good source contact me ok.
