### ISSUE TITLE
Issue in language strings in Pontoon

### ISSUE THREAD

**Issue by HarikalarKutusu** [common-voice/sentence-collector#543]
For readability purposes, we divided the sentences into lines. Such as:

```
sc-home-intro = %The Sentence Collector is part of <commonVoiceLink>Common Voice</commonVoiceLink>.
    It allows contributors to collect and validate sentences created by the community.
    You can use this tool also to import and clean-up small-to-medium-sized public domain corpus 
    you have found or collected. All sentences need to be Public Domain.
    Approved sentences are exported every week to the Common Voice repository and are released
    on the Common Voice website on every new deployment.
```

But when it is transferred to Pontoon, they are also regarded as different lines.
So, for example, Google Translate helper gets confused from that. It tries to translate the following separately:

1. You can use this tool also to import and clean up small-to-medium-sized public domain corpus
2. you have found or collected. All sentences need to be Public Domain.

Of course, we shouldn't rely on Google Translate, but it gives us a head start... We copy it and correct it...

I'm preparing a PR now...  Another export would be advisable before the sentences got translated.

**Comment by HarikalarKutusu** [comment]
PR done...

**Comment by MichaelKohler** [comment]
Oh no, this is a good point. I did not think of that. Thanks for the PR!
