### ISSUE TITLE
Issue in Public Domain requirement wording

### ISSUE THREAD

**Issue by HarikalarKutusu** [common-voice/sentence-collector#545]
The following wording is somewhat misleading:

Remember that we need permission to publish those sentences, so always ensure that the text belongs to the <wikipediaLink>public domain</wikipediaLink>. If there is not an indication, reach out to the person that the text belongs to and ask if you can use their text.

Personally asking is not enough... The resources have to be declared Public Domain.

**Comment by MichaelKohler** [comment]
Indeed, nice catch! We should definitely make this more precise and link to the CC0 Waiver process. We already mention that process on the top of the document in the first bullet point: "To support the inclusion of work not under public licence, we have created a [Contributions Agreement template](https://common-voice.github.io/community-playbook/sub_pages/cc0waiver_process.html) for works where the copyright owner would like to contribute the material to Common Voice."

Side note: this text is part of the "How-To": https://commonvoice.mozilla.org/sentence-collector/#/en/how-to

So I'd suggest to change

"Remember that we need permission to publish those sentences, so always ensure that the text belongs to the public domain. If there is not an indication, reach out to the person that the text belongs to and ask if you can use their text."

to

"Remember that we need permission to publish those sentences, so always ensure that the text belongs to the public domain. If there is no explicit indication, reach out to the person that the text belongs to and ask if they want to contribute their text to the Public Domain. If they want to, help them go through the [Contributions Agreement process](https://common-voice.github.io/community-playbook/sub_pages/cc0waiver_process.html). If they do not want to contribute the text, then you are not allowed to use that text."

@Heyhillary would you agree to that change or do you have a better idea?

**Comment by HarikalarKutusu** [comment]
I defined "sc-howto-findpd-text-2" and the <cc0WaiverLink> in how-to.tsx with the suggested wording.
I'll be waiting for @Heyhillary 's comment on this before sending the commit/PR.

**Comment by MichaelKohler** [comment]
I've merged the PR with the implementation. Hillary, if you have another suggestion, feel free to tell me :)
