### ISSUE TITLE
Improve the review workflow

### ISSUE THREAD

**Issue by nukeador** [Common-Voice/sentence-collector#55]
Not a priority for MVP.

We got this feedback about the current workflow

> The review process was also confusing to me. You tap Yes and it turns green. Does that mean it’s approved? But it’s still there when I return to the page. Oh, I have to physically click the Submit button, which was right by the page number box, so I thought it was for changing the page. Having it auto-submit, hide the sentence and show the next sentence would be a lot better.

**Comment by MichaelKohler** [comment]
We should also define how skipping should work for this workflow. I suppose this should be stored somewhere so the user never sees that sentence again? Currently this wouldn't be the case, therefore some spec is needed.

**Comment by MichaelKohler** [comment]
Closing this as we will have a UX refresh at some point
