### ISSUE TITLE
Update Staging more often for localizations

### ISSUE THREAD

**Issue by MichaelKohler** [common-voice/sentence-collector#557]
As suggested by @rprys in https://discourse.mozilla.org/t/sentence-collector-localization-update/87904/39?u=mkohler it would be good if localizers would get feedback on how their strings look like on the actual website. We have a staging instance, however that only gets updated when there are new commits. As translations are handled in the Common Voice repo, we would need to deploy on a trigger. Multiple times a day, minimum once a day.

To facilitate this, we could add a GitHub Action cronjob to deploy. We however would need to make sure that the docker images get generated even though it's the same Commit hash used. As of 22 days ago at b97f4f72b6efc2d6afa0203608c7a152cfd8c56b this should not be an issue anymore, as the timestamp is added to the image tag. Would need to be verified though.

**Comment by HarikalarKutusu** [comment]
We should also include the language selector in the staging instance, right?

**Comment by MichaelKohler** [comment]
I wouldn't make a distinction here between production and staging, apart from the amount of languages that are available (we'd want to show all languages on staging, and possibly only translated languages on production).

**Comment by MichaelKohler** [comment]
Just to be clear here, yes, you are absolutely right, we should provide #533 as going through the URL to load it is cumbersome and non-intuitive.

**Comment by HarikalarKutusu** [comment]
Exactly, I meant that... I didn't see that part, is it ready and functional?

**Comment by MichaelKohler** [comment]
No, that task is still open.
