### ISSUE TITLE
Replace "submit" button in "add sentences" section (smartphone)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/sentence-collector#574]
Please compare picture 1 and 2
pic1 is from review section (as expected)
![Screenshot_20211213-221057](https://user-images.githubusercontent.com/92784377/145890718-7bffe4a2-e6fa-419e-9f9b-15c96495c972.png)

pic2 is from the "add sententences" section - swiped completely to the bottom.
![Screenshot_20211213-221124](https://user-images.githubusercontent.com/92784377/145890915-118decc2-2ccd-4b75-a619-fb27d7b04b29.png)

a) "submit" button should be in the middle
b) button is divided by a line
c) more space between "submit" and "discourse" when replaced in the middle of the page.
Contributers with bigger fingers have a problem, otherwise.

Os: Android10
Browser: Fx mobile stable
95.1.0 (Build #2015848803)
AC: 95.0.13, 58539f17f6
GV: 95.0-20211129150630
AS: 86.0.1
Hardware: Fairphone 3 plus

**Comment by MichaelKohler** [comment]
Thanks for filing this.

The Review page is generally centered, this page is not. So I don't necessarily agree that it should be centered. For the spacing, same root cause as #572 so I'm gonna mark this as duplicate.

**Comment by robovoice1** [comment]
ok
