### ISSUE TITLE
Add some delay between approval/rejection

### ISSUE THREAD

**Issue by ahangarha** [common-voice/sentence-collector#575]
Many times it happened that because of double click, I approve or reject two sentences.

I think keeping 1s delay to activate these buttons would fix the issue without bringing any usability issue.

**Comment by MichaelKohler** [comment]
Thanks for filing this issue. In all those cases you noticed it, but then it was too late to fix it, right? If so, I'd say https://github.com/common-voice/sentence-collector/issues/456 is a better fix for this problem. Would you agree?

**Comment by ahangarha** [comment]
Better solution. agree
