### ISSUE TITLE
Login redirect and logout redirect should redirect to URL including current language

### ISSUE THREAD

**Issue by robovoice1** [common-voice/sentence-collector#576]
1. Log in sentence collector
2. Change interface language from english to german (see pic) in profile, settings.
![Screenshot_20211231-133132](https://user-images.githubusercontent.com/92784377/147824429-c2baaa64-abb5-41d7-a7cb-86762c58970b.png)
3. Scroll/swipe up to the top of the page.
4. Tap on Common Voice moz://a
5. After 3 seconds the page is switching back to english language
Please see screen recording.

https://user-images.githubusercontent.com/92784377/147825012-ecf56412-5e2d-4a2c-997f-da6cd1eb33a9.mp4

I recorded in "home" section to hide my email, but also tapped top left!
6. Also: After logging out of sentence collector (with selected german language) the page falls back to english language.

A possible solution could be:
The chosen interface language is saved and permanent. A save button is presented to the contributor (under the interface language selection, see pic) to do so.

**Comment by MichaelKohler** [comment]
Thanks for filing this. The click on the logo on the top left is tracked here: https://github.com/common-voice/sentence-collector/issues/567

Logout is a good point as well. Both the [login redirect](https://github.com/common-voice/sentence-collector/blob/main/web/src/components/pages/login.tsx#L12), as well as the [logout redirect](https://github.com/common-voice/sentence-collector/blob/main/web/src/components/pages/login.tsx#L35) should use the current language in the URL it redirects to. Both should use `useLocaleUrl`, similarly to what we do in the header links:

https://github.com/common-voice/sentence-collector/blob/4abc875c06ed111a48a5d4b4f5fbbbb3b690fb4d/web/src/components/header.tsx#L25

**Comment by robovoice1** [comment]
oops, did not see https://github.com/common-voice/sentence-collector/issues/567

I need new glasses 🤓 and happy new year 😎

**Comment by MichaelKohler** [comment]
I was initially wrong, this is not as straight-forward as doing the changes described above. Removed the `good first issue` tag because of that.

**Comment by MichaelKohler** [comment]
The issue here is that we call `/logout` and `/login` respectively. The backend handles that call and then eventually redirects back to the containers:

```
res.redirect(`${FRONTEND_BASE_PATH}/#/login-success`)
...
res.redirect(`${FRONTEND_BASE_PATH}/#/logout-success`)
```

These containers are the React components linked to above. Even if we would use `useLocaleUrl` here, we would always get English as the backend did the redirect so we lost that information. We need to find a way to persist that across the redirect.

**Comment by MichaelKohler** [comment]
Thanks for bringing this up. The Sentence Collector now has moved to https://commonvoice.mozilla.org/write and therefore is now hosted in the main Common Voice repository. That being said, this issue is no longer relevant.
