### ISSUE TITLE
[Bug] LOCALIZATION.md link broken

### ISSUE THREAD

**Issue by robovoice1** [common-voice/sentence-collector#577]
https://github.com/common-voice/sentence-collector/blob/main/LOCALIZATION.md

![Screenshot_20220103-142028](https://user-images.githubusercontent.com/92784377/147935787-c2f62204-b8ab-4c71-b3fc-7f18cd2adc33.png)
![Screenshot_20220103-142903](https://user-images.githubusercontent.com/92784377/147936131-18ff9038-0623-4549-9091-348629a49efa.png)

**Comment by MichaelKohler** [comment]
Good catch, thanks for reporting!
