### ISSUE TITLE
[req] Passwordless Login And Two-Factor Authentication for sentence collector

### ISSUE THREAD

**Issue by robovoice1** [common-voice/sentence-collector#578]
https://newsroom.ibm.com/2020-02-11-IBM-X-Force-Stolen-Credentials-and-Vulnerabilities-Weaponized-Against-Businesses-in-2019

Integration of FIDO U2F and FIDO2/WebAuthn into the CV sentence collector login.
(i also requested this for CV website #3393)

No more stolen passwords,
No more many different passwords to remember,
Possible for desktop and smartphone users with additional (hardware key) security layer.

**Comment by MichaelKohler** [comment]
Thanks for filing this issue.

I commented on https://github.com/common-voice/common-voice/issues/3393 and the Sentence Collector should follow whatever the CV website does. I've asked that they also change the config for the Sentence Collector in case that would get implemented. I'll also keep an eye on that issue. Therefore I'm closing this one.
