### ISSUE TITLE
Statistic page does not load correctly with (android 12/GrapheneOs)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/sentence-collector#584]
Log in Sentence collector.
Choose Statistics.
Result is pic1
![Screenshot_20220118-214909](https://user-images.githubusercontent.com/92784377/150017482-e7c3379e-70e8-4f02-8373-e2d6351c31d3.png)

After reloading the page result is pic2
![Screenshot_20220118-215323](https://user-images.githubusercontent.com/92784377/150017614-96df5f99-ae51-43d0-b026-949ffd150cb0.png)

Pixel 4a smartphone
Android 12 with GrapheneOs
Firefox nightly android
98.0a1 (Build #2015858187), e9a4272e8+
AC: 98.0.20220117143334, 22229398d7
GV: 98.0a1-20220117035808
AS: 87.2.0

**Comment by MichaelKohler** [comment]
Thanks. I reproduced this last weekend and I'm confident this will be fixed by implementing #555. Should get to that next weekend, I think.

**Comment by robovoice1** [comment]
If not, i am reporting :-)

**Comment by MichaelKohler** [comment]
I'll try to remember to update this issue here when it should be fixed.

**Comment by robovoice1** [comment]
After the last sc update:
With vanadium browser statistics page loads (see pic)
![Screenshot_20220203-162719](https://user-images.githubusercontent.com/92784377/152375188-7eb16e79-8b07-4b65-b695-1f9a5cc4b897.png)

With Firefox nightly not (updating message apperars and just a 0 is displayed (see pic)
![Screenshot_20220203-163000](https://user-images.githubusercontent.com/92784377/152375580-42b0935c-e60e-4d21-a3f7-2db6da26140c.png)
Nightly:
98.0a1 (Build #2015861163), e73deb23a+
AC: 98.0.20220202143123, c3b551957a
GV: 98.0a1-20220202093701
AS: 90.0.1

Pixel 6 pro / Android 12/Graphene Os (latest beta channel release)

**Comment by robovoice1** [comment]
With a fresh install of fennec browser:
96.3.0 (Build #963020), 5a685e67c+
AC: 96.0.15, 0178a6fde9
GV: 96.0.3-20220129122726
AS: 86.2.2

Please see pic
![Screenshot_20220203-165534](https://user-images.githubusercontent.com/92784377/152379227-ace5b5e7-10c3-47eb-af0d-c461e7628477.png)

**Comment by robovoice1** [comment]
With the newest nightly statistic page is loading!

![Screenshot_20220204-221402](https://user-images.githubusercontent.com/92784377/152604524-e620b616-0e0a-4762-9d07-d5981d044097.png)

**Comment by MichaelKohler** [comment]
The new mechanism is deployed now, this should not happen anymore.
