### ISSUE TITLE
Cookies link- additional tap necessary to read about cookies (android)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/sentence-collector#595]
1. Log into sentence collector
2. Swipe to the bottom 
3. tap on " cookies" link
4. result is pic1 https://www.mozilla.org/en-US/privacy/websites/#cookies
![Screenshot_20220205-195324](https://user-images.githubusercontent.com/92784377/152655945-82db2ccb-6515-4f83-a97c-0f622d5e2468.png)

5. tap again on cookies link on moz foundation website to finally read about cookies 
https://www.mozilla.org/en-US/privacy/websites/#user-choices
![Screenshot_20220205-200118](https://user-images.githubusercontent.com/92784377/152655958-f7a006d5-451f-4076-ae97-fa70dcf691b0.png)

Pixel 6 pro
Android 12/Graphene Os (latest beta channel release)

Firefox nightly mobile android
98.0a1 (Build #2015861547), a6acacbcc+
AC: 98.0.20220204143127, 2d152a477f
GV: 98.0a1-20220204092958
AS: 91.0.1

**Comment by MichaelKohler** [comment]
Thanks!
