### ISSUE TITLE
In selected (de) Interface another language selection presented to read about cookies (android)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/sentence-collector#596]
1. Log into cv sc
2. choose (de) interface  language
3. swipe to the bottom
4. tap on cookies
5. result is pic1
![Screenshot_20220205-202801](https://user-images.githubusercontent.com/92784377/152656598-c2eb678f-76dc-4793-b093-1ff40597aab3.png)
https://www.mozilla.org/en-US/privacy/websites/#cookies
6.Select german language in moz foundation website
Result is pic2
![Screenshot_20220205-202824](https://user-images.githubusercontent.com/92784377/152656698-e86ec5fa-eb61-4ca7-90f3-121060993eb6.png)
https://www.mozilla.org/de/privacy/websites/

Pixel 6 pro 
Android 12/GrapheneOS 
Firefox nightly mobile android
98.0a1 (Build #2015861547), a6acacbcc+
AC: 98.0.20220204143127, 2d152a477f
GV: 98.0a1-20220204092958
AS: 91.0.1

**Comment by MichaelKohler** [comment]
Yes, indeed we should link to the website without including the `en-US` part of the URL, then the Mozilla website can use its own mechanism to negotiate the correct language. Thanks!

**Comment by robovoice1** [comment]
Wow ,3 updates 8-)
