### ISSUE TITLE
In selected (en) Interface cookies link is displayed in (de) language

### ISSUE THREAD

**Issue by robovoice1** [common-voice/sentence-collector#599]
Please see screenrecording.

https://user-images.githubusercontent.com/92784377/153582676-6f976023-1368-484a-a2f6-145f359d9df8.mp4

Pixel 6 pro
Android12 GrapheneOS
Fx nightly mobile android
99.0a1 (Build #2015862699), 72f0191fc+
AC: 99.0.20220210181319, ade2758828
GV: 99.0a1-20220210065747
AS: 91.0.1

**Comment by MichaelKohler** [comment]
The Sentence Collector and Mozilla website have different localizations. Currently we let the Mozilla website do its own language negotiation. If we wanted to change that, we'd need a mapping between available languages in SC and available languages on the Mozilla website. This is not something we're gonna do, as that is too much of a maintenance burdon.
