### ISSUE TITLE
Menu gone after clicking on select language link

### ISSUE THREAD

**Issue by danielsjf** [Common-Voice/sentence-collector#62]
If no language is selecting before the first review, clicking on this link drops the menu.

**Comment by MichaelKohler** [comment]
I'm not sure I understand this bug report. You didn't set a language, went to the Review page, and clicked on the "Profile" link there, correct? What exactly do you mean by "drops the menu"? Which browser are you using?

Here's what I tried to reproduce this:

<img width="994" alt="screenshot 2019-01-05 at 13 56 41" src="https://user-images.githubusercontent.com/330324/50724203-668a9900-10f2-11e9-9e9e-499170114b59.png">

<img width="882" alt="screenshot 2019-01-05 at 13 56 47" src="https://user-images.githubusercontent.com/330324/50724207-74401e80-10f2-11e9-81ea-e5ce8be36e04.png">

<img width="1280" alt="screenshot 2019-01-05 at 14 01 43" src="https://user-images.githubusercontent.com/330324/50724209-76a27880-10f2-11e9-8fb9-8acdc676d739.png">

**Comment by danielsjf** [comment]
Sorry it seems that I also cannot reproduce this anymore. I clicked around and suddenly I was missing the menu.

You can close this as I myself cannot even reproduce it.

**Comment by MichaelKohler** [comment]
Ok, feel free to open a new issue or reopen this one if you can reproduce it again. Thanks!
