### ISSUE TITLE
Italian has Chinese in it

### ISSUE THREAD

**Issue by coreymillerrev** [common-voice/sentence-collector#638]
cv-corpus-10.0-2022-07-04/it/cli
ps/common_voice_it_23771747.mp3 has this corresponding text: oggi in cinese si utilizzano indifferentemente gli ideogrammi 張三丰 oppure 張三峰

I see the following problems: 
- sentence collector should be programmed to only use sentences with the admitted characters.
- sentences should be revalidated automatically later in the process (if they can change)
- this is only the tip of the Italian iceberg

**Comment by MichaelKohler** [comment]
Thanks for filing this issue.

> sentence collector should be programmed to only use sentences with the admitted characters.

This can be done by improving https://github.com/common-voice/sentence-collector/blob/main/server/lib/validation/languages/it.js.

> sentences should be revalidated automatically later in the process (if they can change)

They can't.
