### ISSUE TITLE
Switching Interface Language from English to Spanish

### ISSUE THREAD

**Issue by jgrant29** [common-voice/sentence-collector#645]
I just noticed that the system fails to translate majority of the website to Spanish when switching the interface language from English to Spanish.  The only change made is the "English" to "Inglés" under "Your languages:"

Here's a picture of what the system interface looks like after switching from English to Spanish:

<img width="1461" alt="Screen Shot 2022-10-28 at 10 51 06 AM" src="https://user-images.githubusercontent.com/8107598/198700675-af0a90ed-77ea-475d-9072-b9600137bd9a.png">

**Comment by MichaelKohler** [comment]
Thanks for filing this. It looks like for Spanish not all the user interface has been translated yet (for both the Common Voice website and Sentence Collector). Translations can be submitted here: https://pontoon.mozilla.org/es/common-voice/web/locales/en/messages.ftl . Would you be interested in helping out with translations? :)

New approved translations get released to the website every time the website gets released. The release cadence may be different between both websites.

I'm closing this issue as there is no code change to be done here and we don't need to track translation status for each language in a GitHub issue.

**Comment by jgrant29** [comment]
Thanks for the information. 

However, what is odd here is that Espanol is on Common Voice (works perfectly) but not on the sentence collector.  The Sentence Collector lists Espanol as Spanish but Common Voice calls it Espanol.  I'm not a language expert but I believe both are the same language.

**Comment by MichaelKohler** [comment]
> However, what is odd here is that Espanol is on Common Voice (works perfectly) but not on the sentence collector

It looks like many of the Common Voice parts were initially translated but there are also some parts that are not translated (probably ones that were added later on). The Sentence Collector parts were added later as well.

>  The Sentence Collector lists Espanol as Spanish but Common Voice calls it Espanol. I'm not a language expert but I believe both are the same language.

Yes, they are. On both websites the language name is always in the selected language if they are translated. If you go to https://commonvoice.mozilla.org/sentence-collector/#/es/profile the languages in the dropdown are also in Spanish.

**Comment by jgrant29** [comment]
> Yes, they are. On both websites the language name is always in the selected language if they are translated. If you go to https://commonvoice.mozilla.org/sentence-collector/#/es/profile the languages in the dropdown are also in Spanish.

Yes, I see that, but if the main Common Voice platform has ESPANOL translated, then the Sentence Collector should have ESPANOL too, yes?  The only reason I'm saying this is because you said Spanish is not available on Pontoon — the language is supposed to be ESPANOL on the Sentence Collector, not SPANISH :)

**Comment by jgrant29** [comment]
SPANISH aka ESPANOL on Common Voice…

<img width="1668" alt="Screen Shot 2022-10-28 at 11 47 34 AM" src="https://user-images.githubusercontent.com/8107598/198710170-5c8ac844-fd17-4295-8b51-0857a6bd3458.png">

**Comment by MichaelKohler** [comment]
> Yes, I see that, but if the main Common Voice platform has ESPANOL translated, then the Sentence Collector should have ESPANOL too, yes? The only reason I'm saying this is because you said Spanish is not available on Pontoon

Generally, yes. I think there was a misunderstanding. I don't mean that Spanish does not exist at all, I'm saying that not all parts have been translated. The translations for both the Common Voice website and the Sentence Collector website are handled here: https://pontoon.mozilla.org/es/common-voice/web/locales/en/messages.ftl/. Currently 62% of all strings are translated. Many of the missing translations are from the Sentence Collector website, but there are also some missing for Common Voice.

Example on https://commonvoice.mozilla.org/es/about:
![image](https://user-images.githubusercontent.com/330324/198828573-77ec397a-4db2-456d-b2e0-812d05f99c5e.png

Translations for Common Voice are a community effort.

> the language is supposed to be ESPANOL on the Sentence Collector, not SPANISH :)

I don't know what you mean by that.

**Comment by jgrant29** [comment]
Hi Michael, thanks for clarifying  —  I was confused about the translation process.   Sorry for my abrupt thread about this issue. Regarding Español and Spanish, I was referring to the fact that "Spanish" is listed as "Español" on the main Common Voice Platform. In contrast, "Español" is listed as "Spanish" on the Sentence Collector. From what I've found online, "Spanish" is the English translation of "Español". [Here's an article referencing the differences.](https://franciscosalvetti.com/difference-espanol-spanish). Thanks again for helping me! Again, I appreciate your support and am sorry for my abrupt message in this thread.
