### ISSUE TITLE
remove all pending-review sentences on nan-tw from a specific source

### ISSUE THREAD

**Issue by irvin** [common-voice/sentence-collector#657]
Hi,

tl;dr
Please help us remove all the pending review sentences from the source - https://github.com/moztw/cc0-sentences/blob/7651b162ee5f39278a37992dbbd52a28f335580f/nan-TW/taioaan-dict.txt⁩

--

Last quarter, we collaborated with a Taiwanese online dictionary to add their phrases into sentences collector, and already reviewed a few thousand into Common Voice. There are 43K sentences in the review queue, but we think the data from that source is enough. Please help us remove all pending one and we will start working on collecting other sources and types of sentences.

Irvin

**Comment by MichaelKohler** [comment]
This is now fully deployed and the sentences are removed.
