### ISSUE TITLE
Adding and rejecting only 1 sentence results in unresponsive confirm button (Vanadium)(android13)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/sentence-collector#660]
To reproduce:
Add only 1 sentence in the sentence collector. (German in my case)
Because of typos, i rejected my own sentence in the review.
Please see screenshot.
![Screenshot_20230107-215955](https://user-images.githubusercontent.com/92784377/211170438-4320b333-6c4f-403f-88c2-cb19940443a7.png)

When tapping on confirn nothing happens - contributor has to reload the page.

Google Pixel 6 pro
Android13 GrapheneOs TQ1A.230105.002.2023010300
Vanadium Browser 108.0.5359.128

This could also affect desktop/laptop contribution....

**Comment by MichaelKohler** [comment]
Thanks for bringing this up. The Sentence Collector now has moved to https://commonvoice.mozilla.org/write and therefore is now hosted in the main Common Voice repository. That being said, this issue is no longer relevant as that part of the code has been rewritten.
