### ISSUE TITLE
Add link to website under Get Involved

### ISSUE THREAD

**Issue by danielsjf** [Common-Voice/sentence-collector#74]
There is a link in the development thread, but it is a bit hard to find (mentioned halfway the thread). It could be useful to also add a link here on Github in the Readme.

**Comment by MichaelKohler** [comment]
Good idea, thanks!

**Comment by MichaelKohler** [comment]
The current link is https://common-voice.github.io/sentence-collector/ . @nukeador could you add it to the "website" field of the repository?

**Comment by nukeador** [comment]
Done
