### ISSUE TITLE
Seperating Chinese into HK, CN and TW

### ISSUE THREAD

**Issue by irvin** [Common-Voice/sentence-collector#76]
Current we only have `Chinese` in the dropdown box of language, they should separate into 
- (zh-TW) Chinese (Taiwan)
- (zh-HK) Chinese (Hong Kong)
- (zh-CN) Chinese (China)

Which is also separated in current data
https://github.com/mozilla/voice-web/tree/master/server/data

**Comment by nukeador** [comment]
I assume this is the way it should be, or these just accents?

For example for Spanish, the language is the same, it only change the accent and that's why there is only one Spanish.

**Comment by irvin** [comment]
In these three sets of sentences, we will have more accents options when recording. Eg., 

zh-cn - Accents: Beijing, Southern, North East, West (There will be more in fact, I'm not familiar with them)
zh-hk (Cantonese) - Accents: Hong Kong, Guangzhou, Macau
zh-tw - Accents: linguistic researcher had suggested we separate accents by 20 cities people birth.

**Comment by MichaelKohler** [comment]
Thanks @irvin . Creating those new buckets should be simple, however we will also need to do this on the staging/prod database.

**Comment by MichaelKohler** [comment]
Currently languages are listed with their native language and the English name.

Example: "Deutsch (German)"

@irvin could you provide this for all three languages?

**Comment by irvin** [comment]
@MichaelKohler 
zh-cn: Chinese (China)
zh-tw: Chinese (Taiwan)
zh-hk: Chinese (Hong Kong)

**Comment by irvin** [comment]
zh-cn: 简体中文 (中国) (Simplified Chinese - China)
zh-tw: 正體中文 (台灣) (Traditional Chinese - Taiwan)
zh-hk: 繁體中文 (香港) (Traditional Chinese - Hong Kong)

or shorter 

zh-cn: 简体中文 (中国) (Chinese - China)
zh-tw: 正體中文 (台灣) (Chinese - Taiwan)
zh-hk: 繁體中文 (香港) (Chinese - Hong Kong)

or even shorter

zh-cn: 中文 (中国) (Chinese - China)
zh-tw: 中文 (台灣) (Chinese - Taiwan)
zh-hk: 中文 (香港) (Chinese - Hong Kong)

**Comment by MichaelKohler** [comment]
We will need to perform some changes on the database, and then this will be done. I will inform @irvin once this is done so he can test and make sure we're not breaking anything.

**Comment by nukeador** [comment]
@Gregoor FYI that we are doing this change. Please let us know if you have ant flags.

**Comment by MichaelKohler** [comment]
FWIW, these locale codes match the already existing ones in voice-web, so this should be fine

**Comment by MichaelKohler** [comment]
@irvin this is now in production, you will need to remove "Chinese" from your profile and add the new variants
