### ISSUE TITLE
Submit form is not clear that sentences should entering per line or not

### ISSUE THREAD

**Issue by irvin** [Common-Voice/sentence-collector#77]
I don't think the submit form is clear indicate that sentences should enter 1) **per line** and 2) **without period** 

<img width="686" alt="2019-01-09 1 30 10" src="https://user-images.githubusercontent.com/165936/50848092-3bcc6900-13ae-11e9-96c8-8a2642543500.png">

**Comment by MichaelKohler** [comment]
At least English and German sentences can be splitted by dot if they are on the same line and not separate. This might not work for all languages though, as I'd say not all languages use a period as terminator. Also I've not tested other scripts and how the website behaves with these if everything is on a single line and terminated by a period.

```
This is the first sentence. This is the second sentence. And so forth. Blabla bla.
```

```
This is the first sentence
This is the second sentence
And so forth
Blabla bla
```

behave the same for me.

@nukeador thoughts?

**Comment by irvin** [comment]
It would be much better to force the user separate them by hands, or I'm worried that we will end up dealing with a copy-pasted article with this 'feature'...

**Comment by nukeador** [comment]
I'm confused, I thought new line meant new sentence, isn't that the case? Is that a problem for other languages?

If that's already the case and not a problem, let's add a small clarification "Enter sentences (one per line)"

**Comment by MichaelKohler** [comment]
> I'm confused, I thought new line meant new sentence, isn't that the case? Is that a problem for other languages?

It is.

> If that's already the case and not a problem, let's add a small clarification "Enter sentences (one per line)"

The thing is that this is not necessarily necessary. If we go down that road, we should enforce it somehow, no idea how though without going back to the period which might not work for all languages.

**Comment by nukeador** [comment]
How new line→new sentence is a problem for some languages?

We intentionally used this because we want to enable people to c&p hundreds or thousands of already gathered sentences into the tool.

**Comment by MichaelKohler** [comment]
I'm not able to articulate myself here, sorry. There is *no* problem with one sentence per line, none at all. But we also additionally split on periods if it's not one per line. Should we force it to be one per line? If so, how?

**Comment by MichaelKohler** [comment]
Nevermind, we need to go down the road of only one per line. Not sure how we can verify this, so I didn't add any validation. This will be introduced by https://github.com/Common-Voice/sentence-collector/pull/83 and see also #78
