### ISSUE TITLE
(Chinese) The auto-added period after sentences on review tool should be full-width

### ISSUE THREAD

**Issue by irvin** [Common-Voice/sentence-collector#78]
1. We don't have period inn the current data set.
2. If we want to add period, they should be full-width `。` for Chinese.

<img width="856" alt="2019-01-09 1 33 22" src="https://user-images.githubusercontent.com/165936/50848248-b4332a00-13ae-11e9-8b7f-6038e4d8dece.png">

**Comment by MichaelKohler** [comment]
Yeah, this should be 1:1 the same as entered, will check if we just add it in the code..

**Comment by irvin** [comment]
I submit the sentences without period when testing

**Comment by MichaelKohler** [comment]
Yep, definitely not a display issue only.

```
updatedText = updatedText.replace(REGEX_ALL_PIPE, '. ');
```

I love removing lines!

**Comment by MichaelKohler** [comment]
Yep, we need to go down the road of "really only one sentence per line"
