### ISSUE TITLE
Clarify number of approved sentences per locale

### ISSUE THREAD

**Issue by nukeador** [Common-Voice/sentence-collector#79]
We are currently talking about unreviewed and reviewed sentences but we are not talking about how many have been approved (enough positive reviews) to get a sense of locale progress.

I think this only makes sense in the homepage when you are logged in.

**Comment by MichaelKohler** [comment]
I like this!

**Comment by nukeador** [comment]
I've changed a bit the wording of this issue, realizing that the voice site use validated for review.
