### ISSUE TITLE
Frontend refresh

### ISSUE THREAD

**Issue by nukeador** [Common-Voice/sentence-collector#8]
We need to adapt the current temporal frontend to something more friendly.

Elements from the UX prototype can be re-used:

https://projects.invisionapp.com/share/24OV89R65VW#/screens/328648306

(note this prototype includes more features than our current MVP)

**Comment by nukeador** [comment]
We have decided not to include any visual refresh for the MVP. We'll just focus on any bugs impacting the current workflow.

**Comment by MichaelKohler** [comment]
I'm closing this one for now. Let's open a new issue once we want to integrate the full design that is being defined.
