### ISSUE TITLE
Decrease importance of review when adding sentences

### ISSUE THREAD

**Issue by nukeador** [Common-Voice/sentence-collector#80]
I got a few people confused about the review step before confirming the sentences you have added, making them think:

- It was mandatory.
- Just completing the review was the way to finish the process.

I suggest we move that to a place that decreases its importance and make clear it's optional, maybe moving it down and change wording to:

"If you want, you can also review your sentences now before submitting them"

**Comment by MichaelKohler** [comment]
Should we also rename the Review "Submit" button to "Finish Review" so it can't be confused with the "Submit" button for the sentences?
