### ISSUE TITLE
Add discussion link

### ISSUE THREAD

**Issue by nukeador** [Common-Voice/sentence-collector#87]
It would interesting to link where the conversations about sentence collection are happening:

https://discourse.mozilla.org/tags/c/voice/sentence-collection

Link text: Discourse

**Comment by MichaelKohler** [comment]
The links at the bottom of the navigation can be found here: 

https://github.com/Common-Voice/sentence-collector/blob/89d4cc67ebd04c5f58f05c85f76c05ef354e1388/web/src/components/header.jsx#L24

This new link should be added above "Report Bugs (GitHub"). Please refer to the README on how to set up the local dev environment. Happy to help if somebody wants to tackle this and gets stuck.
