### ISSUE TITLE
Create Staging Environment

### ISSUE THREAD

**Issue by MichaelKohler** [Common-Voice/sentence-collector#89]
Once we are in Beta, we do not want to risk any breakage or inconsistencies in the database. We should set up a full staging environment, this would include:

* Seperate GH Pages for staging builds
* Seperate Kinto DB (or Bucket?) for staging data

Currently there are some hardcoded parts where the Kinto Bucket is references, but this could be made dynamic somehow. This means we might be okay with just having a separate Kinto Bucket instead of a separate Kinto instance.

@nukeador thoughts?

**Comment by nukeador** [comment]
What are the implications server side of this?

**Comment by MichaelKohler** [comment]
We would need either a separate Bucket within the same Kinto instance or a new Kinto instance. I'd vote for the former due to resources.

**Comment by nukeador** [comment]
Cool, let's document the exact operations that need to be done server side so we can ask partsys.

**Comment by MichaelKohler** [comment]
sentencecollector.staging.k8s.michael.network/
