### ISSUE TITLE
Add spinner to validating/uploading hints

### ISSUE THREAD

**Issue by MichaelKohler** [Common-Voice/sentence-collector#95]
Once https://github.com/Common-Voice/sentence-collector/pull/94/files is merged, there will be an additional sentence displayed when validating/submitting the sentences. Would be nice if we could add a spinner to this, so the user has at least the impression of something going on during that time.

Validating: https://github.com/Common-Voice/sentence-collector/pull/94/files#diff-2802560281c4000efd4ce5b6df4c39e8R61
Submitting: https://github.com/Common-Voice/sentence-collector/pull/94/files#diff-679b4f83a681c3d993c1e519691dc978R83

The same goes for review-form.jsx once https://github.com/Common-Voice/sentence-collector/pull/158 is merged.

**Comment by amanriquez** [comment]
:) Yes definitely, will need a little bit more time though to tackle this one.

**Comment by MichaelKohler** [comment]
Sure, feel free to ask any questions here that might come up :)

**Comment by amanriquez** [comment]
Hey Michael, just letting you know that I haven't forgotten about this issue. Got busy and I also need to study my React  much more so I can solve this, which I have been doing. If you have the time could you give me some clues as to how this should be solved? Would the spinner be a component by itself? which files would need changing? Can it be from a library or it has to be from scratch? Thank you

**Comment by MichaelKohler** [comment]
Sorry for the late answer. Happy to hear you're still interested in fixing this and I'm still happy to help. I'd say the most straightforward way would be to use a CSS spinner, such as https://loading.io/css/ . The CSS for this can be added in `root.css`.

This could then replace the button text in case there is a pending action. So in case of `confirm-firm.jsx` for example, we're currently testing for `pendingSentences` and if that's true (there is a pending action, we show the full HTML block after that). The same could be done for the button after that block and change the content of the button depending on that state, e.g. keeping "Confirm" if `pendingSentences` is `false` and if it's `true` you could return the necessary JSX/HTML to show the spinner. You can use a ternary operation for this:

```
{ pendingSentences ? 
  "Confirm" : (<div>necessaryHTML</div>) }
```

Please note, I just wrote this example, there might be syntax errors as I didn't test this ;)

Does that make sense? Happy to discuss this approach, this is just one approach that came to my mind now.

**Comment by helenatxu** [comment]
Hello @MichaelKohler, I'm looking to make my first contribution and this seems a good one to start with. Is it fixed? Can I take it?

**Comment by MichaelKohler** [comment]
@helenatxu I'm not sure if @amanriquez is working on something for this, though I'd say 13 days is a good timeframe to assume no. Always hard to judge with open source if a person is working on something everybody's time is limited :)

Do you have any questions regarding the approach I've outlined above? Or do you have a better suggestion?

**Comment by helenatxu** [comment]
Thanks @MichaelKohler for your answer. I will take a look more in depth and I will get back to you.

**Comment by helenatxu** [comment]
@MichaelKohler it seems **this** (the page after validating some sentences) is one of the places where it should appear the spinner, right? Where do you expect it to appear in the page? For example in the center of the page, or in the upper right corner? 
 
![screen shot 2019-02-17 at 20 24 26 2](https://user-images.githubusercontent.com/881000/52913604-2c680600-32f2-11e9-92e5-8d4d9b04f2bf.png)

In addition, we may also show some small text asking the user to wait a little bit while the sentences are being uploaded, so they don't leave the page until is done. What do you think?

**Comment by MichaelKohler** [comment]
Please note that this is about the sentence collection, not the voice collection. The sentence collection currently lives outside of voice.mozilla.org at https://common-voice.github.io/sentence-collector/ . 

The views to change are:
* Add (sidebar) -> initial form there
* Add (sidebar) -> view after initial submission ("confirm")
* Review (sidebar) -> this form when submitting

**Comment by MichaelKohler** [comment]
Yes, just saw your edit. That's one place I would like to have this. The other two forms mentioned above as well. I fully agree with the centering of that sentence, good catch!

**Comment by MichaelKohler** [comment]
And I personally would change the content of the button to be a spinner once it gets deactivated. Or alternatively add the spinner to the sentence.

**Comment by helenatxu** [comment]
@MichaelKohler awesome, I set up all the environment and I already have the project running locally, so I will start right now to test some changes. Thanks for your ideas!

**Comment by helenatxu** [comment]
Hello @MichaelKohler I was playing around a little bit trying different options. One option could be the to hide the button once deactivated, and instead show the spinner with the text next to it. 

Another option would be show **inside** the button a spinner (as in this examples in [https://loading.io/button/](url) ). But the last option takes more CSS code, as I would need to import two different CSS files.

What do you think about this two solutions?

**Comment by MichaelKohler** [comment]
Fully removing the button and only showing the text with a spinner is a valid option as well, indeed. Would probably need to test this to judge this better. I think it's worth doing a prototype with this. Would you like to go down that road?

> But the last option takes more CSS code, as I would need to import two different CSS files.

That's quite a lot of lines of CSS, I honestly don't think we benefit a lot if we add that much CSS.

**Comment by helenatxu** [comment]
@MichaelKohler yes, I will work on it right now

**Comment by helenatxu** [comment]
> Fully removing the button and only showing the text with a spinner is a valid option as well, indeed. Would probably need to test this to judge this better. I think it's worth doing a prototype with this. Would you like to go down that road?

Yes, I will work on it right now.

> 
> > But the last option takes more CSS code, as I would need to import two different CSS files.
> 
> That's quite a lot of lines of CSS, I honestly don't think we benefit a lot if we add that much CSS.

I think the same, that's why I wanted to ask you before working on it. Let's try the hide button option then.

**Comment by helenatxu** [comment]
Hello @MichaelKohler I finally came up with two solutions :)

I researched a little bit more and tried different solutions I found, so I finally managed to have the spinner inside the button once you clicked on it, at the same time of disabling it and showing the message.

But I tried the hide button and show spinner and text solution, so we can compare both.

I made two prototypes for both solutions in Codepen that you can check here: [https://codepen.io/helenatxu/pen/Noegjd](url)

And here: [https://codepen.io/helenatxu/pen/qgLXMq](url)

What do you think about this two versions? The button one seems prettier but both are finde. Or maybe you have something better in mind.

**Comment by MichaelKohler** [comment]
Amazing to have both to test with, thanks! I agree with you, I like the button version better as well. And the amount of CSS needed seems to be reasonable as well. Let's go for this :)

**Comment by helenatxu** [comment]
Great! I'm learning React so I'm relatively new to its syntax and how it works, but I think one good way to implement this solution would be to create a new custom component for this button. Am I right?

**Comment by MichaelKohler** [comment]
A separate component would be nice, as future changes (e.g. different class name for example) would only need one change compared to three changes without component. Of course, it's one line in the component, so it's gonna be a very small component.

**Comment by helenatxu** [comment]
I will try that and I will get back to you when I have something working. Thanks!

**Comment by helenatxu** [comment]
Hello @MichaelKohler, I think I've found another bug/issue in the code that is causing me problems to solve this.
In **submit-form.jsx**, in the section of the confirmation buttons there is a condition the app uses to display the button and messages, `parsingSentences`.

When you access for the first time to the "Add" section, `parsingSentences` is true. But if you submit any sentence or even if you cancel the submitting, when it takes you back to the "Add" section again, `parsingSentences` is false. That doesn't make much sense to me, it confuses me about how it works and I'm not sure if that behavior is correct.

Could you guide me a little bit with this?

**Comment by MichaelKohler** [comment]
> When you access for the first time to the "Add" section, `parsingSentences` is `true`. But if you submit any sentence or even if you cancel the submitting, when it takes you back to the "Add" section again, `parsingSentences` is `false`. That doesn't make much sense to me, it confuses me about how it works and I'm not sure if that behavior is correct.

That's odd. At which stage did you log this? This seems to be the complete opposite of what we want. Also, was the sentence displayed even though it shouldn't have been?

* Initially false when going to the "Add" page
* True when clicking the Submit button (until it's done uploading)
* False when canceling

**Comment by helenatxu** [comment]
Ok, thanks for the clarification. I will check again the behaviour without my code to figure out if I was doing wrong.

In other hand, I feel a bit stuck while trying to get my small component to work in other files, I'm not sure how to do it. Maybe I should just add the lines I need in each view. What do you think?

**Comment by helenatxu** [comment]
One more question, for example, in this piece of code:
```
{ parsingSentences && (
        <p>
              <strong>Sentences are being validated. This can take a few seconds depending on the number of sentences added.</strong>
        </p>
 )}
```

Would be the same as:

```
{ parsingSentences ?
        <p>
              <strong>Sentences are being validated. This can take a few seconds depending on the number of sentences added.</strong>
        </p>
}
```

**Comment by MichaelKohler** [comment]
> In other hand, I feel a bit stuck while trying to get my small component to work in other files, I'm not sure how to do it. Maybe I should just add the lines I need in each view. What do you think?

I think that would be fine for now.

And regarding the second comment, yes, that would be the same (though I think the second example would need a third part (not sure though). If `parsingSentences` is true, it outputs the <p> tags, if not it outputs undefined and therefore doesn't get rendered.

**Comment by helenatxu** [comment]
Thanks for pointing that out. BTW, regarding getting the small component to work in different files, I finally got it working fine (sorry for freaking out for a moment). 

I also discovered what I was doing wrong to get the unexpected value in parsingSentences, it was because I modified the code while running, very silly.

Tomorrow if I have a bit of time I will make the pull request :)

**Comment by helenatxu** [comment]
@MichaelKohler I already made my PR :)

**Comment by MichaelKohler** [comment]
I'll deploy this in a few minutes.
