### ISSUE TITLE
Sentences with 1 negative review dissapear from other users review queue

### ISSUE THREAD

**Issue by nukeador** [Common-Voice/sentence-collector#96]
Steps to reproduce:

- Add a new sentence with user 1
- Check with user 1 and user 2 that the sentence is in your review queue
- Review with a "no" from user 1
- Check with user 2 the review queue
- The sentence has disappeared for user 2

I don't think this is the expected behavior.

**Comment by MichaelKohler** [comment]
Can you still reproduce this? I can't, neither locally nor on https://common-voice.github.io/sentence-collector/# .

**Comment by nukeador** [comment]
I no longer can reproduce this, closing.
