### ISSUE TITLE
Error 400 if you login with email

### ISSUE THREAD

**Issue by tauheedul** [Common-Voice/sentence-collector#97]
If you use your email as the login. It displays a non helpful error 400 message.

Suggest instead that they must use their username

**Comment by MichaelKohler** [comment]
So I assume "Please only use alphanumeric usernames." is not clear enough? Maybe we should add somthing like "username (no email, alphanumeric only)"?

**Comment by tauheedul** [comment]
Hi @MichaelKohler web users have become used to having the choice to type in their email or username interchangeably in the user name field, it's become ubiquitous. It's easily done on mobile, we all go into autopilot sometimes.

Implementation wise, it could have some regular expression to detect if the user is actively typing an email address and display a tooltip with the label you suggested.

Or

The error message returned shouldn't be a generic 400 message, instead the label you suggested should be enough.

In addition, it might be useful to add a label 'Forgotten your username? reset link here.'

**Comment by nukeador** [comment]
Allowing emails at this point would probably mean a legal review, so I'm inclined on avoid any personal information from users for now.

In the future we can ask people for their email or integrate with mozilla's auth0.

**Comment by MichaelKohler** [comment]
What we can do for now:
* Add note to username field label as well
* Note to the user if they enter non-allowed characters while typing

**Comment by tauheedul** [comment]
Thanks @MichaelKohler
