### ISSUE TITLE
Flag sentences submitted in wrong language 

### ISSUE THREAD

**Issue by tauheedul** [Common-Voice/sentence-collector#98]
We should be able to flag sentences that were allocated in the wrong language and indicate what is the correct category instead of rejecting it altogether.

Or indicate that it has been sent back to the author because it was put in the wrong language category and must be resubmitted.

The author profile should have a list of rejected sentences and reasons. So they can review, edit, resubmit or delete it.

**Comment by MichaelKohler** [comment]
Thanks for filing this issue!

@nukeador thoughts on this?

**Comment by nukeador** [comment]
This could be part of the "nice to have" in future version, together with the ability to edit the sentences during the review.

**Comment by MichaelKohler** [comment]
We can directly cover this by https://github.com/Common-Voice/sentence-collector/issues/159
